/* main.trainer - 7 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace trainer {
void trainer_type__03d();  // 0xcdc500
void trainer_id_hash_table();  // 0x135ad40
void trainer_data__03d();  // 0x14522a0
void trainer_data__03d_2();  // 0x14524b0
void trainer_poke__03d();  // 0x1453750
void trainer_type__03d_2();  // 0x1453ab0
void TrainerID();  // 0x146cca0

}  // namespace trainer
