/* main.physics - 11 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "physics_physics_main.h"

namespace physics {
void Collision_mergeResults() { /* 0xa71e0 */ }
void PtCollision() { /* 0xa9940 */ }
// Collision_fluidCollision: implemented in prog/matched/main/
void NpPhysics() { /* 0xb2630 */ }
void NpPhysics_2() { /* 0xb2920 */ }
void NpPhysics_3() { /* 0xb3640 */ }
void NpPhysics_4() { /* 0xb3730 */ }
void NpPhysicsInsertionCallback() { /* 0xb4080 */ }
void CS_FObjSetActiveCollision() { /* 0x13da660 */ }
void CS_FObjSetActiveStaticCollision() { /* 0x13da7a0 */ }
void iconCollisionSize() { /* 0x1444b40 */ }

}  // namespace physics
