/* main.manager - 65 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "manager_manager_main.h"

namespace manager {
void Play_UI_Message() { /* 0x93bd70 */ }
void Stop_UI_netbattle_rank_count_loop() { /* 0xac5500 */ }
void Play_UI_boutique_change() { /* 0xc2a800 */ }
void Play_UI_common_report() { /* 0xc2b2a0 */ }
void Play_UI_common_encount() { /* 0xd0bd80 */ }
void Play_UI_Common_PM_Encount_FX() { /* 0xd81450 */ }
void Play_UI_common_decide() { /* 0xd8c120 */ }
void Play_UI_common_decide_2() { /* 0xd90e60 */ }
void Play_UI_Emotional_Exclamation() { /* 0xda65a0 */ }
void Play_UI_Emotional_Exclamation_2() { /* 0xdae730 */ }
void Play_UI_Gym_a_t0501_g0102_Start() { /* 0xdb5820 */ }
void Play_UI_Lcircuit_Count_Down() { /* 0xdcb680 */ }
void Play_UI_Lcircuit_Start() { /* 0xdd8370 */ }
void Play_UI_Lcircuit_Goal() { /* 0xddb9b0 */ }
void Play_UI_Lcircuit_TimeUp() { /* 0xddbd00 */ }
void Play_UI_Lcircuit_CheckPoint() { /* 0xddd020 */ }
void Play_UI_pbox_error() { /* 0xe63560 */ }
void Play_UI_common_menu_scroll() { /* 0xe640c0 */ }
void Play_UI_pbox_error_2() { /* 0xe64350 */ }
void Play_UI_pbox_error_3() { /* 0xe65f70 */ }
void Set_State_UI_Open() { /* 0xe72c50 */ }
void Set_State_UI_Close() { /* 0xe72ce0 */ }
void Play_UI_common_lv_up_window() { /* 0xf102a0 */ }
void Play_UI_common_lv_gauge_up() { /* 0xf12790 */ }
void Stop_UI_common_lv_gauge_up() { /* 0xf14580 */ }
void Play_UI_common_lv_gauge_up_2() { /* 0xf156b0 */ }
void Play_UI_Gnest_start_Gbattle() { /* 0xf98680 */ }
void Play_UI_Gnest_10sec() { /* 0xfa4cd0 */ }
void Play_UI_Gnest_join() { /* 0xfa7290 */ }
void Play_UI_Gnest_join_2() { /* 0xfad3b0 */ }
void Play_UI_Gnest_ready() { /* 0xfb8700 */ }
void Play_UI_common_report_2() { /* 0xff4640 */ }
void Play_UI_common_report_3() { /* 0xff75a0 */ }
void Play_UI_Emotional_Hungry() { /* 0x112a570 */ }
void Play_UI_Emotional_Hungry_2() { /* 0x112b6e0 */ }
void Play_UI_Emotional_Hungry_3() { /* 0x112c850 */ }
void Play_UI_Emotional_Sleep() { /* 0x1138890 */ }
void Play_UI_Emotional_Awake() { /* 0x1138ab0 */ }
void Play_UI_Camp_Notice() { /* 0x11bec80 */ }
void Play_UI_Emotional_Hungry_4() { /* 0x11ffb70 */ }
void Play_UI_Camp_Cooking_Transition() { /* 0x12459c0 */ }
void Play_UI_Camp_Cooking_NutsOnBoard() { /* 0x124a4e0 */ }
void Play_UI_Camp_Cooking_NutsOut() { /* 0x124a650 */ }
void Play_UI_Camp_Cooking_Last3Sec() { /* 0x124d3a0 */ }
void Play_UI_Camp_Licence() { /* 0x1265890 */ }
void Play_UI_Common_window_open() { /* 0x126ef00 */ }
void Play_UI_Common_window_close() { /* 0x126f050 */ }
void Play_UI_network_result() { /* 0x1270b30 */ }
void Play_UI_Camp_Cooking_Pop() { /* 0x1274190 */ }
void Play_UI_Camp_Cooking_Start() { /* 0x1274d40 */ }
void Play_UI_Message_2() { /* 0x13098d0 */ }
void Play_UI_pbox_error_4() { /* 0x1336af0 */ }
void Play_UI_common_menu_close() { /* 0x141e680 */ }
void Play_UI_tournament_fanfare() { /* 0x1441b30 */ }
void Play_UI_map_open() { /* 0x144a5a0 */ }
void Play_UI_common_card_turn() { /* 0x145df00 */ }
void Play_UI_common_card_turn_2() { /* 0x146fe10 */ }
void Play_UI_common_card_turn_3() { /* 0x1471520 */ }
void Play_UI_common_waza_forget() { /* 0x14a8c00 */ }
void Play_UI_common_decide_3() { /* 0x14e3350 */ }
void Play_UI_common_decide_4() { /* 0x14e3860 */ }
void Play_UI_common_decide_5() { /* 0x14e38b0 */ }
void Play_UI_common_select() { /* 0x14e5e00 */ }
void Play_UI_picturebook_open() { /* 0x151adf0 */ }
void Play_UI_picturebook_open_2() { /* 0x153a0e0 */ }

}  // namespace manager
