/* main.taildest - 1 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "taildest_save_main.h"

namespace save {
void save_d() { /* 0x5e4620 */ }

}  // namespace save
