/* main.taildest - 13 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "taildest_battle_main.h"

namespace battle {
void battle_battle_command_2() { /* 0x89f3c0 */ }
void battle_btl_data_holder_2() { /* 0x8a08b0 */ }
void battle_poke_party_2() { /* 0x8a2670 */ }
void battle_btl_cmd_data_holder_2() { /* 0x8a3f60 */ }
void battle_watch_party_2() { /* 0x8b4c10 */ }
void battle_watch_command_2() { /* 0x8b64c0 */ }
void battle_watch_clienttimer_2() { /* 0x8b8150 */ }
void battle_watch_target_party_2() { /* 0x8b8e60 */ }
void battle_btlwatch_data_holder_2() { /* 0x8b9a50 */ }
void battle_watch_cmd_2() { /* 0x8ba440 */ }
void battle_btlwatch_async_data_holder_2() { /* 0x8bb2a0 */ }
void battle_watch_body_2() { /* 0x8bd880 */ }
void battle_common() { /* 0x9470c0 */ }

}  // namespace battle
