/* sdk.taildest - 64 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "taildest_sdk_sdk.h"

namespace sdk {
void sub_1d5f0() { /* 0x1d5f0 */ }
void sub_29450() { /* 0x29450 */ }
void sub_14d680() { /* 0x14d680 */ }
void sub_373ef0() { /* 0x373ef0 */ }
void sub_374190() { /* 0x374190 */ }
void sub_374450() { /* 0x374450 */ }
void sub_3746d0() { /* 0x3746d0 */ }
void sub_374970() { /* 0x374970 */ }
void sub_374d50() { /* 0x374d50 */ }
void sub_38c630() { /* 0x38c630 */ }
void sub_39adb0() { /* 0x39adb0 */ }
void sub_39b080() { /* 0x39b080 */ }
void sub_3c3e10() { /* 0x3c3e10 */ }
void sub_3c3f40() { /* 0x3c3f40 */ }
void sub_3c4050() { /* 0x3c4050 */ }
void sub_3c4090() { /* 0x3c4090 */ }
void sub_3c40d0_sdk_3c40d0() { /* 0x3c40d0 */ }
void sub_3c40f0() { /* 0x3c40f0 */ }
void sub_3c4290() { /* 0x3c4290 */ }
void sub_3c42b0() { /* 0x3c42b0 */ }
void sub_3c42d0() { /* 0x3c42d0 */ }
void sub_3c42f0() { /* 0x3c42f0 */ }
void nvn_no_vsync_capability_2() { /* 0x3c4580 */ }
// sub_3c4790_sdk_3c4790: implemented in prog/matched/sdk/
// sub_3c47a0: implemented in prog/matched/sdk/
// sub_3c47c0: implemented in prog/matched/sdk/
void sub_3c8ff0() { /* 0x3c8ff0 */ }
void sub_3f18e0() { /* 0x3f18e0 */ }
void sub_40b3d0() { /* 0x40b3d0 */ }
void sub_40db90() { /* 0x40db90 */ }
void sub_413ce0() { /* 0x413ce0 */ }
void sub_4166f0() { /* 0x4166f0 */ }
void sub_4167e0() { /* 0x4167e0 */ }
void sub_416a80() { /* 0x416a80 */ }
void sub_42c7f0() { /* 0x42c7f0 */ }
void sub_42e420() { /* 0x42e420 */ }
void sub_42e570() { /* 0x42e570 */ }
void sub_4314c0() { /* 0x4314c0 */ }
void sub_45f310() { /* 0x45f310 */ }
void sub_45f7d8() { /* 0x45f7d8 */ }
void sub_45fca0() { /* 0x45fca0 */ }
void sub_460168() { /* 0x460168 */ }
void sub_460630() { /* 0x460630 */ }
void sub_460af8() { /* 0x460af8 */ }
void sub_460fc0() { /* 0x460fc0 */ }
void sub_461468() { /* 0x461468 */ }
void sub_461910() { /* 0x461910 */ }
void sub_463048() { /* 0x463048 */ }
void sub_463568() { /* 0x463568 */ }
void sub_463a88() { /* 0x463a88 */ }
void sub_463fa8() { /* 0x463fa8 */ }
void sub_4644c8() { /* 0x4644c8 */ }
void sub_4649e8() { /* 0x4649e8 */ }
void sub_464f08() { /* 0x464f08 */ }
void sub_465408() { /* 0x465408 */ }
void sub_465908() { /* 0x465908 */ }
void sub_49f258() { /* 0x49f258 */ }
void sub_49f270_sdk_49f270() { /* 0x49f270 */ }
// sub_49f340: implemented in prog/matched/sdk/
void sub_49f358() { /* 0x49f358 */ }
void sub_49f3b0() { /* 0x49f3b0 */ }
void sub_4b5a60() { /* 0x4b5a60 */ }
void sub_4ff0d8() { /* 0x4ff0d8 */ }
void sub_5019f0() { /* 0x5019f0 */ }

}  // namespace sdk
