/* main.gflib3 - 308 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "gflib3_gflib3_main.h"

namespace gflib3 {
// static_const_char_boost_detail_core_typeid__void_const_v: implemented in prog/matched/main/
void gflib3_reallocatable_resource() { /* 0xad0 */ }
// gflib3_signal_template_hpp_394_15_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_397_15_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_160_13_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_164_13_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_692_11_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_394_15_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_397_15_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_160_13_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_164_13_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_692_11_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_394_15_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_397_15_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_160_13_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_164_13_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_692_11_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_402_15_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_521_15_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_402_15_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_521_15_name_T_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_402_15_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_521_15_name_T_3: implemented in prog/matched/main/
// gflib3_signal_template_hpp_497_15_name_T: implemented in prog/matched/main/
// gflib3_connection_hpp_149_13_name_T_lambda_at_C: implemented in prog/matched/main/
// gflib3_signal_template_hpp_537_13_name_T: implemented in prog/matched/main/
// gflib3_signal_template_hpp_497_15_name_T_2: implemented in prog/matched/main/
// gflib3_connection_hpp_149_13_name_T_lambda_at_C_2: implemented in prog/matched/main/
// gflib3_signal_template_hpp_537_13_name_T_2: implemented in prog/matched/main/
void nn_ldn_SetStationAcceptPolicy() { /* 0x631990 */ }
void gflib3_tlsf_pool() { /* 0x65efa0 */ }
void gflib3_tlsf_pool_resource() { /* 0x65f360 */ }
void gflnet3_ping() { /* 0x6bc100 */ }
void gflnet3_ping_2() { /* 0x6bc290 */ }
void gflnet3_ping_3() { /* 0x6bc550 */ }
void gflnet3_ping_4() { /* 0x6bc7f0 */ }
void gflnet3_ping_5() { /* 0x6bc9e0 */ }
void gflnet3_ping_6() { /* 0x6bcc80 */ }
void gflnet3_ping_7() { /* 0x6bce70 */ }
void gflnet3_ping_8() { /* 0x6bd110 */ }
void gflnet3_sync_ping_data_holder() { /* 0x6bd550 */ }
void gflnet3_sync_ping_data_holder_2() { /* 0x6bd6c0 */ }
void gflnet3_sync_ping_data_holder_3() { /* 0x6bd8c0 */ }
void gflnet3_sync_ping_data_holder_4() { /* 0x6be330 */ }
void gflnet3_block_data_holder() { /* 0x6bfeb0 */ }
void gflnet3_block_data_holder_2() { /* 0x6c0010 */ }
void gflnet3_block_data_holder_3() { /* 0x6c0200 */ }
void gflnet3_block_data_holder_4() { /* 0x6c0a50 */ }
void gflnet3_result() { /* 0x6c0cc0 */ }
void gflnet3_result_2() { /* 0x6c0e10 */ }
void gflnet3_result_3() { /* 0x6c1050 */ }
void gflnet3_result_4() { /* 0x6c13b0 */ }
void gflnet3_result_5() { /* 0x6c15e0 */ }
void gflnet3_result_6() { /* 0x6c1940 */ }
void gflnet3_sync_data_holder() { /* 0x6d4680 */ }
void gflnet3_sync_data_holder_2() { /* 0x6d47c0 */ }
void gflnet3_sync_data_holder_3() { /* 0x6d4e70 */ }
void gflnet3_data() { /* 0x6d5160 */ }
void gflnet3_data_2() { /* 0x6d5260 */ }
void gflnet3_data_3() { /* 0x6d54f0 */ }
void gflnet3_data_4() { /* 0x6d5e60 */ }
void gflnet3_request_cancel() { /* 0x6d8ca0 */ }
void gflnet3_request_cancel_2() { /* 0x6d8e30 */ }
void gflnet3_request_cancel_3() { /* 0x6d8f20 */ }
void gflnet3_request_cancel_4() { /* 0x6d9060 */ }
void gflnet3_request_cancel_5() { /* 0x6d9160 */ }
void gflnet3_request_cancel_6() { /* 0x6d94e0 */ }
void gflnet3_request_cancel_7() { /* 0x6d9770 */ }
void gflnet3_cancel_accepted() { /* 0x6d9880 */ }
void gflnet3_cancel_accepted_2() { /* 0x6d9a10 */ }
void gflnet3_cancel_accepted_3() { /* 0x6d9b10 */ }
void gflnet3_cancel_accepted_4() { /* 0x6d9c70 */ }
void gflnet3_cancel_accepted_5() { /* 0x6d9d80 */ }
void gflnet3_cancel_accepted_6() { /* 0x6da230 */ }
void gflnet3_cancel_accepted_7() { /* 0x6da520 */ }
void gflnet3_request_cancel_all() { /* 0x6da640 */ }
void gflnet3_request_cancel_all_2() { /* 0x6da7d0 */ }
void gflnet3_request_cancel_all_3() { /* 0x6da8c0 */ }
void gflnet3_request_cancel_all_4() { /* 0x6daa00 */ }
void gflnet3_request_cancel_all_5() { /* 0x6dab00 */ }
void gflnet3_request_cancel_all_6() { /* 0x6dae80 */ }
void gflnet3_request_cancel_all_7() { /* 0x6db110 */ }
void gflnet3_sequence_data_holder() { /* 0x6db220 */ }
void gflnet3_sequence_data_holder_2() { /* 0x6db390 */ }
void gflnet3_sequence_data_holder_3() { /* 0x6db5b0 */ }
void gflnet3_sequence_data_holder_4() { /* 0x6dc2b0 */ }
void gflnet3_request_forced_proceed() { /* 0x6dc520 */ }
void gflnet3_request_forced_proceed_2() { /* 0x6dc6c0 */ }
void gflnet3_request_forced_proceed_3() { /* 0x6dc7c0 */ }
void gflnet3_request_forced_proceed_4() { /* 0x6dc900 */ }
void gflnet3_request_forced_proceed_5() { /* 0x6dca10 */ }
void gflnet3_request_forced_proceed_6() { /* 0x6dcf30 */ }
void gflnet3_request_forced_proceed_7() { /* 0x6dd1d0 */ }
void gflnet3_descriptor() { /* 0x6e1400 */ }
void gflnet3_descriptor_2() { /* 0x6e3870 */ }
void gflnet3_logging() { /* 0x6e8130 */ }
void gflnet3_descriptor_3() { /* 0x6e9800 */ }
void gflnet3_descriptor_4() { /* 0x6e9e60 */ }
void gflnet3_descriptor_5() { /* 0x6eb200 */ }
void gflnet3_descriptor_6() { /* 0x6ef000 */ }
void gflnet3_descriptor_7() { /* 0x6f2fc0 */ }
void gflnet3_descriptor_8() { /* 0x6f4200 */ }
void gflnet3_descriptor_9() { /* 0x6f4da0 */ }
void gflnet3_descriptor_10() { /* 0x6f4ec0 */ }
void gflnet3_descriptor_11() { /* 0x6f5a10 */ }
void gflnet3_descriptor_12() { /* 0x6f5ad0 */ }
void gflnet3_descriptor_13() { /* 0x6f5b80 */ }
void gflnet3_descriptor_14() { /* 0x6f5c30 */ }
void gflnet3_descriptor_15() { /* 0x6f5cd0 */ }
void gflnet3_common() { /* 0x6ff450 */ }
void gflnet3_common_2() { /* 0x6fffe0 */ }
void gflnet3_common_3() { /* 0x700080 */ }
void gflnet3_text_format() { /* 0x701310 */ }
void gflnet3_text_format_2() { /* 0x702380 */ }
void gflnet3_text_format_3() { /* 0x7028a0 */ }
void gflnet3_text_format_4() { /* 0x704050 */ }
void gflnet3_text_format_5() { /* 0x704180 */ }
void gflnet3_text_format_6() { /* 0x7067f0 */ }
void gflnet3_text_format_7() { /* 0x709cb0 */ }
void gflnet3_message_lite() { /* 0x70aa80 */ }
void gflnet3_message_lite_2() { /* 0x70ad40 */ }
void gflnet3_message_lite_3() { /* 0x70af20 */ }
void gflnet3_message_lite_4() { /* 0x70aff0 */ }
void gflnet3_message_lite_5() { /* 0x70b190 */ }
void gflnet3_coded_stream() { /* 0x70b430 */ }
void gflnet3_coded_stream_2() { /* 0x70b930 */ }
void gflnet3_zero_copy_stream_impl_lite() { /* 0x70d230 */ }
void gflnet3_zero_copy_stream_impl_lite_2() { /* 0x70d350 */ }
void gflnet3_zero_copy_stream_impl_lite_3() { /* 0x70d4c0 */ }
void gflnet3_zero_copy_stream_impl_lite_4() { /* 0x70d650 */ }
void gflnet3_zero_copy_stream_impl_lite_5() { /* 0x70d800 */ }
void gflnet3_zero_copy_stream_impl_lite_6() { /* 0x70d950 */ }
void gflnet3_zero_copy_stream() { /* 0x70da10 */ }
void gflnet3_wire_format() { /* 0x711730 */ }
void gflnet3_wire_format_2() { /* 0x7118f0 */ }
void gflnet3_wire_format_lite() { /* 0x7141c0 */ }
void gflnet3_wire_format_lite_2() { /* 0x714360 */ }
void gflnet3_wire_format_lite_3() { /* 0x714520 */ }
void gflnet3_wire_format_lite_4() { /* 0x7146c0 */ }
void gflnet3_wire_format_lite_5() { /* 0x714da0 */ }
void gflnet3_generated_message_util() { /* 0x714fd0 */ }
void gflnet3_dynamic_message() { /* 0x715570 */ }
void gflnet3_dynamic_message_2() { /* 0x7160e0 */ }
void gflnet3_message() { /* 0x716bb0 */ }
void gflnet3_message_2() { /* 0x716ca0 */ }
void gflnet3_message_3() { /* 0x717210 */ }
void gflnet3_message_4() { /* 0x7172e0 */ }
void gflnet3_message_5() { /* 0x7173c0 */ }
void gflnet3_message_6() { /* 0x717a80 */ }
void gflnet3_reflection_internal() { /* 0x718e40 */ }
void gflnet3_repeated_field() { /* 0x7190a0 */ }
void gflnet3_reflection_internal_2() { /* 0x719300 */ }
void gflnet3_repeated_field_2() { /* 0x719610 */ }
void gflnet3_reflection_internal_3() { /* 0x719860 */ }
void gflnet3_repeated_field_3() { /* 0x719b70 */ }
void gflnet3_reflection_internal_4() { /* 0x719dc0 */ }
void gflnet3_repeated_field_4() { /* 0x71a0d0 */ }
void gflnet3_reflection_internal_5() { /* 0x71a330 */ }
void gflnet3_repeated_field_5() { /* 0x71a640 */ }
void gflnet3_reflection_internal_6() { /* 0x71a8a0 */ }
void gflnet3_repeated_field_6() { /* 0x71abb0 */ }
void gflnet3_reflection_internal_7() { /* 0x71ae00 */ }
void gflnet3_repeated_field_7() { /* 0x71b100 */ }
void gflnet3_reflection_internal_8() { /* 0x71bf70 */ }
void gflnet3_reflection_internal_9() { /* 0x71c680 */ }
void gflnet3_map() { /* 0x71d830 */ }
void gflnet3_map_field() { /* 0x71d9d0 */ }
void gflnet3_map_2() { /* 0x71dff0 */ }
void gflnet3_map_3() { /* 0x71e190 */ }
void gflnet3_map_4() { /* 0x71e330 */ }
void gflnet3_map_5() { /* 0x71e4d0 */ }
void gflnet3_map_6() { /* 0x71e670 */ }
void gflnet3_map_7() { /* 0x71e810 */ }
void gflnet3_map_8() { /* 0x71e9b0 */ }
void gflnet3_map_9() { /* 0x71eb40 */ }
void gflnet3_map_10() { /* 0x71ecd0 */ }
void gflnet3_map_11() { /* 0x71ee60 */ }
void gflnet3_map_12() { /* 0x71eff0 */ }
void gflnet3_map_13() { /* 0x71f180 */ }
void gflnet3_map_14() { /* 0x71f310 */ }
void gflnet3_map_15() { /* 0x71f4a0 */ }
void gflnet3_map_16() { /* 0x71f630 */ }
void gflnet3_map_17() { /* 0x71f7c0 */ }
void gflnet3_map_field_2() { /* 0x71f950 */ }
void gflnet3_map_18() { /* 0x720180 */ }
void gflnet3_map_19() { /* 0x7206f0 */ }
void gflnet3_map_20() { /* 0x720f10 */ }
void gflnet3_map_21() { /* 0x721810 */ }
void gflnet3_map_22() { /* 0x7219f0 */ }
void gflnet3_reflection_ops() { /* 0x723030 */ }
void gflnet3_extension_set() { /* 0x724300 */ }
void gflnet3_extension_set_2() { /* 0x7248a0 */ }
void gflnet3_extension_set_3() { /* 0x724960 */ }
void gflnet3_extension_set_4() { /* 0x724e00 */ }
void gflnet3_extension_set_5() { /* 0x724ec0 */ }
void gflnet3_extension_set_6() { /* 0x725360 */ }
void gflnet3_extension_set_7() { /* 0x725420 */ }
void gflnet3_extension_set_8() { /* 0x7258c0 */ }
void gflnet3_extension_set_9() { /* 0x725980 */ }
void gflnet3_extension_set_10() { /* 0x725e20 */ }
void gflnet3_extension_set_11() { /* 0x725ee0 */ }
void gflnet3_extension_set_12() { /* 0x726390 */ }
void gflnet3_extension_set_13() { /* 0x726450 */ }
void gflnet3_extension_set_14() { /* 0x726910 */ }
void gflnet3_extension_set_15() { /* 0x7269d0 */ }
void gflnet3_extension_set_16() { /* 0x727280 */ }
void gflnet3_extension_set_17() { /* 0x727340 */ }
void gflnet3_extension_set_18() { /* 0x727820 */ }
void gflnet3_extension_set_19() { /* 0x7278e0 */ }
void gflnet3_extension_set_20() { /* 0x727fa0 */ }
void gflnet3_extension_set_21() { /* 0x728060 */ }
void gflnet3_extension_set_22() { /* 0x728460 */ }
void gflnet3_extension_set_23() { /* 0x7285e0 */ }
void gflnet3_extension_set_24() { /* 0x7286d0 */ }
void gflnet3_extension_set_25() { /* 0x72a340 */ }
void gflnet3_extension_set_26() { /* 0x72a470 */ }
void gflnet3_extension_set_27() { /* 0x72c2f0 */ }
void gflnet3_extension_set_28() { /* 0x72d260 */ }
void gflnet3_generated_message_reflection() { /* 0x72ed90 */ }
void gflnet3_generated_message_reflection_2() { /* 0x730340 */ }
void gflnet3_generated_message_reflection_3() { /* 0x732520 */ }
void gflnet3_generated_message_reflection_4() { /* 0x732950 */ }
void gflnet3_generated_message_reflection_5() { /* 0x733090 */ }
void gflnet3_generated_message_reflection_6() { /* 0x733870 */ }
void gflnet3_generated_message_reflection_7() { /* 0x734c00 */ }
void gflnet3_generated_message_reflection_8() { /* 0x7392b0 */ }
void gflnet3_generated_message_reflection_9() { /* 0x739380 */ }
void gflnet3_generated_message_reflection_10() { /* 0x7397d0 */ }
void gflnet3_generated_message_reflection_11() { /* 0x739ae0 */ }
void gflnet3_generated_message_reflection_12() { /* 0x73b510 */ }
void gflnet3_generated_message_reflection_13() { /* 0x73b710 */ }
void gflnet3_generated_message_reflection_14() { /* 0x73c290 */ }
void gflnet3_extension_set_heavy() { /* 0x73e450 */ }
void gflnet3_extension_set_heavy_2() { /* 0x73e6b0 */ }
void gflnet3_extension_set_heavy_3() { /* 0x73ed10 */ }
void gflnet3_tokenizer() { /* 0x741f40 */ }
void gflnet3_tokenizer_2() { /* 0x742080 */ }
void gflnet3_strtod() { /* 0x742850 */ }
void gflnet3_descriptor_16() { /* 0x742ef0 */ }
void gflnet3_descriptor_17() { /* 0x743640 */ }
void gflnet3_descriptor_18() { /* 0x745120 */ }
void gflnet3_descriptor_19() { /* 0x7455e0 */ }
void gflnet3_descriptor_20() { /* 0x747cb0 */ }
void gflnet3_descriptor_21() { /* 0x748200 */ }
void gflnet3_descriptor_22() { /* 0x7486e0 */ }
void gflnet3_descriptor_23() { /* 0x748dd0 */ }
void gflnet3_descriptor_24() { /* 0x748f90 */ }
void gflnet3_descriptor_25() { /* 0x749680 */ }
void gflnet3_descriptor_26() { /* 0x749930 */ }
void gflnet3_descriptor_27() { /* 0x74b8b0 */ }
void gflnet3_descriptor_28() { /* 0x74bce0 */ }
void gflnet3_descriptor_29() { /* 0x74c130 */ }
void gflnet3_descriptor_30() { /* 0x74d8b0 */ }
void gflnet3_descriptor_31() { /* 0x74d980 */ }
void gflnet3_descriptor_32() { /* 0x74dcd0 */ }
void gflnet3_descriptor_33() { /* 0x74e6d0 */ }
void gflnet3_descriptor_34() { /* 0x74e7a0 */ }
void gflnet3_descriptor_35() { /* 0x74ea30 */ }
void gflnet3_descriptor_36() { /* 0x74f6a0 */ }
void gflnet3_descriptor_37() { /* 0x74f890 */ }
void gflnet3_descriptor_38() { /* 0x74fbb0 */ }
void gflnet3_descriptor_39() { /* 0x750780 */ }
void gflnet3_descriptor_40() { /* 0x750850 */ }
void gflnet3_descriptor_41() { /* 0x750b00 */ }
void gflnet3_descriptor_42() { /* 0x7517f0 */ }
void gflnet3_descriptor_43() { /* 0x7519e0 */ }
void gflnet3_descriptor_44() { /* 0x751ce0 */ }
void gflnet3_descriptor_45() { /* 0x752cf0 */ }
void gflnet3_descriptor_46() { /* 0x752dc0 */ }
void gflnet3_descriptor_47() { /* 0x754650 */ }
void gflnet3_descriptor_48() { /* 0x7553c0 */ }
void gflnet3_descriptor_49() { /* 0x756350 */ }
void gflnet3_descriptor_50() { /* 0x756c30 */ }
void gflnet3_descriptor_51() { /* 0x7576f0 */ }
void gflnet3_descriptor_52() { /* 0x7580c0 */ }
void gflnet3_descriptor_53() { /* 0x758a90 */ }
void gflnet3_descriptor_54() { /* 0x759460 */ }
void gflnet3_descriptor_55() { /* 0x759690 */ }
void gflnet3_descriptor_56() { /* 0x759e40 */ }
void gflnet3_descriptor_57() { /* 0x759ff0 */ }
void gflnet3_descriptor_58() { /* 0x75afc0 */ }
void gflnet3_descriptor_59() { /* 0x75b2d0 */ }
void gflnet3_descriptor_60() { /* 0x75c7d0 */ }
void gflnet3_descriptor_61() { /* 0x75cf00 */ }
void gflnet3_descriptor_62() { /* 0x75d2c0 */ }
void gflnet3_descriptor_63() { /* 0x75e080 */ }
void gflnet3_descriptor_64() { /* 0x75e810 */ }
void gflnet3_descriptor_database() { /* 0x75fb40 */ }
void gflnet3_descriptor_database_2() { /* 0x75fc00 */ }
void gflnet3_descriptor_database_3() { /* 0x760580 */ }
void gflnet3_descriptor_database_4() { /* 0x760a40 */ }
void gflnet3_substitute() { /* 0x761c20 */ }
void nn_ldn_SetStationAcceptPolicy_2() { /* 0xc88f10 */ }
void nn_ldn_SetStationAcceptPolicy_3() { /* 0xd88580 */ }
void nn_ldn_SetStationAcceptPolicy_4() { /* 0x11f09a0 */ }
void gflogo_00_lyt() { /* 0x13056b0 */ }
void nncs2_n_n_srv_nintendo() { /* 0x16c8020 */ }
void nn_pia_session_CreateSessionJob_CompleteFailure() { /* 0x1722ed0 */ }
void nn_pia_session_DestroySessionJob_SendMonitoringData() { /* 0x17238d0 */ }
void nn_pia_session_JoinSessionJob_CompleteFailure() { /* 0x1724320 */ }
void nn_pia_session_LeaveSessionJob_SendMonitoringData() { /* 0x1726a10 */ }
void nn_pia_session_LeaveSessionJob_SendMonitoringData_2() { /* 0x1726ad0 */ }
void nn_pia_session_LeaveSessionJob_SendMonitoringData_3() { /* 0x1726e50 */ }
void nn_pia_session_LeaveSessionJob_SendMonitoringData_4() { /* 0x17271b0 */ }
void nn_pia_session_RandomMatchmakeJob_CompleteFailure() { /* 0x1727bf0 */ }
void nn_pia_session_RandomMatchmakeJob_CompleteFailure_2() { /* 0x17281f0 */ }
void nn_pia_session_RandomMatchmakeJob_CompleteFailure_3() { /* 0x1728900 */ }
void nn_ssl() { /* 0x1777ed0 */ }

}  // namespace gflib3
