/* sdk.gflib3 - 37 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "gflib3_gflib3_sdk.h"

namespace gflib3 {
void nn_audio_AudioRenderSystemManager() { /* 0x9e000 */ }
void nndetailRoGetRoDataStart() { /* 0x180dd0 */ }
void nn_friends_GetProfileList() { /* 0x1d6fc0 */ }
void nn_friends_DeleteFriend() { /* 0x1d7b30 */ }
void nn_friends_SyncFriendList() { /* 0x1d7c00 */ }
void nn_friends_GetFriendRequestList() { /* 0x1d7e40 */ }
void nn_friends_SendFriendRequest() { /* 0x1d7f30 */ }
void nn_friends_SendFriendRequestWithApplicationInfo() { /* 0x1d8000 */ }
void nn_friends_SendFriendRequestWithExternalApplicationCatal() { /* 0x1d8140 */ }
void nn_friends_CancelFriendRequest() { /* 0x1d83c0 */ }
void nn_friends_AcceptFriendRequest() { /* 0x1d8490 */ }
void nn_friends_RejectFriendRequest() { /* 0x1d8560 */ }
void nn_friends_ReadFriendRequest() { /* 0x1d8630 */ }
void nn_friends_ResendFacedFriendRequest() { /* 0x1d8a70 */ }
void nn_friends_GetFriendCandidateList() { /* 0x1d8b40 */ }
void nn_friends_GetSnsAccountLinkPageUrl() { /* 0x1d8d10 */ }
void nn_friends_UnlinkSnsAccount() { /* 0x1d8dd0 */ }
void nn_friends_GetSnsAccountLinkage() { /* 0x1d8e90 */ }
void nn_friends_GetSnsAccountProfile() { /* 0x1d8f50 */ }
void nn_friends_GetSnsAccountFriendList() { /* 0x1d9020 */ }
void nn_friends_BlockUser() { /* 0x1d91e0 */ }
void nn_friends_BlockUserWithApplicationInfo() { /* 0x1d92b0 */ }
void nn_friends_UnblockUser() { /* 0x1d93c0 */ }
void nn_friends_SyncBlockedUserList() { /* 0x1d9490 */ }
void nn_friends_GetProfileExtraList() { /* 0x1d9550 */ }
void nn_friends_GetRelationship() { /* 0x1d9630 */ }
void nn_friends_SyncUserSetting() { /* 0x1d97b0 */ }
void nn_friends_GetProfileExtraFromFriendCode() { /* 0x1d9870 */ }
void nn_friends_GetExternalApplicationCatalog() { /* 0x1d9d50 */ }
void nn_friends_SendFriendRequestForApplication() { /* 0x1daad0 */ }
void nn_friends_ChangePresencePermission() { /* 0x1dc420 */ }
void nn_friends_ChangeFriendRequestReception() { /* 0x1dc500 */ }
void nn_friends_IssueFriendCode() { /* 0x1dc5f0 */ }
void nn_friends_ChangePlayLogPermission() { /* 0x1dc6d0 */ }
void nn_friends_ClearPlayLog() { /* 0x1dc7a0 */ }
void nn_friends_ChangeFriendFavoriteFlag() { /* 0x1dca30 */ }
void nnSdk() { /* 0x33d230 */ }

}  // namespace gflib3
