/* sdk.render - 1 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace render {
void Graphics_Device();  // 0x3f0ec0

}  // namespace render
