/* sdk.audio - 1 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace audio {
void AudioUsbDeviceOutput_sdk_96ac0();  // 0x96ac0

}  // namespace audio
