/* main.audio - 4 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace audio {
void AudioUsbDeviceOutput();  // 0x5650
void MovieAudioInputReadThread();  // 0x663ee0
void MovieAudioOutputHandlerThread();  // 0x664fd0
void SoundWait();  // 0x13ab400

}  // namespace audio
