/* main.save - 3 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "save_save_main.h"

namespace save {
void save_d_2() { /* 0x5e6350 */ }
void save_hashdb() { /* 0x139a010 */ }
void save_process() { /* 0x139ffc0 */ }

}  // namespace save
