/* sdk.save - 8 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "save_save_sdk.h"

namespace save {
void SaveScreenshot() { /* 0x50450 */ }
void SaveScreenshot_2() { /* 0x50630 */ }
void SaveScreenshot_3() { /* 0x50840 */ }
void SaveAndShareScreenshot() { /* 0x50b20 */ }
void SaveDataTransferManager() { /* 0x21cc90 */ }
void SaveDataExporter() { /* 0x21d4f0 */ }
void SaveDataImporter() { /* 0x21d760 */ }
void SaveDataTransferManagerVersion2() { /* 0x21d9c0 */ }

}  // namespace save
