/* main.trainer - 7 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "trainer_trainer_main.h"

namespace trainer {
void trainer_type__03d() { /* 0xcdc500 */ }
void trainer_id_hash_table() { /* 0x135ad40 */ }
void trainer_data__03d() { /* 0x14522a0 */ }
void trainer_data__03d_2() { /* 0x14524b0 */ }
void trainer_poke__03d() { /* 0x1453750 */ }
void trainer_type__03d_2() { /* 0x1453ab0 */ }
void TrainerID() { /* 0x146cca0 */ }

}  // namespace trainer
