/* main.item - 6 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace item {
void item_hash_to_index();  // 0x7c1440
void ItemDescView();  // 0xe6e710
void item_dummy();  // 0xf1d840
void item_sort_table();  // 0x14b9810
void item_dummy_2();  // 0x14bb6b0
void item_dummy_3();  // 0x14bc7a0

}  // namespace item
