cmake_minimum_required(VERSION 3.13)
project(pokemon_sword_decomp C)
set(CMAKE_C_STANDARD 11)
set(RECOMP_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../exefs)
set(RECOMP_STATIC_ONLY ON)
foreach(m rtld main sdk subsdk0 subsdk1)
  if(EXISTS ${RECOMP_SRC_DIR}/${m}/CMakeLists.txt)
    add_subdirectory(${RECOMP_SRC_DIR}/${m} recomp_${m})
  endif()
endforeach()
foreach(m rtld main sdk subsdk0 subsdk1)
  if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${m}/CMakeLists.txt)
    add_subdirectory(${m} decomp_${m})
  endif()
endforeach()
