/* main.bag - 28 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace bag {
void BagViewShop();  // 0x794690
void BagViewShop_2();  // 0x7952f0
void BagViewTop();  // 0x7980e0
void BagViewShop_3();  // 0x7a7e80
void bag_top_itemlist_00_lyt();  // 0x7a8c20
void BagViewShop_4();  // 0x7ab480
void BagViewShop_5();  // 0x7abb50
void BagStateCombine();  // 0x7ac4a0
void BagStatePossess();  // 0x7af0d0
void BagStateUsePoke();  // 0x7afc90
void BagStateEvolution();  // 0x7b0b10
void BagStateUsePlayer();  // 0x7b12f0
void BagStateItemSelect();  // 0x7b1ff0
void BagStatePokeSelect();  // 0x7b3b90
void BagStateSkillSelect();  // 0x7b5de0
void BagStateRotomCatalog();  // 0x7b6570
void BagStateChangeSeikaku();  // 0x7b7800
void BagStateSkillLearning();  // 0x7b81c0
void BagStateCharacteristic();  // 0x7b9370
void BagStateShopItemSelect();  // 0x7b9cd0
void BagViewShop_6();  // 0x7badd0
void BagViewShop_7();  // 0x1246350
void BagStateEnd();  // 0x12484f0
void BagViewFade();  // 0x1248600
void BagViewShop_8();  // 0x1249280
void BagViewIngredientsCheck();  // 0x124b240
void BagViewIngredientsEffect();  // 0x124c690
void bag_pocket();  // 0x1315590

}  // namespace bag
