/* main.main - 244 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "main_main_main_24.h"

namespace main {
void sub_17cda60() { /* 0x17cda60 */ }
void sub_17cdea0() { /* 0x17cdea0 */ }
void sub_17ce1e0() { /* 0x17ce1e0 */ }
void sub_17ce670() { /* 0x17ce670 */ }
void sub_17ce920() { /* 0x17ce920 */ }
void sub_17cee80() { /* 0x17cee80 */ }
void sub_17cf350() { /* 0x17cf350 */ }
void sub_17cf7b0() { /* 0x17cf7b0 */ }
void sub_17cfb80() { /* 0x17cfb80 */ }
void sub_17cffe0() { /* 0x17cffe0 */ }
void sub_17d03b0() { /* 0x17d03b0 */ }
void sub_17d0580() { /* 0x17d0580 */ }
void sub_17d0990() { /* 0x17d0990 */ }
void sub_17d0f70() { /* 0x17d0f70 */ }
void sub_17d1220() { /* 0x17d1220 */ }
void sub_17d14b0() { /* 0x17d14b0 */ }
void sub_17d19b0() { /* 0x17d19b0 */ }
void sub_17d19d0() { /* 0x17d19d0 */ }
void sub_17d1a00() { /* 0x17d1a00 */ }
void sub_17d1ee0() { /* 0x17d1ee0 */ }
void sub_17d2200() { /* 0x17d2200 */ }
void sub_17d2230() { /* 0x17d2230 */ }
void sub_17d24b0() { /* 0x17d24b0 */ }
void sub_17d2510() { /* 0x17d2510 */ }
void sub_17d2520() { /* 0x17d2520 */ }
void sub_17d2530() { /* 0x17d2530 */ }
void sub_17d2550() { /* 0x17d2550 */ }
void sub_17d2590() { /* 0x17d2590 */ }
void sub_17d25f0() { /* 0x17d25f0 */ }
void sub_17d2600() { /* 0x17d2600 */ }
void sub_17d2690() { /* 0x17d2690 */ }
void sub_17d2890() { /* 0x17d2890 */ }
void sub_17d28d0() { /* 0x17d28d0 */ }
void sub_17d2920() { /* 0x17d2920 */ }
void sub_17d2b10() { /* 0x17d2b10 */ }
void Gap_d() { /* 0x17d2b50 */ }
void sub_17d2de0() { /* 0x17d2de0 */ }
void sub_17d3330() { /* 0x17d3330 */ }
void Heap_is_not_set_in_the_argument_of_the_resource_destruct() { /* 0x17d3390 */ }
void sub_17d3680() { /* 0x17d3680 */ }
void sub_17d36f0() { /* 0x17d36f0 */ }
void Faild_to_initialize_primitive_Index_d() { /* 0x17d3890 */ }
void sub_17d3b30() { /* 0x17d3b30 */ }
void sub_17d3cd0() { /* 0x17d3cd0 */ }
void sub_17d3e30() { /* 0x17d3e30 */ }
void sub_17d3fc0() { /* 0x17d3fc0 */ }
void sub_17d4010() { /* 0x17d4010 */ }
void sub_17d4140() { /* 0x17d4140 */ }
void sub_17d4160() { /* 0x17d4160 */ }
void The_Texture_which_was_not_found_is_s() { /* 0x17d42c0 */ }
void sub_17d4490() { /* 0x17d4490 */ }
void sub_17d4520() { /* 0x17d4520 */ }
void Appointed_Primitive_is_not_found_from_Resident_Resource() { /* 0x17d4960 */ }
void sub_17d49e0() { /* 0x17d49e0 */ }
void sub_17d4b40() { /* 0x17d4b40 */ }
void sub_17d4b90() { /* 0x17d4b90 */ }
// sub_17d4c20: implemented in prog/matched/main/
// sub_17d4c30: implemented in prog/matched/main/
// sub_17d4c40: implemented in prog/matched/main/
// sub_17d4c50: implemented in prog/matched/main/
void sub_17d4c60() { /* 0x17d4c60 */ }
// sub_17d4c70: implemented in prog/matched/main/
// sub_17d4c80: implemented in prog/matched/main/
// sub_17d4c90: implemented in prog/matched/main/
// sub_17d4ca0: implemented in prog/matched/main/
// sub_17d4cb0: implemented in prog/matched/main/
// sub_17d4cc0: implemented in prog/matched/main/
void sub_17d4cd0() { /* 0x17d4cd0 */ }
void sub_17d4d60() { /* 0x17d4d60 */ }
// sub_17d4df0: implemented in prog/matched/main/
// sub_17d4e00: implemented in prog/matched/main/
void sub_17d4e10() { /* 0x17d4e10 */ }
void sub_17d4e30() { /* 0x17d4e30 */ }
void sub_17d4e50() { /* 0x17d4e50 */ }
// sub_17d4e60: implemented in prog/matched/main/
// sub_17d4e70: implemented in prog/matched/main/
// sub_17d4e80: implemented in prog/matched/main/
// sub_17d4e90: implemented in prog/matched/main/
// sub_17d4ea0: implemented in prog/matched/main/
// sub_17d4eb0: implemented in prog/matched/main/
void sub_17d4ec0() { /* 0x17d4ec0 */ }
void sub_17d4f10() { /* 0x17d4f10 */ }
void sub_17d4f60() { /* 0x17d4f60 */ }
void sub_17d5010() { /* 0x17d5010 */ }
void sub_17d50a0() { /* 0x17d50a0 */ }
void s_fmdb_A_format_of__u1_is_different_from__uo_of_the_part() { /* 0x17d5410 */ }
void sub_17d5660() { /* 0x17d5660 */ }
// sub_17d57a0: implemented in prog/matched/main/
void sub_17d57c0() { /* 0x17d57c0 */ }
void sub_17d59f0() { /* 0x17d59f0 */ }
void sub_17d5ad0() { /* 0x17d5ad0 */ }
// sub_17d5c10: implemented in prog/matched/main/
void sub_17d5c20() { /* 0x17d5c20 */ }
void sub_17d5e10() { /* 0x17d5e10 */ }
void sub_17d6050() { /* 0x17d6050 */ }
// sub_17d60b0: implemented in prog/matched/main/
void sub_17d60c0() { /* 0x17d60c0 */ }
void sysFrameBufferTexture() { /* 0x17d60f0 */ }
void Stripe_Memory_Allocate_Error_d() { /* 0x17d66d0 */ }
void sub_17d6960() { /* 0x17d6960 */ }
void sub_17d6a00() { /* 0x17d6a00 */ }
void Stripe_instance_is_null() { /* 0x17d6b10 */ }
void sub_17d6b80() { /* 0x17d6b80 */ }
void sub_17d6bd0() { /* 0x17d6bd0 */ }
void sub_17d6c00() { /* 0x17d6c00 */ }
void sub_17d6c50() { /* 0x17d6c50 */ }
// sub_17d6d30: implemented in prog/matched/main/
void sub_17d6d40() { /* 0x17d6d40 */ }
void sub_17d6d90() { /* 0x17d6d90 */ }
void StripeSystem_is_already_initialized() { /* 0x17d6de0 */ }
void sub_17d6f50() { /* 0x17d6f50 */ }
void There_is_no_available_Stripe_instance() { /* 0x17d6fa0 */ }
void sub_17d71d0() { /* 0x17d71d0 */ }
void sub_17d7440() { /* 0x17d7440 */ }
void sub_17d76e0() { /* 0x17d76e0 */ }
void sub_17d7710() { /* 0x17d7710 */ }
void sub_17d7740() { /* 0x17d7740 */ }
void sub_17d8150() { /* 0x17d8150 */ }
void sub_17d84a0() { /* 0x17d84a0 */ }
void sub_17d8600() { /* 0x17d8600 */ }
void sub_17d88a0() { /* 0x17d88a0 */ }
void sub_17d89f0() { /* 0x17d89f0 */ }
void sub_17d8ae0() { /* 0x17d8ae0 */ }
void sub_17d8cf0() { /* 0x17d8cf0 */ }
void sub_17d8e50() { /* 0x17d8e50 */ }
void sub_17d9240() { /* 0x17d9240 */ }
void sub_17d9370() { /* 0x17d9370 */ }
void sub_17d9870() { /* 0x17d9870 */ }
void sub_17d99e0() { /* 0x17d99e0 */ }
void sub_17d9c50() { /* 0x17d9c50 */ }
void sub_17d9cf0() { /* 0x17d9cf0 */ }
void SuperStripe_instance_is_null() { /* 0x17d9e00 */ }
void sub_17d9e70() { /* 0x17d9e70 */ }
void sub_17d9ec0() { /* 0x17d9ec0 */ }
void sub_17d9ef0() { /* 0x17d9ef0 */ }
void sub_17d9f40() { /* 0x17d9f40 */ }
void sub_17da030() { /* 0x17da030 */ }
void sub_17da080() { /* 0x17da080 */ }
void SuperStripeSystem_is_already_initialized() { /* 0x17da0d0 */ }
void sub_17da240() { /* 0x17da240 */ }
void There_is_no_available_Stripe_instance_2() { /* 0x17da290 */ }
void sub_17da4d0() { /* 0x17da4d0 */ }
void sub_17da680() { /* 0x17da680 */ }
void sub_17dc1e0() { /* 0x17dc1e0 */ }
void sub_17dc530() { /* 0x17dc530 */ }
void sub_17dca00() { /* 0x17dca00 */ }
void sub_17dccb0() { /* 0x17dccb0 */ }
void sub_17dced0() { /* 0x17dced0 */ }
void sub_17dcf00() { /* 0x17dcf00 */ }
void sub_17dcf30() { /* 0x17dcf30 */ }
void sub_17dd090() { /* 0x17dd090 */ }
void SDK_MW_Nintendo_NintendoWare_Vfx_7_3_2_Release() { /* 0x17dd310 */ }
void TempBuffer_WorkSize_d() { /* 0x17dd460 */ }
void vfx_system_deleted_the_registered_binary_resource_id_d() { /* 0x17de080 */ }
void sub_17de2c0() { /* 0x17de2c0 */ }
void The_Resource_to_be_cleared_does_not_exist_ResourceId_d() { /* 0x17de2f0 */ }
void vfx_system_deleted_the_registered_binary_resource_id_d_2() { /* 0x17de370 */ }
void There_is_no_available_Emitter_instance() { /* 0x17de470 */ }
// sub_17de500: implemented in prog/matched/main/
void sub_17de510() { /* 0x17de510 */ }
void There_is_no_available_Emitter_instance_2() { /* 0x17de540 */ }
void sub_17de780() { /* 0x17de780 */ }
void EmitterSet_has_been_already_deleted() { /* 0x17de7a0 */ }
void EmitterSet_has_been_already_deleted_2() { /* 0x17de830 */ }
void EmitterSet_Remove_Failed() { /* 0x17de990 */ }
void sub_17deb60() { /* 0x17deb60 */ }
void Invalid_EmitterSet_has_been_detected_Invalidates_handle() { /* 0x17dee90 */ }
void sub_17df0e0() { /* 0x17df0e0 */ }
void sub_17df150() { /* 0x17df150 */ }
void sub_17df200() { /* 0x17df200 */ }
void sub_17df4a0() { /* 0x17df4a0 */ }
void sub_17df650() { /* 0x17df650 */ }
void sub_17df710() { /* 0x17df710 */ }
void sub_17df770() { /* 0x17df770 */ }
// sub_17df790: implemented in prog/matched/main/
void sub_17df7a0() { /* 0x17df7a0 */ }
void sub_17df8a0() { /* 0x17df8a0 */ }
void Particle_sort_has_failed_More_buffer_size_is_needed() { /* 0x17df8f0 */ }
void sub_17dfcd0() { /* 0x17dfcd0 */ }
void sub_17dfdb0() { /* 0x17dfdb0 */ }
void sub_17dfdc0() { /* 0x17dfdc0 */ }
void sub_17dfdd0() { /* 0x17dfdd0 */ }
void sub_17dfde0() { /* 0x17dfde0 */ }
void sub_17dfdf0() { /* 0x17dfdf0 */ }
void sub_17dfe20() { /* 0x17dfe20 */ }
void sub_17dfe80() { /* 0x17dfe80 */ }
void sub_17dfea0() { /* 0x17dfea0 */ }
void sub_17e0740() { /* 0x17e0740 */ }
void sub_17e08f0() { /* 0x17e08f0 */ }
void sub_17e0cb0() { /* 0x17e0cb0 */ }
void sub_17e13b0() { /* 0x17e13b0 */ }
void sub_17e15f0() { /* 0x17e15f0 */ }
void sub_17e1720() { /* 0x17e1720 */ }
void sub_17e1920() { /* 0x17e1920 */ }
void sub_17e1db0() { /* 0x17e1db0 */ }
void sub_17e24b0() { /* 0x17e24b0 */ }
void sub_17e26f0() { /* 0x17e26f0 */ }
void sub_17e2820() { /* 0x17e2820 */ }
void sub_17e2a20() { /* 0x17e2a20 */ }
void sub_17e2eb0() { /* 0x17e2eb0 */ }
void sub_17e3660() { /* 0x17e3660 */ }
void sub_17e3890() { /* 0x17e3890 */ }
void sub_17e39e0() { /* 0x17e39e0 */ }
void sub_17e3c20() { /* 0x17e3c20 */ }
void sub_17e40e0() { /* 0x17e40e0 */ }
void sub_17e4890() { /* 0x17e4890 */ }
void sub_17e4ac0() { /* 0x17e4ac0 */ }
void sub_17e4c10() { /* 0x17e4c10 */ }
void sub_17e4e50() { /* 0x17e4e50 */ }
void sub_17e5310() { /* 0x17e5310 */ }
// sub_17e5360: implemented in prog/matched/main/
void sub_17e5370() { /* 0x17e5370 */ }
// sub_17e53a0: implemented in prog/matched/main/
void sub_17e53b0() { /* 0x17e53b0 */ }
void sub_17e5ac0() { /* 0x17e5ac0 */ }
void sub_17e5c40() { /* 0x17e5c40 */ }
void sub_17e5ca0() { /* 0x17e5ca0 */ }
void sub_17e5cf0() { /* 0x17e5cf0 */ }
// sub_17e5d50: implemented in prog/matched/main/
void ConnectedStripe_Memory_Allocate_Error_d() { /* 0x17e5d70 */ }
void sub_17e5e70() { /* 0x17e5e70 */ }
void sub_17e5ec0() { /* 0x17e5ec0 */ }
void sub_17e7e40() { /* 0x17e7e40 */ }
void sub_17e8140() { /* 0x17e8140 */ }
// sub_17e8260: implemented in prog/matched/main/
void sub_17e8280() { /* 0x17e8280 */ }
void sub_17e82f0() { /* 0x17e82f0 */ }
void unnamed_91() { /* 0x17e83a0 */ }
// sub_17e84c0: implemented in prog/matched/main/
void sub_17e84d0() { /* 0x17e84d0 */ }
void Texture_Sampler_Table_Already_Created() { /* 0x17e8530 */ }
void sub_17e8920() { /* 0x17e8920 */ }
void sub_17e89c0() { /* 0x17e89c0 */ }
void sub_17e89f0() { /* 0x17e89f0 */ }
void sub_17e8a70() { /* 0x17e8a70 */ }
void sub_17e8b00() { /* 0x17e8b00 */ }
void sub_17e8b60() { /* 0x17e8b60 */ }
void sub_17e8c90() { /* 0x17e8c90 */ }
// sub_17e8d00: implemented in prog/matched/main/
void sub_17e8d20() { /* 0x17e8d20 */ }
void sub_17e8e80() { /* 0x17e8e80 */ }
// sub_17e8ec0: implemented in prog/matched/main/
// sub_17e8ed0: implemented in prog/matched/main/
void sub_17e8ee0() { /* 0x17e8ee0 */ }

}  // namespace main
