/* main.save - 4 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace save {
void save_d();  // 0x5e4620
void save_d_2();  // 0x5e6350
void save_hashdb();  // 0x139a010
void save_process();  // 0x139ffc0

}  // namespace save
