/* subsdk1.tailthunk - 58 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "tailthunk_subsdk1_subsdk1.h"

namespace subsdk1 {
// sub_1250: implemented in prog/matched/subsdk1/
// sub_12b0: implemented in prog/matched/subsdk1/
// sub_1380: implemented in prog/matched/subsdk1/
// sub_3930: implemented in prog/matched/subsdk1/
// sub_e0f0: implemented in prog/matched/subsdk1/
// sub_13d30: implemented in prog/matched/subsdk1/
// sub_343d0: implemented in prog/matched/subsdk1/
// sub_34520: implemented in prog/matched/subsdk1/
// sub_1c85b0: implemented in prog/matched/subsdk1/
// sub_1ca060_subsdk1_1ca060: implemented in prog/matched/subsdk1/
// sub_1ca070: implemented in prog/matched/subsdk1/
// sub_1ca310: implemented in prog/matched/subsdk1/
// sub_1ca320: implemented in prog/matched/subsdk1/
// sub_21afe0: implemented in prog/matched/subsdk1/
// sub_223640: implemented in prog/matched/subsdk1/
// sub_29d210: implemented in prog/matched/subsdk1/
// sub_29d3c0: implemented in prog/matched/subsdk1/
// sub_29d3d0: implemented in prog/matched/subsdk1/
// sub_29d5d0: implemented in prog/matched/subsdk1/
// sub_29d5e0_subsdk1_29d5e0: implemented in prog/matched/subsdk1/
// sub_2a5030: implemented in prog/matched/subsdk1/
// sub_2ac7f0: implemented in prog/matched/subsdk1/
// sub_2e1c50: implemented in prog/matched/subsdk1/
// sub_32b070: implemented in prog/matched/subsdk1/
// sub_32b1d0: implemented in prog/matched/subsdk1/
// sub_32b1e0: implemented in prog/matched/subsdk1/
// sub_32b1f0: implemented in prog/matched/subsdk1/
// sub_32b2c0: implemented in prog/matched/subsdk1/
// sub_32b830: implemented in prog/matched/subsdk1/
// sub_32b880: implemented in prog/matched/subsdk1/
// sub_32c260: implemented in prog/matched/subsdk1/
// sub_32c270: implemented in prog/matched/subsdk1/
// sub_32c280: implemented in prog/matched/subsdk1/
// sub_32ca40: implemented in prog/matched/subsdk1/
// sub_32cb10: implemented in prog/matched/subsdk1/
// sub_32cbe0: implemented in prog/matched/subsdk1/
// sub_32cbf0: implemented in prog/matched/subsdk1/
// sub_32cef0: implemented in prog/matched/subsdk1/
// sub_32d0d0: implemented in prog/matched/subsdk1/
// sub_32d8c0: implemented in prog/matched/subsdk1/
// sub_32da00: implemented in prog/matched/subsdk1/
// sub_37d900: implemented in prog/matched/subsdk1/
// sub_4bfdf0: implemented in prog/matched/subsdk1/
// sub_4bfe00: implemented in prog/matched/subsdk1/
// sub_4c0cb0: implemented in prog/matched/subsdk1/
// sub_4c0cc0: implemented in prog/matched/subsdk1/
// sub_4c0cd0: implemented in prog/matched/subsdk1/
// sub_4c0ce0: implemented in prog/matched/subsdk1/
// sub_4c0cf0: implemented in prog/matched/subsdk1/
// sub_4ccda0: implemented in prog/matched/subsdk1/
// sub_4cdee0: implemented in prog/matched/subsdk1/
// sub_4cdf10: implemented in prog/matched/subsdk1/
// sub_4cdf50: implemented in prog/matched/subsdk1/
// sub_4ce0c0: implemented in prog/matched/subsdk1/
// sub_4ce0f0: implemented in prog/matched/subsdk1/
// sub_4ce140: implemented in prog/matched/subsdk1/
// sub_4ce180: implemented in prog/matched/subsdk1/
// sub_4ce1c0_subsdk1_4ce1c0: implemented in prog/matched/subsdk1/

}  // namespace subsdk1
