/* subsdk0.tailthunk - 28 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "tailthunk_subsdk0_subsdk0.h"

namespace subsdk0 {
// sub_54010: implemented in prog/matched/subsdk0/
// sub_258660_subsdk0_258660: implemented in prog/matched/subsdk0/
// sub_297280: implemented in prog/matched/subsdk0/
// sub_297290: implemented in prog/matched/subsdk0/
// sub_29af10: implemented in prog/matched/subsdk0/
// sub_2a6fa0: implemented in prog/matched/subsdk0/
// sub_2a6fb0: implemented in prog/matched/subsdk0/
// sub_2a6fc0_subsdk0_2a6fc0: implemented in prog/matched/subsdk0/
// sub_2a6fd0: implemented in prog/matched/subsdk0/
// sub_2a6fe0: implemented in prog/matched/subsdk0/
// sub_2a6ff0: implemented in prog/matched/subsdk0/
// sub_2a7000: implemented in prog/matched/subsdk0/
// sub_2a7010: implemented in prog/matched/subsdk0/
// sub_2a7020: implemented in prog/matched/subsdk0/
// sub_2a7030: implemented in prog/matched/subsdk0/
// sub_2a7040: implemented in prog/matched/subsdk0/
// sub_2a7050: implemented in prog/matched/subsdk0/
// sub_2baa70: implemented in prog/matched/subsdk0/
// sub_31cc70: implemented in prog/matched/subsdk0/
// sub_338580: implemented in prog/matched/subsdk0/
// sub_338a80: implemented in prog/matched/subsdk0/
// sub_348a80: implemented in prog/matched/subsdk0/
// sub_348a90_subsdk0_348a90: implemented in prog/matched/subsdk0/
// sub_348aa0: implemented in prog/matched/subsdk0/
// sub_348ad0: implemented in prog/matched/subsdk0/
// sub_348ae0_subsdk0_348ae0: implemented in prog/matched/subsdk0/
// sub_348af0: implemented in prog/matched/subsdk0/
// sub_35bbc0: implemented in prog/matched/subsdk0/

}  // namespace subsdk0
