/* sdk.tailthunk - 71 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "tailthunk_sdk_sdk.h"

namespace sdk {
// sub_1ab80: implemented in prog/matched/sdk/
// sub_2c590: implemented in prog/matched/sdk/
// sub_14d670: implemented in prog/matched/sdk/
// sub_374420: implemented in prog/matched/sdk/
// sub_374430_sdk_374430: implemented in prog/matched/sdk/
// sub_374940: implemented in prog/matched/sdk/
// sub_374950: implemented in prog/matched/sdk/
// sub_3750f0: implemented in prog/matched/sdk/
// sub_375100: implemented in prog/matched/sdk/
// sub_38c620: implemented in prog/matched/sdk/
// sub_38c940: implemented in prog/matched/sdk/
// sub_39ada0: implemented in prog/matched/sdk/
// sub_39aea0: implemented in prog/matched/sdk/
// sub_39aeb0: implemented in prog/matched/sdk/
// sub_39b070: implemented in prog/matched/sdk/
// sub_39b1b0: implemented in prog/matched/sdk/
// sub_39b1c0: implemented in prog/matched/sdk/
// sub_3bc4a0: implemented in prog/matched/sdk/
// sub_3bc4b0: implemented in prog/matched/sdk/
// sub_3bc4c0: implemented in prog/matched/sdk/
// sub_3bc4d0: implemented in prog/matched/sdk/
// sub_3bc520: implemented in prog/matched/sdk/
// sub_3bc590: implemented in prog/matched/sdk/
// sub_3bc670: implemented in prog/matched/sdk/
// sub_3bc690: implemented in prog/matched/sdk/
// sub_3bc6a0: implemented in prog/matched/sdk/
// sub_3bc6b0: implemented in prog/matched/sdk/
// sub_3bc6c0: implemented in prog/matched/sdk/
// sub_3bc6d0: implemented in prog/matched/sdk/
// sub_3bc6e0: implemented in prog/matched/sdk/
// sub_3c4780: implemented in prog/matched/sdk/
// sub_3c5170: implemented in prog/matched/sdk/
// sub_3f18d0: implemented in prog/matched/sdk/
// sub_40b570_sdk_40b570: implemented in prog/matched/sdk/
// sub_40bb50: implemented in prog/matched/sdk/
// sub_40bb60: implemented in prog/matched/sdk/
// sub_40bb70: implemented in prog/matched/sdk/
// sub_40bb80: implemented in prog/matched/sdk/
// sub_40da00: implemented in prog/matched/sdk/
// sub_414bf0: implemented in prog/matched/sdk/
// sub_4167c0: implemented in prog/matched/sdk/
// sub_4167d0: implemented in prog/matched/sdk/
// sub_416b70: implemented in prog/matched/sdk/
// sub_431a20: implemented in prog/matched/sdk/
// sub_4520c8: implemented in prog/matched/sdk/
// sub_45f308: implemented in prog/matched/sdk/
// sub_45f7d0: implemented in prog/matched/sdk/
// sub_45fc98: implemented in prog/matched/sdk/
// sub_460160: implemented in prog/matched/sdk/
// sub_460628: implemented in prog/matched/sdk/
// sub_460af0: implemented in prog/matched/sdk/
// sub_460fb8: implemented in prog/matched/sdk/
// sub_461460: implemented in prog/matched/sdk/
// sub_461908: implemented in prog/matched/sdk/
// sub_463040: implemented in prog/matched/sdk/
// sub_463560: implemented in prog/matched/sdk/
// sub_463a80: implemented in prog/matched/sdk/
// sub_463fa0: implemented in prog/matched/sdk/
// sub_4644c0: implemented in prog/matched/sdk/
// sub_4649e0: implemented in prog/matched/sdk/
// sub_464f00: implemented in prog/matched/sdk/
// sub_465400: implemented in prog/matched/sdk/
// sub_465900: implemented in prog/matched/sdk/
// sub_49e7c0: implemented in prog/matched/sdk/
// sub_49e7f8: implemented in prog/matched/sdk/
// sub_49e9c0: implemented in prog/matched/sdk/
// sub_49ea18: implemented in prog/matched/sdk/
// sub_49ea90: implemented in prog/matched/sdk/
// sub_4b7568: implemented in prog/matched/sdk/
// sub_4ff150: implemented in prog/matched/sdk/
// sub_501af0: implemented in prog/matched/sdk/

}  // namespace sdk
