/* sdk.tailthunk - 71 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace sdk {
void sub_1ab80();  // 0x1ab80
void sub_2c590();  // 0x2c590
void sub_14d670();  // 0x14d670
void sub_374420();  // 0x374420
void sub_374430_sdk_374430();  // 0x374430
void sub_374940();  // 0x374940
void sub_374950();  // 0x374950
void sub_3750f0();  // 0x3750f0
void sub_375100();  // 0x375100
void sub_38c620();  // 0x38c620
void sub_38c940();  // 0x38c940
void sub_39ada0();  // 0x39ada0
void sub_39aea0();  // 0x39aea0
void sub_39aeb0();  // 0x39aeb0
void sub_39b070();  // 0x39b070
void sub_39b1b0();  // 0x39b1b0
void sub_39b1c0();  // 0x39b1c0
void sub_3bc4a0();  // 0x3bc4a0
void sub_3bc4b0();  // 0x3bc4b0
void sub_3bc4c0();  // 0x3bc4c0
void sub_3bc4d0();  // 0x3bc4d0
void sub_3bc520();  // 0x3bc520
void sub_3bc590();  // 0x3bc590
void sub_3bc670();  // 0x3bc670
void sub_3bc690();  // 0x3bc690
void sub_3bc6a0();  // 0x3bc6a0
void sub_3bc6b0();  // 0x3bc6b0
void sub_3bc6c0();  // 0x3bc6c0
void sub_3bc6d0();  // 0x3bc6d0
void sub_3bc6e0();  // 0x3bc6e0
void sub_3c4780();  // 0x3c4780
void sub_3c5170();  // 0x3c5170
void sub_3f18d0();  // 0x3f18d0
void sub_40b570_sdk_40b570();  // 0x40b570
void sub_40bb50();  // 0x40bb50
void sub_40bb60();  // 0x40bb60
void sub_40bb70();  // 0x40bb70
void sub_40bb80();  // 0x40bb80
void sub_40da00();  // 0x40da00
void sub_414bf0();  // 0x414bf0
void sub_4167c0();  // 0x4167c0
void sub_4167d0();  // 0x4167d0
void sub_416b70();  // 0x416b70
void sub_431a20();  // 0x431a20
void sub_4520c8();  // 0x4520c8
void sub_45f308();  // 0x45f308
void sub_45f7d0();  // 0x45f7d0
void sub_45fc98();  // 0x45fc98
void sub_460160();  // 0x460160
void sub_460628();  // 0x460628
void sub_460af0();  // 0x460af0
void sub_460fb8();  // 0x460fb8
void sub_461460();  // 0x461460
void sub_461908();  // 0x461908
void sub_463040();  // 0x463040
void sub_463560();  // 0x463560
void sub_463a80();  // 0x463a80
void sub_463fa0();  // 0x463fa0
void sub_4644c0();  // 0x4644c0
void sub_4649e0();  // 0x4649e0
void sub_464f00();  // 0x464f00
void sub_465400();  // 0x465400
void sub_465900();  // 0x465900
void sub_49e7c0();  // 0x49e7c0
void sub_49e7f8();  // 0x49e7f8
void sub_49e9c0();  // 0x49e9c0
void sub_49ea18();  // 0x49ea18
void sub_49ea90();  // 0x49ea90
void sub_4b7568();  // 0x4b7568
void sub_4ff150();  // 0x4ff150
void sub_501af0();  // 0x501af0

}  // namespace sdk
