/* subsdk1.tailthunk - 58 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace subsdk1 {
void sub_1250();  // 0x1250
void sub_12b0();  // 0x12b0
void sub_1380();  // 0x1380
void sub_3930();  // 0x3930
void sub_e0f0();  // 0xe0f0
void sub_13d30();  // 0x13d30
void sub_343d0();  // 0x343d0
void sub_34520();  // 0x34520
void sub_1c85b0();  // 0x1c85b0
void sub_1ca060_subsdk1_1ca060();  // 0x1ca060
void sub_1ca070();  // 0x1ca070
void sub_1ca310();  // 0x1ca310
void sub_1ca320();  // 0x1ca320
void sub_21afe0();  // 0x21afe0
void sub_223640();  // 0x223640
void sub_29d210();  // 0x29d210
void sub_29d3c0();  // 0x29d3c0
void sub_29d3d0();  // 0x29d3d0
void sub_29d5d0();  // 0x29d5d0
void sub_29d5e0_subsdk1_29d5e0();  // 0x29d5e0
void sub_2a5030();  // 0x2a5030
void sub_2ac7f0();  // 0x2ac7f0
void sub_2e1c50();  // 0x2e1c50
void sub_32b070();  // 0x32b070
void sub_32b1d0();  // 0x32b1d0
void sub_32b1e0();  // 0x32b1e0
void sub_32b1f0();  // 0x32b1f0
void sub_32b2c0();  // 0x32b2c0
void sub_32b830();  // 0x32b830
void sub_32b880();  // 0x32b880
void sub_32c260();  // 0x32c260
void sub_32c270();  // 0x32c270
void sub_32c280();  // 0x32c280
void sub_32ca40();  // 0x32ca40
void sub_32cb10();  // 0x32cb10
void sub_32cbe0();  // 0x32cbe0
void sub_32cbf0();  // 0x32cbf0
void sub_32cef0();  // 0x32cef0
void sub_32d0d0();  // 0x32d0d0
void sub_32d8c0();  // 0x32d8c0
void sub_32da00();  // 0x32da00
void sub_37d900();  // 0x37d900
void sub_4bfdf0();  // 0x4bfdf0
void sub_4bfe00();  // 0x4bfe00
void sub_4c0cb0();  // 0x4c0cb0
void sub_4c0cc0();  // 0x4c0cc0
void sub_4c0cd0();  // 0x4c0cd0
void sub_4c0ce0();  // 0x4c0ce0
void sub_4c0cf0();  // 0x4c0cf0
void sub_4ccda0();  // 0x4ccda0
void sub_4cdee0();  // 0x4cdee0
void sub_4cdf10();  // 0x4cdf10
void sub_4cdf50();  // 0x4cdf50
void sub_4ce0c0();  // 0x4ce0c0
void sub_4ce0f0();  // 0x4ce0f0
void sub_4ce140();  // 0x4ce140
void sub_4ce180();  // 0x4ce180
void sub_4ce1c0_subsdk1_4ce1c0();  // 0x4ce1c0

}  // namespace subsdk1
