/* subsdk0.tailthunk - 28 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace subsdk0 {
void sub_54010();  // 0x54010
void sub_258660_subsdk0_258660();  // 0x258660
void sub_297280();  // 0x297280
void sub_297290();  // 0x297290
void sub_29af10();  // 0x29af10
void sub_2a6fa0();  // 0x2a6fa0
void sub_2a6fb0();  // 0x2a6fb0
void sub_2a6fc0_subsdk0_2a6fc0();  // 0x2a6fc0
void sub_2a6fd0();  // 0x2a6fd0
void sub_2a6fe0();  // 0x2a6fe0
void sub_2a6ff0();  // 0x2a6ff0
void sub_2a7000();  // 0x2a7000
void sub_2a7010();  // 0x2a7010
void sub_2a7020();  // 0x2a7020
void sub_2a7030();  // 0x2a7030
void sub_2a7040();  // 0x2a7040
void sub_2a7050();  // 0x2a7050
void sub_2baa70();  // 0x2baa70
void sub_31cc70();  // 0x31cc70
void sub_338580();  // 0x338580
void sub_338a80();  // 0x338a80
void sub_348a80();  // 0x348a80
void sub_348a90_subsdk0_348a90();  // 0x348a90
void sub_348aa0();  // 0x348aa0
void sub_348ad0();  // 0x348ad0
void sub_348ae0_subsdk0_348ae0();  // 0x348ae0
void sub_348af0();  // 0x348af0
void sub_35bbc0();  // 0x35bbc0

}  // namespace subsdk0
