/* sdk.net - 3 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace net {
void nn_friends_SendFriendRequestWithNintendoNetworkIdInfo();  // 0x1d8280
void nn_friends_GetNintendoNetworkIdInfo();  // 0x1d8c20
void nn_friends_ChangeFriendOnlineNotificationFlag();  // 0x1dcb10

}  // namespace net
