/* main.taildest - 3 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace gflib3 {
void gflnet3_message_lite_5();  // 0x70b190
void gflnet3_descriptor_17();  // 0x743640
void nn_ssl();  // 0x1777ed0

}  // namespace gflib3
