/* main.taildest - 1 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace save {
void save_d();  // 0x5e4620

}  // namespace save
