/* subsdk0.taildest - 28 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace subsdk0 {
void sub_54020();  // 0x54020
void libnvmm_camera();  // 0x258680
void sub_273a10();  // 0x273a10
void sub_273c50();  // 0x273c50
void sub_273e00();  // 0x273e00
void BlockAACEnc();  // 0x29e6e0
void BlockSuperJpgDec();  // 0x29e940
void BlockJpgEnc();  // 0x29f4f0
void BlockMP3Dec_2();  // 0x29f7f0
void BlockAACDec();  // 0x29f8e0
void BlockWMADec();  // 0x29fa10
void BlockH264Dec();  // 0x29fef0
void OMX_Nvidia_h264_decode_low_latency();  // 0x29fff0
void BlockH264Dec_2();  // 0x2a0040
void BlockVc1Dec();  // 0x2a0140
void BlockMpeg2Dec();  // 0x2a04f0
void BlockMJpgDec();  // 0x2a05f0
void sub_2baa90();  // 0x2baa90
void sub_31abc0_subsdk0_31abc0();  // 0x31abc0
void sub_338590();  // 0x338590
void sub_338a90_subsdk0_338a90();  // 0x338a90
void sub_353db0();  // 0x353db0
void sub_3554b0();  // 0x3554b0
void sub_355580();  // 0x355580
void sub_355620();  // 0x355620
void sub_3557e0_subsdk0_3557e0();  // 0x3557e0
void sub_356390();  // 0x356390
void sub_356ef0();  // 0x356ef0

}  // namespace subsdk0
