/* subsdk1.taildest - 30 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace subsdk1 {
void sub_2b0_subsdk1_2b0();  // 0x2b0
void sub_2c0_subsdk1_2c0();  // 0x2c0
void sub_2d0_subsdk1_2d0();  // 0x2d0
void sub_9d0();  // 0x9d0
void sub_f10_subsdk1_f10();  // 0xf10
void sub_1100_subsdk1_1100();  // 0x1100
void sub_2f10();  // 0x2f10
void sub_df80_subsdk1_df80();  // 0xdf80
void sub_dfa0();  // 0xdfa0
void sub_e100_subsdk1_e100();  // 0xe100
void sub_34d70();  // 0x34d70
void sub_392c0();  // 0x392c0
void sub_39400();  // 0x39400
void sub_1620d0();  // 0x1620d0
void sub_1bb950();  // 0x1bb950
void sub_1c61e0_subsdk1_1c61e0();  // 0x1c61e0
void sub_1c6b90();  // 0x1c6b90
void sub_1c80f0();  // 0x1c80f0
void sub_264720();  // 0x264720
void sub_29d280_subsdk1_29d280();  // 0x29d280
void mem_Alloc();  // 0x2a4c10
void sub_3136f0();  // 0x3136f0
void layout_qualifier_s_incompatible_with_s();  // 0x327c90
void ARB_enhanced_layouts_2();  // 0x32a4b0
void component_4();  // 0x32a7a0
void layout_qualifier_s_incompatible_with_s_3();  // 0x32aba0
void NV_stereo_secondary_view_offset_d();  // 0x32ace0
void unsupported_node_type_in_DupNode();  // 0x360dc0
void sub_3774b0();  // 0x3774b0
void sub_4c4ab0();  // 0x4c4ab0

}  // namespace subsdk1
