/* subsdk0.subsdk0 - 1778 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "subsdk0_subsdk0_subsdk0_2.h"

namespace subsdk0 {
void sub_255570() { /* 0x255570 */ }
void sub_2555e0() { /* 0x2555e0 */ }
void sub_255630() { /* 0x255630 */ }
void sub_2556d0_subsdk0_2556d0() { /* 0x2556d0 */ }
void sub_255830_subsdk0_255830() { /* 0x255830 */ }
void sub_255890() { /* 0x255890 */ }
void sub_2558a0_subsdk0_2558a0() { /* 0x2558a0 */ }
void sub_2558d0_subsdk0_2558d0() { /* 0x2558d0 */ }
void sub_255900() { /* 0x255900 */ }
void sub_255980_subsdk0_255980() { /* 0x255980 */ }
void sub_2559c0() { /* 0x2559c0 */ }
void sub_2559e0() { /* 0x2559e0 */ }
void sub_255a30() { /* 0x255a30 */ }
void sub_255a70() { /* 0x255a70 */ }
void sub_255ad0() { /* 0x255ad0 */ }
void WebmElement() { /* 0x255b40 */ }
void sub_255c80() { /* 0x255c80 */ }
void sub_255cb0() { /* 0x255cb0 */ }
void sub_255cc0_subsdk0_255cc0() { /* 0x255cc0 */ }
void sub_255df0() { /* 0x255df0 */ }
void sub_255e50_subsdk0_255e50() { /* 0x255e50 */ }
void sub_255e90() { /* 0x255e90 */ }
void sub_255f90() { /* 0x255f90 */ }
void sub_256360() { /* 0x256360 */ }
void sub_2565a0() { /* 0x2565a0 */ }
void android() { /* 0x256b50 */ }
void A_VORBIS() { /* 0x256ee0 */ }
void sub_2573d0() { /* 0x2573d0 */ }
void sub_257870() { /* 0x257870 */ }
void sub_257bf0_subsdk0_257bf0() { /* 0x257bf0 */ }
void sub_257c00() { /* 0x257c00 */ }
void sub_257c10() { /* 0x257c10 */ }
void sub_257c40() { /* 0x257c40 */ }
void sub_257c80() { /* 0x257c80 */ }
void sub_257c90() { /* 0x257c90 */ }
void sub_257cc0() { /* 0x257cc0 */ }
// sub_257d00: implemented in prog/matched/subsdk0/
void sub_257d10() { /* 0x257d10 */ }
void sub_257d20() { /* 0x257d20 */ }
void sub_257df0() { /* 0x257df0 */ }
void sub_257ec0() { /* 0x257ec0 */ }
void sub_257f80() { /* 0x257f80 */ }
void sub_257fe0() { /* 0x257fe0 */ }
void sub_258030_subsdk0_258030() { /* 0x258030 */ }
void sub_2580a0() { /* 0x2580a0 */ }
void sub_258160() { /* 0x258160 */ }
void sub_2581e0() { /* 0x2581e0 */ }
void sub_258240() { /* 0x258240 */ }
// sub_258260: implemented in prog/matched/subsdk0/
// sub_258270_subsdk0_258270: implemented in prog/matched/subsdk0/
// sub_258280: implemented in prog/matched/subsdk0/
// sub_258290: implemented in prog/matched/subsdk0/
// sub_2582a0: implemented in prog/matched/subsdk0/
// sub_2582b0: implemented in prog/matched/subsdk0/
// sub_2582c0: implemented in prog/matched/subsdk0/
// sub_2582d0: implemented in prog/matched/subsdk0/
// sub_2582e0: implemented in prog/matched/subsdk0/
// sub_2582f0: implemented in prog/matched/subsdk0/
// sub_258300: implemented in prog/matched/subsdk0/
// sub_258310: implemented in prog/matched/subsdk0/
// sub_258320: implemented in prog/matched/subsdk0/
// sub_258330: implemented in prog/matched/subsdk0/
// sub_258340: implemented in prog/matched/subsdk0/
// sub_258350_subsdk0_258350: implemented in prog/matched/subsdk0/
// sub_258360: implemented in prog/matched/subsdk0/
// sub_258370: implemented in prog/matched/subsdk0/
// sub_258380: implemented in prog/matched/subsdk0/
void sub_258390() { /* 0x258390 */ }
void sub_258500() { /* 0x258500 */ }
void sub_2585b0_subsdk0_2585b0() { /* 0x2585b0 */ }
// sub_258660_subsdk0_258660: implemented in prog/matched/subsdk0/
void sub_258670() { /* 0x258670 */ }
void libnvmm_camera() { /* 0x258680 */ }
void sub_258b20_subsdk0_258b20() { /* 0x258b20 */ }
void sub_258b90() { /* 0x258b90 */ }
void sub_258bf0() { /* 0x258bf0 */ }
void sub_258cb0() { /* 0x258cb0 */ }
void sub_258d80() { /* 0x258d80 */ }
void sub_258da0() { /* 0x258da0 */ }
void sub_258e10() { /* 0x258e10 */ }
void sub_258e90() { /* 0x258e90 */ }
void sub_258f00() { /* 0x258f00 */ }
// sub_2594b0_subsdk0_2594b0: implemented in prog/matched/subsdk0/
void sub_2594c0() { /* 0x2594c0 */ }
void sub_2596c0() { /* 0x2596c0 */ }
void sub_259700() { /* 0x259700 */ }
void sub_259940() { /* 0x259940 */ }
void sub_259e20() { /* 0x259e20 */ }
void sub_259e30() { /* 0x259e30 */ }
void sub_259f60() { /* 0x259f60 */ }
void sub_259fd0() { /* 0x259fd0 */ }
void sub_25a070() { /* 0x25a070 */ }
void sub_25a100() { /* 0x25a100 */ }
void sub_25a120() { /* 0x25a120 */ }
void sub_25a150_subsdk0_25a150() { /* 0x25a150 */ }
void sub_25a180() { /* 0x25a180 */ }
void sub_25a2a0() { /* 0x25a2a0 */ }
void sub_25a2c0() { /* 0x25a2c0 */ }
void sub_25a2d0() { /* 0x25a2d0 */ }
void sub_25a340() { /* 0x25a340 */ }
// sub_25a350: implemented in prog/matched/subsdk0/
void sub_25a360() { /* 0x25a360 */ }
void sub_25a380() { /* 0x25a380 */ }
// sub_25a3b0: implemented in prog/matched/subsdk0/
void sub_25a3d0() { /* 0x25a3d0 */ }
void sub_25a420() { /* 0x25a420 */ }
void sub_25a440() { /* 0x25a440 */ }
// sub_25a500: implemented in prog/matched/subsdk0/
// sub_25a510: implemented in prog/matched/subsdk0/
void sub_25a520() { /* 0x25a520 */ }
void sub_25a530() { /* 0x25a530 */ }
void FileSize_f() { /* 0x25a650 */ }
// sub_25a970_subsdk0_25a970: implemented in prog/matched/subsdk0/
void sub_25a980_subsdk0_25a980() { /* 0x25a980 */ }
void sub_25ab40() { /* 0x25ab40 */ }
void sub_25ab50() { /* 0x25ab50 */ }
void sub_25ac10() { /* 0x25ac10 */ }
void sub_25af50_subsdk0_25af50() { /* 0x25af50 */ }
void sub_25b200() { /* 0x25b200 */ }
void sub_25b470() { /* 0x25b470 */ }
// sub_25b4b0: implemented in prog/matched/subsdk0/
// sub_25b4c0: implemented in prog/matched/subsdk0/
// sub_25b4d0: implemented in prog/matched/subsdk0/
void sub_25b4e0() { /* 0x25b4e0 */ }
void sub_25bcd0() { /* 0x25bcd0 */ }
void sub_25bd60() { /* 0x25bd60 */ }
void sub_25bd90() { /* 0x25bd90 */ }
void sub_25bda0() { /* 0x25bda0 */ }
void sub_25bf20() { /* 0x25bf20 */ }
void sub_25bf40() { /* 0x25bf40 */ }
// sub_25c3b0: implemented in prog/matched/subsdk0/
void sub_25c3c0() { /* 0x25c3c0 */ }
void sub_25c4c0() { /* 0x25c4c0 */ }
void sub_25c530() { /* 0x25c530 */ }
void sub_25c7e0() { /* 0x25c7e0 */ }
void sub_25c910() { /* 0x25c910 */ }
void sub_25c970() { /* 0x25c970 */ }
void sub_25c9b0() { /* 0x25c9b0 */ }
void sub_25c9e0() { /* 0x25c9e0 */ }
void sub_25d0a0_subsdk0_25d0a0() { /* 0x25d0a0 */ }
void sub_25d280() { /* 0x25d280 */ }
void sub_25d300() { /* 0x25d300 */ }
void sub_25d400() { /* 0x25d400 */ }
void sub_25d4d0() { /* 0x25d4d0 */ }
void sub_25d510() { /* 0x25d510 */ }
// sub_25d520: implemented in prog/matched/subsdk0/
void sub_25d530() { /* 0x25d530 */ }
void sub_25d620() { /* 0x25d620 */ }
void sub_25d660() { /* 0x25d660 */ }
void sub_25d690() { /* 0x25d690 */ }
void sub_25d6b0() { /* 0x25d6b0 */ }
void sub_25d6f0() { /* 0x25d6f0 */ }
void sub_25d730_subsdk0_25d730() { /* 0x25d730 */ }
// sub_25d750: implemented in prog/matched/subsdk0/
// sub_25d760_subsdk0_25d760: implemented in prog/matched/subsdk0/
void sub_25d770() { /* 0x25d770 */ }
// sub_25d7d0_subsdk0_25d7d0: implemented in prog/matched/subsdk0/
void sub_25d7e0() { /* 0x25d7e0 */ }
// sub_25d7f0: implemented in prog/matched/subsdk0/
void x_ms_wvx() { /* 0x25d800 */ }
void sub_25d9d0() { /* 0x25d9d0 */ }
void sub_25da10() { /* 0x25da10 */ }
// sub_25db10: implemented in prog/matched/subsdk0/
void sub_25db20() { /* 0x25db20 */ }
// sub_25df20: implemented in prog/matched/subsdk0/
void sub_25df30() { /* 0x25df30 */ }
// sub_25df50: implemented in prog/matched/subsdk0/
void x_msvideo() { /* 0x25df60 */ }
void sub_25e150() { /* 0x25e150 */ }
// sub_25e250_subsdk0_25e250: implemented in prog/matched/subsdk0/
void sub_25e260() { /* 0x25e260 */ }
void sub_25e3e0() { /* 0x25e3e0 */ }
// sub_25e3f0_subsdk0_25e3f0: implemented in prog/matched/subsdk0/
void sub_25e400() { /* 0x25e400 */ }
void sub_25e600_subsdk0_25e600() { /* 0x25e600 */ }
void sub_25e670_subsdk0_25e670() { /* 0x25e670 */ }
void sub_25e870_subsdk0_25e870() { /* 0x25e870 */ }
void sub_25e890() { /* 0x25e890 */ }
// sub_25f080: implemented in prog/matched/subsdk0/
// sub_25f090_subsdk0_25f090: implemented in prog/matched/subsdk0/
// sub_25f0a0: implemented in prog/matched/subsdk0/
// sub_25f0b0_subsdk0_25f0b0: implemented in prog/matched/subsdk0/
void sub_25f0c0() { /* 0x25f0c0 */ }
void sub_25f290() { /* 0x25f290 */ }
void sub_25f2b0() { /* 0x25f2b0 */ }
void sub_25f4c0() { /* 0x25f4c0 */ }
void sub_25f6f0_subsdk0_25f6f0() { /* 0x25f6f0 */ }
void sub_25f760() { /* 0x25f760 */ }
void sub_25f7b0() { /* 0x25f7b0 */ }
void sub_25f870() { /* 0x25f870 */ }
void sub_25f8c0() { /* 0x25f8c0 */ }
void sub_25fa00() { /* 0x25fa00 */ }
void sub_25fd40() { /* 0x25fd40 */ }
void AMR_WB_2() { /* 0x260060 */ }
void sub_260350_subsdk0_260350() { /* 0x260350 */ }
void sub_260390() { /* 0x260390 */ }
void sub_260c90() { /* 0x260c90 */ }
void sub_261370() { /* 0x261370 */ }
void sub_2619c0() { /* 0x2619c0 */ }
void sub_261af0() { /* 0x261af0 */ }
void sub_261bb0() { /* 0x261bb0 */ }
void max_fs() { /* 0x261db0 */ }
void sub_262320() { /* 0x262320 */ }
void sub_262dd0() { /* 0x262dd0 */ }
void sub_2633a0() { /* 0x2633a0 */ }
void sub_263420() { /* 0x263420 */ }
void sub_263430() { /* 0x263430 */ }
void sub_263500_subsdk0_263500() { /* 0x263500 */ }
void sub_263720_subsdk0_263720() { /* 0x263720 */ }
void sub_2637d0() { /* 0x2637d0 */ }
void sub_263840() { /* 0x263840 */ }
void application() { /* 0x263c90 */ }
void f_1_2() { /* 0x264c30 */ }
void f_1_3() { /* 0x265140 */ }
void WMServer() { /* 0x265380 */ }
void sub_265cc0() { /* 0x265cc0 */ }
void f_1_0_200_OK() { /* 0x265d50 */ }
void f_1_0_200_OK_2() { /* 0x266400 */ }
void sub_266610_subsdk0_266610() { /* 0x266610 */ }
void sub_266720_subsdk0_266720() { /* 0x266720 */ }
void sub_266aa0() { /* 0x266aa0 */ }
void sub_266c20() { /* 0x266c20 */ }
void f_1_0_200_OK_3() { /* 0x266fc0 */ }
void sub_2671c0() { /* 0x2671c0 */ }
void sub_2672f0() { /* 0x2672f0 */ }
void sub_267300() { /* 0x267300 */ }
void sub_2673b0() { /* 0x2673b0 */ }
void sub_267490() { /* 0x267490 */ }
void sub_267610() { /* 0x267610 */ }
void sub_267710() { /* 0x267710 */ }
void sub_267750() { /* 0x267750 */ }
void sub_2679b0() { /* 0x2679b0 */ }
void sub_267ad0() { /* 0x267ad0 */ }
void sub_267b30() { /* 0x267b30 */ }
void sub_267b90() { /* 0x267b90 */ }
void sub_267e10() { /* 0x267e10 */ }
void theora() { /* 0x267e50 */ }
void sub_268bd0() { /* 0x268bd0 */ }
void NV_LOG_LEVEL() { /* 0x269340 */ }
void nvlog() { /* 0x2694d0 */ }
void sub_269580() { /* 0x269580 */ }
void sub_269870() { /* 0x269870 */ }
void sub_269890() { /* 0x269890 */ }
void sub_269c90() { /* 0x269c90 */ }
void sub_269d10() { /* 0x269d10 */ }
void sub_269d70() { /* 0x269d70 */ }
void sub_269ea0() { /* 0x269ea0 */ }
void sub_269f30() { /* 0x269f30 */ }
void sub_269ff0() { /* 0x269ff0 */ }
void sub_26a0a0() { /* 0x26a0a0 */ }
void sub_26a530() { /* 0x26a530 */ }
void sub_26a570() { /* 0x26a570 */ }
void sub_26a6d0() { /* 0x26a6d0 */ }
void sub_26a7c0_subsdk0_26a7c0() { /* 0x26a7c0 */ }
void sub_26a810() { /* 0x26a810 */ }
void sub_26a900() { /* 0x26a900 */ }
void sub_26a9c0() { /* 0x26a9c0 */ }
void sub_26aa10() { /* 0x26aa10 */ }
void sub_26aa50_subsdk0_26aa50() { /* 0x26aa50 */ }
void sub_26aa70() { /* 0x26aa70 */ }
void sub_26aa90() { /* 0x26aa90 */ }
void sub_26ab60() { /* 0x26ab60 */ }
void sub_26ac10() { /* 0x26ac10 */ }
void sub_26acb0() { /* 0x26acb0 */ }
void sub_26ad30() { /* 0x26ad30 */ }
void sub_26ade0() { /* 0x26ade0 */ }
void sub_26ae20() { /* 0x26ae20 */ }
void sub_26ae40() { /* 0x26ae40 */ }
void NV_CK_HEADER() { /* 0x26aef0 */ }
void sub_26b100() { /* 0x26b100 */ }
void sub_26b1c0() { /* 0x26b1c0 */ }
void sub_26b280() { /* 0x26b280 */ }
void sub_26b320() { /* 0x26b320 */ }
void chunked_subsdk0_26b560() { /* 0x26b560 */ }
void sub_26be20() { /* 0x26be20 */ }
void mpeg_2() { /* 0x26be30 */ }
void sub_26c370() { /* 0x26c370 */ }
void sub_26c530() { /* 0x26c530 */ }
void sub_26c6f0() { /* 0x26c6f0 */ }
void sub_26c790() { /* 0x26c790 */ }
void sub_26c7c0() { /* 0x26c7c0 */ }
void sub_26c860() { /* 0x26c860 */ }
void sub_26c890() { /* 0x26c890 */ }
void sub_26c8a0() { /* 0x26c8a0 */ }
void sub_26c8d0() { /* 0x26c8d0 */ }
void sub_26c900() { /* 0x26c900 */ }
void sub_26c960() { /* 0x26c960 */ }
void sub_26c9b0() { /* 0x26c9b0 */ }
void sub_26c9d0() { /* 0x26c9d0 */ }
void sub_26c9f0_subsdk0_26c9f0() { /* 0x26c9f0 */ }
void sub_26ca20() { /* 0x26ca20 */ }
void sub_26ca70() { /* 0x26ca70 */ }
void sub_26cb20() { /* 0x26cb20 */ }
void sub_26cb50() { /* 0x26cb50 */ }
void sub_26cbc0() { /* 0x26cbc0 */ }
void sub_26cc10() { /* 0x26cc10 */ }
void sub_26cc80() { /* 0x26cc80 */ }
void sub_26ccf0() { /* 0x26ccf0 */ }
void sub_26cd40() { /* 0x26cd40 */ }
void sub_26cd70() { /* 0x26cd70 */ }
void sub_26cda0() { /* 0x26cda0 */ }
void sub_26cdd0() { /* 0x26cdd0 */ }
void sub_26ce00() { /* 0x26ce00 */ }
void sub_26ce30() { /* 0x26ce30 */ }
void sub_26ce60_subsdk0_26ce60() { /* 0x26ce60 */ }
void sub_26ce90_subsdk0_26ce90() { /* 0x26ce90 */ }
void sub_26ceb0() { /* 0x26ceb0 */ }
void sub_26d0a0() { /* 0x26d0a0 */ }
void sub_26d120() { /* 0x26d120 */ }
void sub_26d1d0() { /* 0x26d1d0 */ }
void sub_26d210() { /* 0x26d210 */ }
void sub_26d220() { /* 0x26d220 */ }
void sub_26d240() { /* 0x26d240 */ }
void sub_26d2c0() { /* 0x26d2c0 */ }
void sub_26d2d0() { /* 0x26d2d0 */ }
void sub_26d2f0() { /* 0x26d2f0 */ }
void sub_26d310() { /* 0x26d310 */ }
void sub_26d320() { /* 0x26d320 */ }
void sub_26d350() { /* 0x26d350 */ }
void sub_26d370() { /* 0x26d370 */ }
void sub_26d390() { /* 0x26d390 */ }
void sub_26d3b0() { /* 0x26d3b0 */ }
void sub_26d4f0() { /* 0x26d4f0 */ }
void sub_26d580() { /* 0x26d580 */ }
void sub_26d690() { /* 0x26d690 */ }
void sub_26d6f0() { /* 0x26d6f0 */ }
void sub_26d750() { /* 0x26d750 */ }
void sub_26d900() { /* 0x26d900 */ }
void sub_26daa0() { /* 0x26daa0 */ }
void sub_26db10() { /* 0x26db10 */ }
void sub_26db20() { /* 0x26db20 */ }
void d_u() { /* 0x26dba0 */ }
// sub_26dd70: implemented in prog/matched/subsdk0/
void sub_26dd80() { /* 0x26dd80 */ }
void sub_26de40() { /* 0x26de40 */ }
void sub_26dea0() { /* 0x26dea0 */ }
void sub_26df10() { /* 0x26df10 */ }
void s_s() { /* 0x26df80 */ }
// sub_26e030: implemented in prog/matched/subsdk0/
// sub_26e040: implemented in prog/matched/subsdk0/
// sub_26e050: implemented in prog/matched/subsdk0/
// sub_26e060: implemented in prog/matched/subsdk0/
// sub_26e070: implemented in prog/matched/subsdk0/
// sub_26e080: implemented in prog/matched/subsdk0/
// sub_26e090: implemented in prog/matched/subsdk0/
// sub_26e0a0: implemented in prog/matched/subsdk0/
// sub_26e0b0: implemented in prog/matched/subsdk0/
// sub_26e0c0: implemented in prog/matched/subsdk0/
// sub_26e0d0: implemented in prog/matched/subsdk0/
// sub_26e0e0: implemented in prog/matched/subsdk0/
// sub_26e0f0: implemented in prog/matched/subsdk0/
// sub_26e100: implemented in prog/matched/subsdk0/
void libnvmmlite_msaudio() { /* 0x26e110 */ }
void sub_26e5e0() { /* 0x26e5e0 */ }
void sub_26e650() { /* 0x26e650 */ }
void sub_26e6b0() { /* 0x26e6b0 */ }
void sub_26e730() { /* 0x26e730 */ }
void sub_26e790() { /* 0x26e790 */ }
void sub_26e820() { /* 0x26e820 */ }
void sub_26e840() { /* 0x26e840 */ }
void sub_26e890() { /* 0x26e890 */ }
void sub_26e910() { /* 0x26e910 */ }
void sub_26e920() { /* 0x26e920 */ }
void sub_26e980() { /* 0x26e980 */ }
void sub_26e9e0() { /* 0x26e9e0 */ }
void sub_26ea00() { /* 0x26ea00 */ }
void sub_26ea30() { /* 0x26ea30 */ }
void sub_26ea60_subsdk0_26ea60() { /* 0x26ea60 */ }
void sub_26ea80() { /* 0x26ea80 */ }
void sub_26eab0() { /* 0x26eab0 */ }
void sub_26eb40() { /* 0x26eb40 */ }
void sub_26eb50() { /* 0x26eb50 */ }
void sub_26eb60_subsdk0_26eb60() { /* 0x26eb60 */ }
void sub_26eb70() { /* 0x26eb70 */ }
void sub_26eb80() { /* 0x26eb80 */ }
void sub_26ec10() { /* 0x26ec10 */ }
void sub_26eca0() { /* 0x26eca0 */ }
void sub_26ee90() { /* 0x26ee90 */ }
void sub_26ef10() { /* 0x26ef10 */ }
void sub_26f0c0() { /* 0x26f0c0 */ }
void sub_26f260() { /* 0x26f260 */ }
void sub_26f440_subsdk0_26f440() { /* 0x26f440 */ }
void sub_26f4c0() { /* 0x26f4c0 */ }
void sub_26f870() { /* 0x26f870 */ }
void sub_26f880() { /* 0x26f880 */ }
void sub_26f900() { /* 0x26f900 */ }
void sub_26f920_subsdk0_26f920() { /* 0x26f920 */ }
void sub_26fa30() { /* 0x26fa30 */ }
void sub_26fa80() { /* 0x26fa80 */ }
void sub_26fb90_subsdk0_26fb90() { /* 0x26fb90 */ }
void sub_26fcc0() { /* 0x26fcc0 */ }
void sub_26fd20() { /* 0x26fd20 */ }
void sub_26fdb0_subsdk0_26fdb0() { /* 0x26fdb0 */ }
void sub_26fde0() { /* 0x26fde0 */ }
void sub_26fe40() { /* 0x26fe40 */ }
void sub_26feb0() { /* 0x26feb0 */ }
void sub_26ffc0() { /* 0x26ffc0 */ }
void sub_270010() { /* 0x270010 */ }
void sub_270140() { /* 0x270140 */ }
void sub_2701f0() { /* 0x2701f0 */ }
void sub_270220() { /* 0x270220 */ }
void sub_270240() { /* 0x270240 */ }
void sub_270270() { /* 0x270270 */ }
void sub_270290() { /* 0x270290 */ }
void sub_2702b0() { /* 0x2702b0 */ }
void sub_2702d0() { /* 0x2702d0 */ }
void sub_2702e0() { /* 0x2702e0 */ }
void sub_2702f0() { /* 0x2702f0 */ }
void sub_270400() { /* 0x270400 */ }
// sub_270450: implemented in prog/matched/subsdk0/
// sub_270460: implemented in prog/matched/subsdk0/
// sub_270470: implemented in prog/matched/subsdk0/
void sub_270480_subsdk0_270480() { /* 0x270480 */ }
void sub_270700() { /* 0x270700 */ }
void NvxTrace() { /* 0x270860 */ }
void sub_2709e0() { /* 0x2709e0 */ }
void sub_270b90() { /* 0x270b90 */ }
void sub_270c40() { /* 0x270c40 */ }
void sub_270e30() { /* 0x270e30 */ }
void sub_270f40_subsdk0_270f40() { /* 0x270f40 */ }
void sub_271030() { /* 0x271030 */ }
void sub_271050() { /* 0x271050 */ }
void sub_271210() { /* 0x271210 */ }
void sub_271320() { /* 0x271320 */ }
void sub_271330() { /* 0x271330 */ }
void sub_271340() { /* 0x271340 */ }
void sub_2713b0() { /* 0x2713b0 */ }
void sub_2713c0() { /* 0x2713c0 */ }
void sub_2713f0() { /* 0x2713f0 */ }
void sub_271850() { /* 0x271850 */ }
void sub_2718d0() { /* 0x2718d0 */ }
void sub_2719f0() { /* 0x2719f0 */ }
void sub_271a30() { /* 0x271a30 */ }
void sub_271b20() { /* 0x271b20 */ }
void sub_271b60() { /* 0x271b60 */ }
void sub_271cb0() { /* 0x271cb0 */ }
void sub_271d00() { /* 0x271d00 */ }
void sub_271d30() { /* 0x271d30 */ }
void sub_272180() { /* 0x272180 */ }
void sub_2721c0() { /* 0x2721c0 */ }
void sub_2723e0() { /* 0x2723e0 */ }
void sub_272760() { /* 0x272760 */ }
void sub_2728d0() { /* 0x2728d0 */ }
void sub_272a40() { /* 0x272a40 */ }
void sub_272c40() { /* 0x272c40 */ }
void sub_272cc0() { /* 0x272cc0 */ }
void sub_272d20() { /* 0x272d20 */ }
void sub_273480() { /* 0x273480 */ }
// sub_273a10: implemented in prog/matched/subsdk0/
// sub_273a20: implemented in prog/matched/subsdk0/
void sub_273a30() { /* 0x273a30 */ }
void sub_273aa0() { /* 0x273aa0 */ }
void sub_273c50() { /* 0x273c50 */ }
void sub_273e00() { /* 0x273e00 */ }
void sub_273ea0() { /* 0x273ea0 */ }
void sub_273f60() { /* 0x273f60 */ }
void sub_274040() { /* 0x274040 */ }
void NVNVRMSURFACENV() { /* 0x274910 */ }
void sub_274b90() { /* 0x274b90 */ }
void sub_274db0() { /* 0x274db0 */ }
void sub_274df0() { /* 0x274df0 */ }
void sub_274ea0() { /* 0x274ea0 */ }
void sub_2755b0() { /* 0x2755b0 */ }
void sub_275600() { /* 0x275600 */ }
void sub_2756b0() { /* 0x2756b0 */ }
void sub_275730() { /* 0x275730 */ }
void sub_275790() { /* 0x275790 */ }
void sub_275800() { /* 0x275800 */ }
void sub_275840() { /* 0x275840 */ }
void sub_2759a0_subsdk0_2759a0() { /* 0x2759a0 */ }
void sub_275af0() { /* 0x275af0 */ }
void sub_2760f0() { /* 0x2760f0 */ }
void sub_276210() { /* 0x276210 */ }
void sub_276350() { /* 0x276350 */ }
void sub_276580() { /* 0x276580 */ }
void sub_2765a0() { /* 0x2765a0 */ }
void octet_stream_2() { /* 0x276610 */ }
void octet_stream_3() { /* 0x2766b0 */ }
void octet_stream_4() { /* 0x276760 */ }
void sub_276800() { /* 0x276800 */ }
void sub_2769e0() { /* 0x2769e0 */ }
void sub_276a30() { /* 0x276a30 */ }
void sub_276bb0() { /* 0x276bb0 */ }
void sub_276c60() { /* 0x276c60 */ }
void sub_276cc0() { /* 0x276cc0 */ }
void sub_277010() { /* 0x277010 */ }
void sub_277250() { /* 0x277250 */ }
void sub_277390() { /* 0x277390 */ }
void sub_277430() { /* 0x277430 */ }
void sub_2775c0() { /* 0x2775c0 */ }
void sub_277720() { /* 0x277720 */ }
void sub_277840() { /* 0x277840 */ }
void sub_2779b0() { /* 0x2779b0 */ }
void sub_277f40() { /* 0x277f40 */ }
void sub_277f50_subsdk0_277f50() { /* 0x277f50 */ }
void sub_278080() { /* 0x278080 */ }
void sub_2781b0() { /* 0x2781b0 */ }
void sub_278490() { /* 0x278490 */ }
void sub_2784e0() { /* 0x2784e0 */ }
void sub_278570() { /* 0x278570 */ }
void sub_2786d0() { /* 0x2786d0 */ }
void sub_278760() { /* 0x278760 */ }
void sub_2787b0() { /* 0x2787b0 */ }
void sub_2788c0() { /* 0x2788c0 */ }
void sub_278a20() { /* 0x278a20 */ }
void sub_278a80() { /* 0x278a80 */ }
void sub_278e30() { /* 0x278e30 */ }
void sub_278f00() { /* 0x278f00 */ }
void sub_278fd0() { /* 0x278fd0 */ }
void sub_279070() { /* 0x279070 */ }
void sub_279110() { /* 0x279110 */ }
void sub_279150() { /* 0x279150 */ }
void sub_279190() { /* 0x279190 */ }
void sub_279220() { /* 0x279220 */ }
void sub_279250() { /* 0x279250 */ }
void sub_279290() { /* 0x279290 */ }
void sub_2792c0() { /* 0x2792c0 */ }
void sub_279310() { /* 0x279310 */ }
void sub_279500() { /* 0x279500 */ }
void sub_279550() { /* 0x279550 */ }
void sub_2795a0() { /* 0x2795a0 */ }
void sub_2795f0() { /* 0x2795f0 */ }
void sub_2796b0() { /* 0x2796b0 */ }
void sub_279750() { /* 0x279750 */ }
void sub_279780() { /* 0x279780 */ }
void sub_2797a0() { /* 0x2797a0 */ }
void sub_2797c0() { /* 0x2797c0 */ }
void clock_binary() { /* 0x2797e0 */ }
void sub_279a70() { /* 0x279a70 */ }
void sub_279ab0() { /* 0x279ab0 */ }
void sub_279bb0() { /* 0x279bb0 */ }
void sub_279e60() { /* 0x279e60 */ }
void sub_27a0b0() { /* 0x27a0b0 */ }
void sub_27a0f0_subsdk0_27a0f0() { /* 0x27a0f0 */ }
void sub_27a340() { /* 0x27a340 */ }
void test() { /* 0x27a5c0 */ }
void sub_27a7c0() { /* 0x27a7c0 */ }
void sub_27a810() { /* 0x27a810 */ }
void sub_27a830() { /* 0x27a830 */ }
void sub_27ae60() { /* 0x27ae60 */ }
void sub_27afd0() { /* 0x27afd0 */ }
void sub_27b0c0() { /* 0x27b0c0 */ }
void f_3gpWriter() { /* 0x27b1c0 */ }
void sub_27b6d0() { /* 0x27b6d0 */ }
void sub_27b760() { /* 0x27b760 */ }
void sub_27b790() { /* 0x27b790 */ }
void video_scheduler_binary() { /* 0x27b800 */ }
void sub_27b9c0() { /* 0x27b9c0 */ }
void sub_27b9f0() { /* 0x27b9f0 */ }
void sub_27be20() { /* 0x27be20 */ }
void sub_27be40() { /* 0x27be40 */ }
void sub_27be80() { /* 0x27be80 */ }
void raw_reader_binary() { /* 0x27beb0 */ }
void test_2() { /* 0x27bf40 */ }
void test_3() { /* 0x27c060 */ }
void image_reader_binary() { /* 0x27c230 */ }
void video_reader_binary() { /* 0x27c2c0 */ }
void video_reader_binary_2() { /* 0x27c350 */ }
void video_reader_binary_3() { /* 0x27c3e0 */ }
void sub_27c480() { /* 0x27c480 */ }
void sub_27c4c0() { /* 0x27c4c0 */ }
void sub_27c5a0() { /* 0x27c5a0 */ }
void sub_27c800() { /* 0x27c800 */ }
void sub_27c880() { /* 0x27c880 */ }
void sub_27c8c0() { /* 0x27c8c0 */ }
void sub_27c920() { /* 0x27c920 */ }
void sub_27c950() { /* 0x27c950 */ }
void raw_writer_binary() { /* 0x27c9b0 */ }
void wav_writer_binary() { /* 0x27cad0 */ }
void amr_writer_binary() { /* 0x27cb60 */ }
void image_writer_binary() { /* 0x27cbf0 */ }
void image_writer_binary_2() { /* 0x27cc80 */ }
void video_writer_binary() { /* 0x27cd10 */ }
void video_writer_binary_2() { /* 0x27cda0 */ }
void sub_27ce40() { /* 0x27ce40 */ }
void sub_27ce80_subsdk0_27ce80() { /* 0x27ce80 */ }
void sub_27cfb0() { /* 0x27cfb0 */ }
void s_08d_s() { /* 0x27d020 */ }
void sub_27d3e0() { /* 0x27d3e0 */ }
void sub_27d460() { /* 0x27d460 */ }
void sub_27d5a0() { /* 0x27d5a0 */ }
void sub_27d5d0() { /* 0x27d5d0 */ }
void CallGraph() { /* 0x27d620 */ }
void enable_subsdk0_27d730() { /* 0x27d730 */ }
void sub_27dea0() { /* 0x27dea0 */ }
void sub_27df20() { /* 0x27df20 */ }
void sub_27df60() { /* 0x27df60 */ }
void sub_27dfa0() { /* 0x27dfa0 */ }
void sub_27dfe0() { /* 0x27dfe0 */ }
void sub_27e0a0() { /* 0x27e0a0 */ }
void sub_27e0e0() { /* 0x27e0e0 */ }
// sub_27e280: implemented in prog/matched/subsdk0/
void sub_27e290() { /* 0x27e290 */ }
void sub_27e320() { /* 0x27e320 */ }
void sub_27e390() { /* 0x27e390 */ }
void sub_27e3d0() { /* 0x27e3d0 */ }
void sub_27e470() { /* 0x27e470 */ }
void sub_27e4f0() { /* 0x27e4f0 */ }
void sub_27e530() { /* 0x27e530 */ }
void sub_27e600() { /* 0x27e600 */ }
void sub_27e6a0() { /* 0x27e6a0 */ }
void sub_27e7f0() { /* 0x27e7f0 */ }
void sub_27eab0() { /* 0x27eab0 */ }
void sub_27eb50() { /* 0x27eb50 */ }
void NvMMNvxRunWorkerThread() { /* 0x27eb90 */ }
void sub_27ed10() { /* 0x27ed10 */ }
void sub_27ee40() { /* 0x27ee40 */ }
// sub_27ee90: implemented in prog/matched/subsdk0/
// sub_27eec0: implemented in prog/matched/subsdk0/
void sub_27eee0() { /* 0x27eee0 */ }
void sub_27ef60() { /* 0x27ef60 */ }
void sub_27ef70() { /* 0x27ef70 */ }
void sub_27f0b0() { /* 0x27f0b0 */ }
void sub_27fb70() { /* 0x27fb70 */ }
void sub_2801c0() { /* 0x2801c0 */ }
void sub_280410() { /* 0x280410 */ }
void sub_280420() { /* 0x280420 */ }
void sub_280880() { /* 0x280880 */ }
void sub_280e70() { /* 0x280e70 */ }
void sub_280fc0() { /* 0x280fc0 */ }
void sub_281260() { /* 0x281260 */ }
void sub_2815e0() { /* 0x2815e0 */ }
void sub_281990() { /* 0x281990 */ }
void Total_packets_d() { /* 0x281cc0 */ }
void sub_2824f0() { /* 0x2824f0 */ }
void image_decoder() { /* 0x282a60 */ }
void sub_283b90() { /* 0x283b90 */ }
void sub_2846d0() { /* 0x2846d0 */ }
void sub_2852e0() { /* 0x2852e0 */ }
void sub_286020() { /* 0x286020 */ }
void sub_286c00() { /* 0x286c00 */ }
void sub_286f90() { /* 0x286f90 */ }
void sub_28bba0() { /* 0x28bba0 */ }
void sub_28be60() { /* 0x28be60 */ }
void sub_28c7e0() { /* 0x28c7e0 */ }
void sub_28cd00() { /* 0x28cd00 */ }
void sub_28d140() { /* 0x28d140 */ }
void sub_28d160() { /* 0x28d160 */ }
void sub_28d180() { /* 0x28d180 */ }
void sub_28d1c0() { /* 0x28d1c0 */ }
void sub_28d240() { /* 0x28d240 */ }
void sub_28d290() { /* 0x28d290 */ }
void sub_28d310() { /* 0x28d310 */ }
void sub_28d320() { /* 0x28d320 */ }
void sub_28d330() { /* 0x28d330 */ }
// sub_28d380: implemented in prog/matched/subsdk0/
void sub_28d390() { /* 0x28d390 */ }
void sub_28d3c0() { /* 0x28d3c0 */ }
void sub_28d590() { /* 0x28d590 */ }
void sub_28d5c0() { /* 0x28d5c0 */ }
void sub_28d5e0() { /* 0x28d5e0 */ }
void sub_28d740() { /* 0x28d740 */ }
void sub_28d9a0() { /* 0x28d9a0 */ }
void sub_28dc50() { /* 0x28dc50 */ }
void NVNVRMSURFACENV_2() { /* 0x28dd90 */ }
void NVNVRMSURFACENV_3() { /* 0x28de70 */ }
void sub_28df10() { /* 0x28df10 */ }
void sub_28e140() { /* 0x28e140 */ }
void sub_28e180() { /* 0x28e180 */ }
void sub_28e340() { /* 0x28e340 */ }
void sub_28e3a0() { /* 0x28e3a0 */ }
void sub_28e3c0() { /* 0x28e3c0 */ }
void sub_28e460() { /* 0x28e460 */ }
void sub_28e7b0() { /* 0x28e7b0 */ }
void sub_28e880() { /* 0x28e880 */ }
void sub_28ea20() { /* 0x28ea20 */ }
void sub_28ea60() { /* 0x28ea60 */ }
void sub_28f180() { /* 0x28f180 */ }
void sub_28f240() { /* 0x28f240 */ }
void sub_28f4b0() { /* 0x28f4b0 */ }
void sub_28f6a0() { /* 0x28f6a0 */ }
void sub_28fd00() { /* 0x28fd00 */ }
// sub_28ff60: implemented in prog/matched/subsdk0/
void sub_28ff70() { /* 0x28ff70 */ }
// sub_28ff90: implemented in prog/matched/subsdk0/
void sub_28ffa0() { /* 0x28ffa0 */ }
void sub_28ffd0() { /* 0x28ffd0 */ }
void sub_290000() { /* 0x290000 */ }
void sub_2901e0() { /* 0x2901e0 */ }
void sub_2903b0() { /* 0x2903b0 */ }
void sub_2904c0() { /* 0x2904c0 */ }
void BlockADTSDec() { /* 0x2905d0 */ }
void BlockBSACDec() { /* 0x2906f0 */ }
void BlockWavDec() { /* 0x290810 */ }
void WMAPRODec() { /* 0x2908a0 */ }
void WMALSLDec() { /* 0x2909b0 */ }
void BlockOGGDec() { /* 0x290ac0 */ }
void BlockAMRDec() { /* 0x290b50 */ }
void BlockAMRWBDec() { /* 0x290c50 */ }
void sub_290d50_subsdk0_290d50() { /* 0x290d50 */ }
void sub_290d80() { /* 0x290d80 */ }
void sub_290db0() { /* 0x290db0 */ }
void sub_2918e0() { /* 0x2918e0 */ }
void sub_292220() { /* 0x292220 */ }
void sub_2923c0() { /* 0x2923c0 */ }
void sub_292510() { /* 0x292510 */ }
void sub_2925b0() { /* 0x2925b0 */ }
void sub_292600() { /* 0x292600 */ }
void sub_2927a0() { /* 0x2927a0 */ }
void sub_2928d0() { /* 0x2928d0 */ }
void sub_292b30() { /* 0x292b30 */ }
void sub_292bf0() { /* 0x292bf0 */ }
void sub_292c30() { /* 0x292c30 */ }
void sub_292d30() { /* 0x292d30 */ }
void sub_292da0() { /* 0x292da0 */ }
void sub_292e10() { /* 0x292e10 */ }
void sub_292e30() { /* 0x292e30 */ }
void sub_292e50() { /* 0x292e50 */ }
void sub_292f10() { /* 0x292f10 */ }
void sub_292f50() { /* 0x292f50 */ }
void sub_292fd0() { /* 0x292fd0 */ }
void sub_293050() { /* 0x293050 */ }
void sub_293060() { /* 0x293060 */ }
void sub_293070() { /* 0x293070 */ }
void sub_293260() { /* 0x293260 */ }
void sub_2934e0() { /* 0x2934e0 */ }
void sub_293510() { /* 0x293510 */ }
void sub_2937e0() { /* 0x2937e0 */ }
void sub_293830() { /* 0x293830 */ }
void sub_2938b0() { /* 0x2938b0 */ }
void sub_293ab0_subsdk0_293ab0() { /* 0x293ab0 */ }
void sub_293af0() { /* 0x293af0 */ }
void sub_293b10() { /* 0x293b10 */ }
void sub_293b30() { /* 0x293b30 */ }
void iv_renderer_rgb565() { /* 0x293b40 */ }
void sub_293f60_subsdk0_293f60() { /* 0x293f60 */ }
void sub_293f70() { /* 0x293f70 */ }
void sub_293f80() { /* 0x293f80 */ }
void sub_293f90() { /* 0x293f90 */ }
void sub_293fa0() { /* 0x293fa0 */ }
void sub_293fb0() { /* 0x293fb0 */ }
void sub_293fc0() { /* 0x293fc0 */ }
void sub_293fd0() { /* 0x293fd0 */ }
void sub_293fe0() { /* 0x293fe0 */ }
void sub_293ff0() { /* 0x293ff0 */ }
void sub_294000() { /* 0x294000 */ }
void sub_2945e0_subsdk0_2945e0() { /* 0x2945e0 */ }
void sub_294790() { /* 0x294790 */ }
void sub_2947c0() { /* 0x2947c0 */ }
void sub_294870_subsdk0_294870() { /* 0x294870 */ }
void sub_2949e0() { /* 0x2949e0 */ }
void sub_294a20() { /* 0x294a20 */ }
void sub_294a90_subsdk0_294a90() { /* 0x294a90 */ }
void sub_295130() { /* 0x295130 */ }
void sub_295350() { /* 0x295350 */ }
void Frame_d_s() { /* 0x2955e0 */ }
void sub_295850_subsdk0_295850() { /* 0x295850 */ }
void sub_295a00_subsdk0_295a00() { /* 0x295a00 */ }
void sub_295a30() { /* 0x295a30 */ }
void sub_295f80() { /* 0x295f80 */ }
void dropped_frames_d() { /* 0x2968b0 */ }
void frame_delivery() { /* 0x296d60 */ }
void sub_296eb0() { /* 0x296eb0 */ }
void iv_renderer_loopback() { /* 0x296f20 */ }
void sub_2970a0() { /* 0x2970a0 */ }
// sub_2970d0: implemented in prog/matched/subsdk0/
// sub_2970e0_subsdk0_2970e0: implemented in prog/matched/subsdk0/
// sub_2970f0: implemented in prog/matched/subsdk0/
void sub_297100() { /* 0x297100 */ }
// sub_297110: implemented in prog/matched/subsdk0/
// sub_297120: implemented in prog/matched/subsdk0/
void sub_297130() { /* 0x297130 */ }
// sub_297280: implemented in prog/matched/subsdk0/
// sub_297290: implemented in prog/matched/subsdk0/
// sub_2972a0: implemented in prog/matched/subsdk0/
void sub_2972b0() { /* 0x2972b0 */ }
void sub_2972e0() { /* 0x2972e0 */ }
void sub_297310() { /* 0x297310 */ }
void sub_2974a0() { /* 0x2974a0 */ }
void sub_297690() { /* 0x297690 */ }
void sub_297900() { /* 0x297900 */ }
void sub_297cd0() { /* 0x297cd0 */ }
void sub_297e30_subsdk0_297e30() { /* 0x297e30 */ }
void sub_297f90() { /* 0x297f90 */ }
void sub_298900() { /* 0x298900 */ }
void sub_2991c0() { /* 0x2991c0 */ }
void sub_299420_subsdk0_299420() { /* 0x299420 */ }
void sub_2995c0() { /* 0x2995c0 */ }
void sub_299840() { /* 0x299840 */ }
void sub_299ac0_subsdk0_299ac0() { /* 0x299ac0 */ }
void sub_299b20() { /* 0x299b20 */ }
void sub_299b80() { /* 0x299b80 */ }
void sub_299ba0() { /* 0x299ba0 */ }
void sub_299bc0() { /* 0x299bc0 */ }
void sub_299bf0() { /* 0x299bf0 */ }
void sub_299c20() { /* 0x299c20 */ }
void sub_299ca0() { /* 0x299ca0 */ }
void sub_299d20() { /* 0x299d20 */ }
void sub_299d30_subsdk0_299d30() { /* 0x299d30 */ }
void sub_299d40() { /* 0x299d40 */ }
void sub_299eb0() { /* 0x299eb0 */ }
void sub_29a080_subsdk0_29a080() { /* 0x29a080 */ }
// sub_29a150_subsdk0_29a150: implemented in prog/matched/subsdk0/
void sub_29a160() { /* 0x29a160 */ }
void sub_29a1f0_subsdk0_29a1f0() { /* 0x29a1f0 */ }
void sub_29a210() { /* 0x29a210 */ }
void sub_29a300() { /* 0x29a300 */ }
void sub_29a4a0() { /* 0x29a4a0 */ }
void BlockAmrnbEnc() { /* 0x29a660 */ }
void BlockAmrwbEnc() { /* 0x29a770 */ }
void BlockilbcEnc() { /* 0x29a880 */ }
void BlockAmrwbEnc_2() { /* 0x29a910 */ }
void sub_29aa20() { /* 0x29aa20 */ }
void sub_29aa50() { /* 0x29aa50 */ }
void sub_29aa80() { /* 0x29aa80 */ }
void sub_29ab80() { /* 0x29ab80 */ }
void sub_29ac50() { /* 0x29ac50 */ }
void sub_29ada0() { /* 0x29ada0 */ }
void sub_29aeb0() { /* 0x29aeb0 */ }
// sub_29af10: implemented in prog/matched/subsdk0/
void sub_29af20_subsdk0_29af20() { /* 0x29af20 */ }
void sub_29af60() { /* 0x29af60 */ }
void sub_29afa0() { /* 0x29afa0 */ }
void sub_29b060() { /* 0x29b060 */ }
void sub_29b0f0_subsdk0_29b0f0() { /* 0x29b0f0 */ }
void sub_29b520() { /* 0x29b520 */ }
void sub_29b690() { /* 0x29b690 */ }
void sub_29b700() { /* 0x29b700 */ }
void sub_29b770() { /* 0x29b770 */ }
void sub_29b790() { /* 0x29b790 */ }
void sub_29b7b0() { /* 0x29b7b0 */ }
void sub_29b7e0() { /* 0x29b7e0 */ }
void sub_29b810() { /* 0x29b810 */ }
void sub_29b890() { /* 0x29b890 */ }
void sub_29b910() { /* 0x29b910 */ }
void sub_29b920() { /* 0x29b920 */ }
void OMX_Nvidia_video_extractor() { /* 0x29b930 */ }
void sub_29ba40() { /* 0x29ba40 */ }
void sub_29ba70() { /* 0x29ba70 */ }
void sub_29ba90() { /* 0x29ba90 */ }
void sub_29bab0() { /* 0x29bab0 */ }
void sub_29bb60() { /* 0x29bb60 */ }
void sub_29bb90() { /* 0x29bb90 */ }
void sub_29bf40() { /* 0x29bf40 */ }
void sub_29bfc0() { /* 0x29bfc0 */ }
// sub_29c020: implemented in prog/matched/subsdk0/
void sub_29c030_subsdk0_29c030() { /* 0x29c030 */ }
void sub_29c070() { /* 0x29c070 */ }
void sub_29c540() { /* 0x29c540 */ }
void BlockASFParser() { /* 0x29c960 */ }
void sub_29c9d0() { /* 0x29c9d0 */ }
void BlockMKVParser() { /* 0x29cbe0 */ }
void Block3GPParser() { /* 0x29cc50 */ }
void BlockAVIParser() { /* 0x29ccc0 */ }
void BlockWAVParser() { /* 0x29cd30 */ }
void BlockAACParser() { /* 0x29cda0 */ }
void SuperParser() { /* 0x29ce10 */ }
void sub_29ce80() { /* 0x29ce80 */ }
void sub_29cf10() { /* 0x29cf10 */ }
void sub_29d110() { /* 0x29d110 */ }
void sub_29d2f0() { /* 0x29d2f0 */ }
void sub_29d670_subsdk0_29d670() { /* 0x29d670 */ }
void sub_29d8d0() { /* 0x29d8d0 */ }
void sub_29d8e0_subsdk0_29d8e0() { /* 0x29d8e0 */ }
void sub_29da40() { /* 0x29da40 */ }
void sub_29daa0() { /* 0x29daa0 */ }
void sub_29dad0() { /* 0x29dad0 */ }
void sub_29db00_subsdk0_29db00() { /* 0x29db00 */ }
void sub_29db10() { /* 0x29db10 */ }
void sub_29dc20() { /* 0x29dc20 */ }
void sub_29e030() { /* 0x29e030 */ }
void sub_29e100() { /* 0x29e100 */ }
void sub_29e250() { /* 0x29e250 */ }
void sub_29e2a0() { /* 0x29e2a0 */ }
void sub_29e4e0() { /* 0x29e4e0 */ }
// sub_29e6c0: implemented in prog/matched/subsdk0/
// sub_29e6d0_subsdk0_29e6d0: implemented in prog/matched/subsdk0/
void BlockAACEnc() { /* 0x29e6e0 */ }
void BlockSuperJpgDec() { /* 0x29e940 */ }
void sub_29eb30() { /* 0x29eb30 */ }
void sub_29eb60() { /* 0x29eb60 */ }
void sub_29ece0() { /* 0x29ece0 */ }
void sub_29edc0_subsdk0_29edc0() { /* 0x29edc0 */ }
void sub_29f0c0() { /* 0x29f0c0 */ }
void sub_29f180() { /* 0x29f180 */ }
void sub_29f270() { /* 0x29f270 */ }
void sub_29f380() { /* 0x29f380 */ }
void sub_29f3e0() { /* 0x29f3e0 */ }
void sub_29f400_subsdk0_29f400() { /* 0x29f400 */ }
void sub_29f430() { /* 0x29f430 */ }
void sub_29f4b0() { /* 0x29f4b0 */ }
void sub_29f4c0() { /* 0x29f4c0 */ }
void BlockJpgEnc() { /* 0x29f4f0 */ }
void BlockMP3Dec() { /* 0x29f700 */ }
void BlockMP3Dec_2() { /* 0x29f7f0 */ }
void BlockAACDec() { /* 0x29f8e0 */ }
void BlockWMADec() { /* 0x29fa10 */ }
void sub_29fb10() { /* 0x29fb10 */ }
void BlockH265Dec() { /* 0x29fda0 */ }
void OMX_Nvidia_h265_decode_low_latency() { /* 0x29fea0 */ }
void BlockH264Dec() { /* 0x29fef0 */ }
void OMX_Nvidia_h264_decode_low_latency() { /* 0x29fff0 */ }
void BlockH264Dec_2() { /* 0x2a0040 */ }
void BlockVc1Dec() { /* 0x2a0140 */ }
void video_decoder() { /* 0x2a0240 */ }
void BlockVP8Dec() { /* 0x2a02b0 */ }
void BlockVP9Dec() { /* 0x2a03d0 */ }
void BlockMpeg2Dec() { /* 0x2a04f0 */ }
void BlockMJpgDec() { /* 0x2a05f0 */ }
void sub_2a0690() { /* 0x2a0690 */ }
void OMX_Nvidia_h263_decode() { /* 0x2a06d0 */ }
void sub_2a1040() { /* 0x2a1040 */ }
void sub_2a16f0() { /* 0x2a16f0 */ }
void sub_2a1c00() { /* 0x2a1c00 */ }
void sub_2a1fc0() { /* 0x2a1fc0 */ }
void OMX_Nvidia_h265_decode() { /* 0x2a2140 */ }
void sub_2a2680_subsdk0_2a2680() { /* 0x2a2680 */ }
void sub_2a26c0() { /* 0x2a26c0 */ }
void sub_2a27a0_subsdk0_2a27a0() { /* 0x2a27a0 */ }
void sub_2a27d0() { /* 0x2a27d0 */ }
void sub_2a2850() { /* 0x2a2850 */ }
void sub_2a28c0() { /* 0x2a28c0 */ }
void sub_2a28d0() { /* 0x2a28d0 */ }
void sub_2a2900() { /* 0x2a2900 */ }
void BlockHevcEnc() { /* 0x2a2920 */ }
void enctune() { /* 0x2a2a50 */ }
void BlockAvcEnc() { /* 0x2a2d70 */ }
void sub_2a2eb0() { /* 0x2a2eb0 */ }
void sub_2a2f20() { /* 0x2a2f20 */ }
void sub_2a38f0() { /* 0x2a38f0 */ }
void sub_2a48c0() { /* 0x2a48c0 */ }
void sub_2a4c30() { /* 0x2a4c30 */ }
void sub_2a5320() { /* 0x2a5320 */ }
void InsertSPSPPSAtIDR() { /* 0x2a53f0 */ }
void sub_2a68f0_subsdk0_2a68f0() { /* 0x2a68f0 */ }
void sub_2a6950() { /* 0x2a6950 */ }
void sub_2a6970() { /* 0x2a6970 */ }
void sub_2a69a0() { /* 0x2a69a0 */ }
void sub_2a6a20() { /* 0x2a6a20 */ }
void sub_2a6a30() { /* 0x2a6a30 */ }
void sub_2a6a60() { /* 0x2a6a60 */ }
void sub_2a6c30() { /* 0x2a6c30 */ }
// sub_2a6fa0: implemented in prog/matched/subsdk0/
// sub_2a6fb0: implemented in prog/matched/subsdk0/
// sub_2a6fc0_subsdk0_2a6fc0: implemented in prog/matched/subsdk0/
// sub_2a6fd0: implemented in prog/matched/subsdk0/
// sub_2a6fe0: implemented in prog/matched/subsdk0/
// sub_2a6ff0: implemented in prog/matched/subsdk0/
// sub_2a7000: implemented in prog/matched/subsdk0/
// sub_2a7010: implemented in prog/matched/subsdk0/
// sub_2a7020: implemented in prog/matched/subsdk0/
// sub_2a7030: implemented in prog/matched/subsdk0/
// sub_2a7040: implemented in prog/matched/subsdk0/
// sub_2a7050: implemented in prog/matched/subsdk0/
void sub_2a7060() { /* 0x2a7060 */ }
void sub_2a70b0() { /* 0x2a70b0 */ }
void sub_2a70c0() { /* 0x2a70c0 */ }
void sub_2a7310() { /* 0x2a7310 */ }
void PLAYREADYCTR() { /* 0x2a8b50 */ }
void sub_2aa400() { /* 0x2aa400 */ }
void sub_2aa740() { /* 0x2aa740 */ }
void sub_2aa920() { /* 0x2aa920 */ }
void sub_2aa940_subsdk0_2aa940() { /* 0x2aa940 */ }
void sub_2aaf20() { /* 0x2aaf20 */ }
void sub_2ab540() { /* 0x2ab540 */ }
void sub_2ab670() { /* 0x2ab670 */ }
void sub_2ab7d0() { /* 0x2ab7d0 */ }
void sub_2abae0() { /* 0x2abae0 */ }
void sub_2abbd0() { /* 0x2abbd0 */ }
void sub_2abf40() { /* 0x2abf40 */ }
void sub_2ac000() { /* 0x2ac000 */ }
void sub_2ac100() { /* 0x2ac100 */ }
void sub_2ac1f0() { /* 0x2ac1f0 */ }
void Total_packets_d_2() { /* 0x2ac4b0 */ }
void sub_2ac840() { /* 0x2ac840 */ }
void sub_2acda0() { /* 0x2acda0 */ }
void sub_2acea0() { /* 0x2acea0 */ }
void sub_2adca0() { /* 0x2adca0 */ }
void sub_2ae240() { /* 0x2ae240 */ }
void sub_2ae400() { /* 0x2ae400 */ }
void sub_2ae4d0() { /* 0x2ae4d0 */ }
// sub_2ae640: implemented in prog/matched/subsdk0/
void sub_2ae650() { /* 0x2ae650 */ }
void sub_2ae710() { /* 0x2ae710 */ }
void sub_2ae980() { /* 0x2ae980 */ }
void sub_2aeb00() { /* 0x2aeb00 */ }
void sub_2aecf0() { /* 0x2aecf0 */ }
void sub_2aeeb0() { /* 0x2aeeb0 */ }
void sub_2aeff0() { /* 0x2aeff0 */ }
void NvxRenderSurfaceToOverlayANW() { /* 0x2af040 */ }
void sub_2af330_subsdk0_2af330() { /* 0x2af330 */ }
void sub_2af360() { /* 0x2af360 */ }
void sub_2af3f0() { /* 0x2af3f0 */ }
void sub_2af4b0() { /* 0x2af4b0 */ }
void sub_2af520() { /* 0x2af520 */ }
void sub_2af540() { /* 0x2af540 */ }
void sub_2af5d0() { /* 0x2af5d0 */ }
void sub_2af600() { /* 0x2af600 */ }
void sub_2af6c0() { /* 0x2af6c0 */ }
// sub_2af990: implemented in prog/matched/subsdk0/
// sub_2af9a0: implemented in prog/matched/subsdk0/
void sub_2af9b0() { /* 0x2af9b0 */ }
void sub_2afc70() { /* 0x2afc70 */ }
void sub_2afd40() { /* 0x2afd40 */ }
void sub_2afd80() { /* 0x2afd80 */ }
void sub_2aff70() { /* 0x2aff70 */ }
void sub_2b01b0() { /* 0x2b01b0 */ }
void sub_2b0210_subsdk0_2b0210() { /* 0x2b0210 */ }
void sub_2b0240() { /* 0x2b0240 */ }
void sub_2b0340() { /* 0x2b0340 */ }
void sub_2b0d30() { /* 0x2b0d30 */ }
void sub_2b0df0_subsdk0_2b0df0() { /* 0x2b0df0 */ }
void sub_2b0f60() { /* 0x2b0f60 */ }
void sub_2b1030_subsdk0_2b1030() { /* 0x2b1030 */ }
void sub_2b1080_subsdk0_2b1080() { /* 0x2b1080 */ }
void sub_2b1110() { /* 0x2b1110 */ }
// sub_2b1140: implemented in prog/matched/subsdk0/
void sub_2b1150_subsdk0_2b1150() { /* 0x2b1150 */ }
void sub_2b1180() { /* 0x2b1180 */ }
void sub_2b13a0_subsdk0_2b13a0() { /* 0x2b13a0 */ }
void sub_2b1560() { /* 0x2b1560 */ }
void sub_2b1580() { /* 0x2b1580 */ }
void sub_2b15b0() { /* 0x2b15b0 */ }
void snvddk2d_dump_05d() { /* 0x2b15f0 */ }
void sub_2b16c0() { /* 0x2b16c0 */ }
void sub_2b17b0_subsdk0_2b17b0() { /* 0x2b17b0 */ }
void sub_2b1840() { /* 0x2b1840 */ }
void coverage() { /* 0x2b1870 */ }
void sub_2b2ed0() { /* 0x2b2ed0 */ }
void sub_2b3050() { /* 0x2b3050 */ }
void sub_2b3100() { /* 0x2b3100 */ }
void sub_2b3130() { /* 0x2b3130 */ }
void sub_2b36d0() { /* 0x2b36d0 */ }
void sub_2b3700() { /* 0x2b3700 */ }
void sub_2b3ca0() { /* 0x2b3ca0 */ }
void sub_2b3cf0() { /* 0x2b3cf0 */ }
void sub_2b3d90() { /* 0x2b3d90 */ }
void sub_2b3ec0() { /* 0x2b3ec0 */ }
void sub_2b3fc0_subsdk0_2b3fc0() { /* 0x2b3fc0 */ }
void sub_2b40e0() { /* 0x2b40e0 */ }
void sub_2b4360() { /* 0x2b4360 */ }
void sub_2b44c0() { /* 0x2b44c0 */ }
void sub_2b4500() { /* 0x2b4500 */ }
// sub_2b4670_subsdk0_2b4670: implemented in prog/matched/subsdk0/
void sub_2b4680() { /* 0x2b4680 */ }
void sub_2b46a0() { /* 0x2b46a0 */ }
void sub_2b46e0() { /* 0x2b46e0 */ }
void sub_2b47f0() { /* 0x2b47f0 */ }
void sub_2b48f0() { /* 0x2b48f0 */ }
void sub_2b4950() { /* 0x2b4950 */ }
void sub_2b4d10() { /* 0x2b4d10 */ }
void sub_2b4d40() { /* 0x2b4d40 */ }
void sub_2b4dd0() { /* 0x2b4dd0 */ }
// sub_2b4e20: implemented in prog/matched/subsdk0/
void sub_2b4e30() { /* 0x2b4e30 */ }
void sub_2b54b0() { /* 0x2b54b0 */ }
void sub_2b55e0() { /* 0x2b55e0 */ }
void sub_2b5640_subsdk0_2b5640() { /* 0x2b5640 */ }
void sub_2b5810() { /* 0x2b5810 */ }
void sub_2b5a40() { /* 0x2b5a40 */ }
void sub_2b6a40() { /* 0x2b6a40 */ }
void sub_2b6cc0_subsdk0_2b6cc0() { /* 0x2b6cc0 */ }
void sub_2b6f50() { /* 0x2b6f50 */ }
void sub_2b7460() { /* 0x2b7460 */ }
void sub_2b79b0() { /* 0x2b79b0 */ }
void sub_2b7b80() { /* 0x2b7b80 */ }
void sub_2b7bb0() { /* 0x2b7bb0 */ }
void sub_2b7be0() { /* 0x2b7be0 */ }
void sub_2b7c20() { /* 0x2b7c20 */ }
// sub_2b7c80: implemented in prog/matched/subsdk0/
void sub_2b7c90() { /* 0x2b7c90 */ }
void sub_2b7cc0() { /* 0x2b7cc0 */ }
void sub_2b7cf0() { /* 0x2b7cf0 */ }
void sub_2b7d00() { /* 0x2b7d00 */ }
void sub_2b7d10() { /* 0x2b7d10 */ }
void sub_2b7d90() { /* 0x2b7d90 */ }
// hw_vic: implemented in prog/matched/subsdk0/
// VIC_hardware_backend: implemented in prog/matched/subsdk0/
void sub_2b7df0() { /* 0x2b7df0 */ }
// sub_2b8390: implemented in prog/matched/subsdk0/
// sub_2b83a0: implemented in prog/matched/subsdk0/
void sub_2b83b0() { /* 0x2b83b0 */ }
void sub_2b83d0() { /* 0x2b83d0 */ }
void sub_2b83f0() { /* 0x2b83f0 */ }
void sub_2b8630() { /* 0x2b8630 */ }
void sub_2b86e0() { /* 0x2b86e0 */ }
void sub_2b8940_subsdk0_2b8940() { /* 0x2b8940 */ }
void sub_2b8be0() { /* 0x2b8be0 */ }
void sub_2b9150() { /* 0x2b9150 */ }
void sub_2b9530() { /* 0x2b9530 */ }
void sub_2b9640_subsdk0_2b9640() { /* 0x2b9640 */ }
void sub_2b9920_subsdk0_2b9920() { /* 0x2b9920 */ }
void sub_2b9a90() { /* 0x2b9a90 */ }
void sub_2b9ab0() { /* 0x2b9ab0 */ }
void sub_2b9b80_subsdk0_2b9b80() { /* 0x2b9b80 */ }
void sub_2b9dc0() { /* 0x2b9dc0 */ }
void sub_2b9dd0_subsdk0_2b9dd0() { /* 0x2b9dd0 */ }
void sub_2ba120() { /* 0x2ba120 */ }
void sub_2ba130() { /* 0x2ba130 */ }
void sub_2ba190() { /* 0x2ba190 */ }
void sub_2ba240() { /* 0x2ba240 */ }
void sub_2ba2d0_subsdk0_2ba2d0() { /* 0x2ba2d0 */ }
void sub_2ba360() { /* 0x2ba360 */ }
void sub_2ba660() { /* 0x2ba660 */ }
// sub_2ba9d0_subsdk0_2ba9d0: implemented in prog/matched/subsdk0/
void sub_2ba9e0_subsdk0_2ba9e0() { /* 0x2ba9e0 */ }
// sub_2baa70: implemented in prog/matched/subsdk0/
// sub_2baa80: implemented in prog/matched/subsdk0/
void sub_2baa90() { /* 0x2baa90 */ }
void sub_2bad00_subsdk0_2bad00() { /* 0x2bad00 */ }
void sub_2bad20() { /* 0x2bad20 */ }
void sub_2bad60_subsdk0_2bad60() { /* 0x2bad60 */ }
// sub_2bb1e0: implemented in prog/matched/subsdk0/
// sub_2bb1f0_subsdk0_2bb1f0: implemented in prog/matched/subsdk0/
// sub_2bb200: implemented in prog/matched/subsdk0/
// sub_2bb210: implemented in prog/matched/subsdk0/
// sub_2bb220: implemented in prog/matched/subsdk0/
// sub_2bb230: implemented in prog/matched/subsdk0/
// sub_2bb240: implemented in prog/matched/subsdk0/
// sub_2bb250_subsdk0_2bb250: implemented in prog/matched/subsdk0/
// sub_2bb260: implemented in prog/matched/subsdk0/
void sub_2bb270() { /* 0x2bb270 */ }
void sub_2bb4c0() { /* 0x2bb4c0 */ }
void sub_2bb540() { /* 0x2bb540 */ }
void sub_2bb650_subsdk0_2bb650() { /* 0x2bb650 */ }
void sub_2bb900_subsdk0_2bb900() { /* 0x2bb900 */ }
void sub_2bb9f0() { /* 0x2bb9f0 */ }
void sub_2bbab0() { /* 0x2bbab0 */ }
void sub_2bbac0() { /* 0x2bbac0 */ }
void sub_2bbad0_subsdk0_2bbad0() { /* 0x2bbad0 */ }
void sub_2bc220_subsdk0_2bc220() { /* 0x2bc220 */ }
void sub_2bca20() { /* 0x2bca20 */ }
void sub_2bcc20() { /* 0x2bcc20 */ }
void sub_2bccc0() { /* 0x2bccc0 */ }
void sub_2bcdc0() { /* 0x2bcdc0 */ }
void sub_2bd150() { /* 0x2bd150 */ }
void sub_2bd6c0() { /* 0x2bd6c0 */ }
void sub_2bd7a0() { /* 0x2bd7a0 */ }
void sub_2bd7b0() { /* 0x2bd7b0 */ }
void sub_2bd8c0() { /* 0x2bd8c0 */ }
void sub_2bfb40() { /* 0x2bfb40 */ }
void sub_2bfe60() { /* 0x2bfe60 */ }
void sub_2c00e0() { /* 0x2c00e0 */ }
void sub_2c0150() { /* 0x2c0150 */ }
void sub_2c0170() { /* 0x2c0170 */ }
void NvMMTVMRMVCDeinterlaceThread() { /* 0x2c01c0 */ }
void DeinterlaceThread() { /* 0x2c0490 */ }
void DeinterlaceMVCStitchThread() { /* 0x2c0de0 */ }
void NVMMLITE_TVMRDEC() { /* 0x2c1050 */ }
void TVMRCombine_MVCViews_Interlaced() { /* 0x2c1210 */ }
void NVMMLITE_TVMRDEC_2() { /* 0x2c1410 */ }
void NVMMLITE_TVMRDEC_3() { /* 0x2c1cf0 */ }
void NVMMLITE_TVMRDEC_4() { /* 0x2c2370 */ }
void sub_2c24a0() { /* 0x2c24a0 */ }
void sub_2c2500() { /* 0x2c2500 */ }
void sub_2c2720() { /* 0x2c2720 */ }
void InterlaceBufferAlloc() { /* 0x2c2d90 */ }
void sub_2c3210() { /* 0x2c3210 */ }
void sub_2c32b0() { /* 0x2c32b0 */ }
void NvRmSurfaceLayout_Tiled() { /* 0x2c3310 */ }
void sub_2c5480() { /* 0x2c5480 */ }
void sub_2c59c0() { /* 0x2c59c0 */ }
void sub_2c5b30() { /* 0x2c5b30 */ }
void sub_2c5dc0() { /* 0x2c5dc0 */ }
void sub_2c5ef0() { /* 0x2c5ef0 */ }
void sub_2c6000() { /* 0x2c6000 */ }
void sub_2c6130() { /* 0x2c6130 */ }
void sub_2c62d0_subsdk0_2c62d0() { /* 0x2c62d0 */ }
void sub_2c6710() { /* 0x2c6710 */ }
void sub_2c6830() { /* 0x2c6830 */ }
void sub_2c69d0() { /* 0x2c69d0 */ }
void NVMMLITE_TVMRDEC_5() { /* 0x2c6e40 */ }
void NVMMLITE_TVMRDEC_6() { /* 0x2c6fd0 */ }
void Error_detected_0x_x() { /* 0x2c8030 */ }
void GetFeedbackInfoForMetadata() { /* 0x2c8160 */ }
void GetMotionVectorForMetadata() { /* 0x2c8290 */ }
void GetNewFrameBuffer() { /* 0x2c8560 */ }
void sub_2c8d40() { /* 0x2c8d40 */ }
void sub_2c90b0() { /* 0x2c90b0 */ }
void sub_2c95f0() { /* 0x2c95f0 */ }
void cbDisplayPicture() { /* 0x2c9830 */ }
void NVMMLITE_TVMRDEC_7() { /* 0x2cae00 */ }
// sub_2cb290: implemented in prog/matched/subsdk0/
void cbAllocPictureBuffer() { /* 0x2cb2a0 */ }
void VideoDFS_Mjolnir() { /* 0x2cc040 */ }
void sub_2cc2c0() { /* 0x2cc2c0 */ }
void VideoDFS_videoconf() { /* 0x2cc590 */ }
void NVMMLITE_TVMRDEC_8() { /* 0x2cc710 */ }
void sub_2cc9e0() { /* 0x2cc9e0 */ }
void cbCreateDecrypter() { /* 0x2cca00 */ }
void NVMMLITE_TVMRDEC_9() { /* 0x2ccb70 */ }
void sub_2ccde0() { /* 0x2ccde0 */ }
void NVMMLITE_TVMRDEC_10() { /* 0x2cce50 */ }
void NVMMLITE_TVMRDEC_11() { /* 0x2cd130 */ }
void NVMMLITE_TVMRDEC_12() { /* 0x2cd2f0 */ }
void cbGetDpbInfoForMetadata() { /* 0x2cd550 */ }
void sub_2cd8a0() { /* 0x2cd8a0 */ }
void TVMRBufferProcessing() { /* 0x2cda30 */ }
void TVMRStitchMvcViews() { /* 0x2cf9d0 */ }
void TVMRCombine_MVCViews() { /* 0x2cfd70 */ }
void TVMRConvertToPitchLinear() { /* 0x2cffb0 */ }
void TVMRVPRFloorSizeSettingThread() { /* 0x2d07f0 */ }
void TVMRFrameDelivery() { /* 0x2d0a40 */ }
void TVMRFrameStatusReporting() { /* 0x2d1010 */ }
void sub_2d12a0() { /* 0x2d12a0 */ }
void sub_2d1300() { /* 0x2d1300 */ }
void sub_2d1340() { /* 0x2d1340 */ }
void NvMMTVMRVPRFloorSizeThread() { /* 0x2d1880 */ }
void NvMMLiteTVMRDecDoWork() { /* 0x2d2b00 */ }
void sub_2d3600_subsdk0_2d3600() { /* 0x2d3600 */ }
void NvMMLiteTVMRDecGetBufferRequirements() { /* 0x2d3ab0 */ }
void NvMMLiteTVMRDecAbortBuffers() { /* 0x2d3eb0 */ }
void NvMMLiteTVMRDecSetAttribute() { /* 0x2d5020 */ }
void NvMMLiteTVMRDecGetAttribute() { /* 0x2d57d0 */ }
void sub_2d5c30_subsdk0_2d5c30() { /* 0x2d5c30 */ }
void NvMMLiteTVMRDecHwInit() { /* 0x2d5c40 */ }
void FrameNo() { /* 0x2d5da0 */ }
void FrameNo_2() { /* 0x2d5f40 */ }
void Frame_stats() { /* 0x2d6080 */ }
void sub_2d60e0_subsdk0_2d60e0() { /* 0x2d60e0 */ }
void sub_2d6140() { /* 0x2d6140 */ }
void sub_2d61a0() { /* 0x2d61a0 */ }
void sub_2d6200() { /* 0x2d6200 */ }
void sub_2d6260() { /* 0x2d6260 */ }
void NvMMLiteVideoEncBlockOpen() { /* 0x2d6280 */ }
void sub_2d7160() { /* 0x2d7160 */ }
void NvMMVideoEncOutputThread() { /* 0x2d7250 */ }
void NvMMLiteVideoEncBlockPrivateClose() { /* 0x2d7ab0 */ }
void NvMMLiteVideoEncGetBufferRequirements() { /* 0x2d8080 */ }
void sub_2d8310() { /* 0x2d8310 */ }
void sub_2d8320() { /* 0x2d8320 */ }
void NvVideoEncAbortBuffer() { /* 0x2d8330 */ }
void NvMMLiteVideoEncSetState() { /* 0x2d8ac0 */ }
void NvMMLiteVideoEncSetAttribute() { /* 0x2d8e00 */ }
void NvMMLiteVideoEncGetAttribute() { /* 0x2da690 */ }
void NvMMLiteVideoEncBlockClose() { /* 0x2da910 */ }
void sub_2dab80() { /* 0x2dab80 */ }
void ProcessTNRParams() { /* 0x2daee0 */ }
void NvBLSurfaceDownscaleThread() { /* 0x2db5c0 */ }
void SendInputAndSignalToNextStage_LookAhead() { /* 0x2dbb40 */ }
void VideoEncInputProcessing() { /* 0x2dc470 */ }
void VideoEndOutputDelivery() { /* 0x2dd1d0 */ }
void SendAbortSignalToNextStage() { /* 0x2dda80 */ }
void SendInputAndSignalToNextStage() { /* 0x2dde30 */ }
void sub_2de060() { /* 0x2de060 */ }
void sub_2de2a0() { /* 0x2de2a0 */ }
void sub_2de3a0() { /* 0x2de3a0 */ }
void sub_2de430_subsdk0_2de430() { /* 0x2de430 */ }
void sub_2de450() { /* 0x2de450 */ }
void sub_2de460() { /* 0x2de460 */ }
void sub_2de470() { /* 0x2de470 */ }
void sub_2de560() { /* 0x2de560 */ }
void sub_2de590() { /* 0x2de590 */ }
void sub_2de5e0_subsdk0_2de5e0() { /* 0x2de5e0 */ }
void sub_2de650() { /* 0x2de650 */ }
void sub_2de690() { /* 0x2de690 */ }
void sub_2deba0() { /* 0x2deba0 */ }
void sub_2defd0() { /* 0x2defd0 */ }
void sub_2df0d0() { /* 0x2df0d0 */ }
void sub_2df1d0() { /* 0x2df1d0 */ }
void sub_2df2d0() { /* 0x2df2d0 */ }
void sub_2df590() { /* 0x2df590 */ }
void sub_2df5c0() { /* 0x2df5c0 */ }
void sub_2df720_subsdk0_2df720() { /* 0x2df720 */ }
void sub_2df730() { /* 0x2df730 */ }
void sub_2df910() { /* 0x2df910 */ }
void sub_2dfa10() { /* 0x2dfa10 */ }
void sub_2dfb10() { /* 0x2dfb10 */ }
void sub_2dfb80() { /* 0x2dfb80 */ }
void sub_2dfdf0() { /* 0x2dfdf0 */ }
void sub_2dfe90() { /* 0x2dfe90 */ }
void sub_2dfea0() { /* 0x2dfea0 */ }
void sub_2dfeb0_subsdk0_2dfeb0() { /* 0x2dfeb0 */ }
void sub_2e0450() { /* 0x2e0450 */ }
void sub_2e0510() { /* 0x2e0510 */ }
void gaps_framenum_allowed() { /* 0x2e05c0 */ }
void subframeStatFileName() { /* 0x2e1090 */ }
void QppRunVector8x8_2() { /* 0x2e2060 */ }
void tu_search_basedon_pusize() { /* 0x2e2280 */ }
void temporal_hint_pattern() { /* 0x2e4500 */ }
void second_chroma_qp_index() { /* 0x2e6240 */ }
void constrained_intra_pred_flag() { /* 0x2e7590 */ }
void pcm_loop_filter_disable_flag() { /* 0x2e7610 */ }
void slice_size() { /* 0x2e78e0 */ }
void limit_slice_top_boundary() { /* 0x2e79b0 */ }
void uniform_spacing_flag() { /* 0x2e7b10 */ }
void double_fn() { /* 0x2e7c40 */ }
void sub_2e8180_subsdk0_2e8180() { /* 0x2e8180 */ }
void sub_2e9840() { /* 0x2e9840 */ }
void sub_2e9900() { /* 0x2e9900 */ }
void sub_2e99c0() { /* 0x2e99c0 */ }
void sub_2e9a30_subsdk0_2e9a30() { /* 0x2e9a30 */ }
void sub_2e9a40() { /* 0x2e9a40 */ }
void sub_2e9a50_subsdk0_2e9a50() { /* 0x2e9a50 */ }
void s__05u() { /* 0x2e9f30 */ }
void sub_2eee40() { /* 0x2eee40 */ }
void sub_2ef7a0() { /* 0x2ef7a0 */ }
void sub_2ef900() { /* 0x2ef900 */ }
void sub_2f04e0() { /* 0x2f04e0 */ }
void sub_2f0550() { /* 0x2f0550 */ }
void sub_2f0900() { /* 0x2f0900 */ }
void sub_2f0a60_subsdk0_2f0a60() { /* 0x2f0a60 */ }
void sub_2f0ac0_subsdk0_2f0ac0() { /* 0x2f0ac0 */ }
void sub_2f0bc0_subsdk0_2f0bc0() { /* 0x2f0bc0 */ }
void sub_2f0c10_subsdk0_2f0c10() { /* 0x2f0c10 */ }
void sub_2f0c50_subsdk0_2f0c50() { /* 0x2f0c50 */ }
void sub_2f0d00_subsdk0_2f0d00() { /* 0x2f0d00 */ }
void sub_2f0e00_subsdk0_2f0e00() { /* 0x2f0e00 */ }
void sub_2f1440() { /* 0x2f1440 */ }
void sub_2f1520() { /* 0x2f1520 */ }
void sub_2f1570() { /* 0x2f1570 */ }
void sub_2f15c0() { /* 0x2f15c0 */ }
void sub_2f15e0() { /* 0x2f15e0 */ }
void sub_2f1640() { /* 0x2f1640 */ }
void sub_2f1680() { /* 0x2f1680 */ }
// sub_2f16e0: implemented in prog/matched/subsdk0/
void sub_2f16f0() { /* 0x2f16f0 */ }
void sub_2f1720() { /* 0x2f1720 */ }
void sub_2f1790() { /* 0x2f1790 */ }
void sub_2f1810() { /* 0x2f1810 */ }
void sub_2f1860() { /* 0x2f1860 */ }
void sub_2f18a0() { /* 0x2f18a0 */ }
void sub_2f18d0() { /* 0x2f18d0 */ }
void sub_2f18f0() { /* 0x2f18f0 */ }
void sub_2f1930() { /* 0x2f1930 */ }
void sub_2f1960() { /* 0x2f1960 */ }
void sub_2f1990() { /* 0x2f1990 */ }
// sub_2f1a10: implemented in prog/matched/subsdk0/
void sub_2f1a20() { /* 0x2f1a20 */ }
void sub_2f1ad0() { /* 0x2f1ad0 */ }
void sub_2f1c40() { /* 0x2f1c40 */ }
void sub_2f1cb0() { /* 0x2f1cb0 */ }
void sub_2f1d10() { /* 0x2f1d10 */ }
void sub_2f1d30() { /* 0x2f1d30 */ }
void sub_2f23d0() { /* 0x2f23d0 */ }
void sub_2f2420() { /* 0x2f2420 */ }
void sub_2f2600() { /* 0x2f2600 */ }
void sub_2f2720() { /* 0x2f2720 */ }
void sub_2f2740() { /* 0x2f2740 */ }
void sub_2f2850() { /* 0x2f2850 */ }
void sub_2f2870() { /* 0x2f2870 */ }
void sub_2f3820() { /* 0x2f3820 */ }
void sub_2f56b0() { /* 0x2f56b0 */ }
void sub_2f6060() { /* 0x2f6060 */ }
void sub_2f8380() { /* 0x2f8380 */ }
void sub_2f94e0() { /* 0x2f94e0 */ }
void sub_2f99e0() { /* 0x2f99e0 */ }
void sub_2faa40() { /* 0x2faa40 */ }
void sub_2fd820() { /* 0x2fd820 */ }
void sub_2fd850() { /* 0x2fd850 */ }
void sub_2fdb90() { /* 0x2fdb90 */ }
void sub_2fddb0() { /* 0x2fddb0 */ }
void sub_2fe1e0() { /* 0x2fe1e0 */ }
void sub_2fe640() { /* 0x2fe640 */ }
void sub_2fe8e0() { /* 0x2fe8e0 */ }
void sub_2fedd0_subsdk0_2fedd0() { /* 0x2fedd0 */ }
void sub_2ff370() { /* 0x2ff370 */ }
void sub_2fff30() { /* 0x2fff30 */ }
void sub_3000e0() { /* 0x3000e0 */ }
void sub_300410_subsdk0_300410() { /* 0x300410 */ }
void sub_300520() { /* 0x300520 */ }
void sub_300c20() { /* 0x300c20 */ }
void sub_300d60() { /* 0x300d60 */ }
void sub_300dc0() { /* 0x300dc0 */ }
void sub_300e10() { /* 0x300e10 */ }
void sub_3010e0() { /* 0x3010e0 */ }
void sub_3011b0_subsdk0_3011b0() { /* 0x3011b0 */ }
void sub_3014c0() { /* 0x3014c0 */ }
void sub_301810() { /* 0x301810 */ }
void sub_3019a0() { /* 0x3019a0 */ }
void sub_3024c0() { /* 0x3024c0 */ }
void sub_3026d0() { /* 0x3026d0 */ }
void sub_3030b0() { /* 0x3030b0 */ }
void sub_303370() { /* 0x303370 */ }
void sub_303480() { /* 0x303480 */ }
void sub_303590() { /* 0x303590 */ }
void sub_303630_subsdk0_303630() { /* 0x303630 */ }
void sub_3036f0() { /* 0x3036f0 */ }
void sub_303720() { /* 0x303720 */ }
void sub_303b30() { /* 0x303b30 */ }
void sub_303b70() { /* 0x303b70 */ }
void sub_303be0() { /* 0x303be0 */ }
void sub_303e70() { /* 0x303e70 */ }
void sub_3041d0() { /* 0x3041d0 */ }
void sub_3042c0() { /* 0x3042c0 */ }
void sub_3042e0_subsdk0_3042e0() { /* 0x3042e0 */ }
void firstpass() { /* 0x3043d0 */ }
void sub_305010_subsdk0_305010() { /* 0x305010 */ }
void sub_305030() { /* 0x305030 */ }
void sub_3050b0() { /* 0x3050b0 */ }
void sub_305110() { /* 0x305110 */ }
void sub_305150() { /* 0x305150 */ }
void sub_305190() { /* 0x305190 */ }
void sub_305270() { /* 0x305270 */ }
// sub_3052f0: implemented in prog/matched/subsdk0/
void sub_305300_subsdk0_305300() { /* 0x305300 */ }
void sub_305340_subsdk0_305340() { /* 0x305340 */ }
void sub_3053f0() { /* 0x3053f0 */ }
void sub_305410_subsdk0_305410() { /* 0x305410 */ }
void sub_3058f0() { /* 0x3058f0 */ }
void sub_305f70() { /* 0x305f70 */ }
void sub_305fc0() { /* 0x305fc0 */ }
void sub_306010() { /* 0x306010 */ }
void sub_306050() { /* 0x306050 */ }
void secondpass() { /* 0x306090 */ }
void venc_hqmode() { /* 0x308630 */ }
void sub_30ca50() { /* 0x30ca50 */ }
void s__05u_2() { /* 0x30d460 */ }
void sub_30d610_subsdk0_30d610() { /* 0x30d610 */ }
void sub_30d6f0() { /* 0x30d6f0 */ }
void sub_30d760() { /* 0x30d760 */ }
void sub_30d880_subsdk0_30d880() { /* 0x30d880 */ }
void sub_30d8b0_subsdk0_30d8b0() { /* 0x30d8b0 */ }
void sub_30d910_subsdk0_30d910() { /* 0x30d910 */ }
void sub_30d940() { /* 0x30d940 */ }
void sub_30d970_subsdk0_30d970() { /* 0x30d970 */ }
void sub_30dd20() { /* 0x30dd20 */ }
void sub_30e170() { /* 0x30e170 */ }
void sub_30e2a0() { /* 0x30e2a0 */ }
void sub_30e570() { /* 0x30e570 */ }
void sub_30e990_subsdk0_30e990() { /* 0x30e990 */ }
void sub_30ed50_subsdk0_30ed50() { /* 0x30ed50 */ }
void sub_30ef50() { /* 0x30ef50 */ }
void sub_30f5f0() { /* 0x30f5f0 */ }
void sub_30fbe0() { /* 0x30fbe0 */ }
void sub_30fe50_subsdk0_30fe50() { /* 0x30fe50 */ }
void sub_30ff60() { /* 0x30ff60 */ }
void sub_310ad0() { /* 0x310ad0 */ }
void sub_3133e0_subsdk0_3133e0() { /* 0x3133e0 */ }
void s__05d() { /* 0x313630 */ }
void slice_tc_offset_div2() { /* 0x3143c0 */ }
void sub_314b20() { /* 0x314b20 */ }
void sub_314dd0() { /* 0x314dd0 */ }
void sub_3155d0_subsdk0_3155d0() { /* 0x3155d0 */ }
void sub_315820() { /* 0x315820 */ }
void sub_316080_subsdk0_316080() { /* 0x316080 */ }
void sub_316960() { /* 0x316960 */ }
void sub_316e50() { /* 0x316e50 */ }
void sub_317540() { /* 0x317540 */ }
void sub_3175a0() { /* 0x3175a0 */ }
void sub_3181a0() { /* 0x3181a0 */ }
void sub_3184d0_subsdk0_3184d0() { /* 0x3184d0 */ }
void sub_318570() { /* 0x318570 */ }
void sub_318640() { /* 0x318640 */ }
void sub_318850() { /* 0x318850 */ }
void sub_318a30() { /* 0x318a30 */ }
void sub_318d10_subsdk0_318d10() { /* 0x318d10 */ }
// sub_318fc0_subsdk0_318fc0: implemented in prog/matched/subsdk0/
void sub_318fd0_subsdk0_318fd0() { /* 0x318fd0 */ }
void sub_319150_subsdk0_319150() { /* 0x319150 */ }
void sub_3191f0() { /* 0x3191f0 */ }
void sub_319470_subsdk0_319470() { /* 0x319470 */ }
void sub_319630_subsdk0_319630() { /* 0x319630 */ }
void sub_319a70() { /* 0x319a70 */ }
void sub_31aa00() { /* 0x31aa00 */ }
void sub_31abc0_subsdk0_31abc0() { /* 0x31abc0 */ }
// sub_31cc70: implemented in prog/matched/subsdk0/
void sub_31cc80_subsdk0_31cc80() { /* 0x31cc80 */ }
void sub_31d0f0() { /* 0x31d0f0 */ }
void sub_31d150() { /* 0x31d150 */ }
void sub_320290() { /* 0x320290 */ }
void sub_320a40() { /* 0x320a40 */ }
void sub_321100() { /* 0x321100 */ }
void sub_3238d0() { /* 0x3238d0 */ }
void sub_324430() { /* 0x324430 */ }
void sub_324760_subsdk0_324760() { /* 0x324760 */ }
void sub_3248a0() { /* 0x3248a0 */ }
void sub_324c70() { /* 0x324c70 */ }
void sub_324d60() { /* 0x324d60 */ }
void sub_324e60() { /* 0x324e60 */ }
void sub_325090() { /* 0x325090 */ }
void sub_325560() { /* 0x325560 */ }
void sub_325ac0_subsdk0_325ac0() { /* 0x325ac0 */ }
void sub_325cf0() { /* 0x325cf0 */ }
void sub_325f20() { /* 0x325f20 */ }
void sub_326330() { /* 0x326330 */ }
void sub_3264c0() { /* 0x3264c0 */ }
void sub_326580() { /* 0x326580 */ }
void sub_327dd0_subsdk0_327dd0() { /* 0x327dd0 */ }
void sub_3281c0() { /* 0x3281c0 */ }
void tvmr_enablehdr10() { /* 0x3283e0 */ }
void sub_32fb50() { /* 0x32fb50 */ }
void sub_32fda0() { /* 0x32fda0 */ }
void sub_32fdd0_subsdk0_32fdd0() { /* 0x32fdd0 */ }
void sub_32fe80() { /* 0x32fe80 */ }
void sub_330100() { /* 0x330100 */ }
void sub_330520_subsdk0_330520() { /* 0x330520 */ }
void sub_330670() { /* 0x330670 */ }
void sub_330700() { /* 0x330700 */ }
void sub_330970() { /* 0x330970 */ }
void sub_330e60() { /* 0x330e60 */ }
void sub_3313c0() { /* 0x3313c0 */ }
void sub_331500() { /* 0x331500 */ }
void sub_3354f0() { /* 0x3354f0 */ }
void sub_335c60() { /* 0x335c60 */ }
void sub_335f10() { /* 0x335f10 */ }
void sub_336220() { /* 0x336220 */ }
void sub_336400() { /* 0x336400 */ }
void sub_336480() { /* 0x336480 */ }
void sub_3364b0() { /* 0x3364b0 */ }
void sub_3367e0() { /* 0x3367e0 */ }
void sub_336990() { /* 0x336990 */ }
void sub_336af0() { /* 0x336af0 */ }
void sub_336f70() { /* 0x336f70 */ }
void sub_3371a0() { /* 0x3371a0 */ }
void sub_337a80() { /* 0x337a80 */ }
// sub_337b00: implemented in prog/matched/subsdk0/
void sub_337b10() { /* 0x337b10 */ }
void sub_337bd0() { /* 0x337bd0 */ }
void sub_337c20() { /* 0x337c20 */ }
void sub_337c70() { /* 0x337c70 */ }
void sub_337fa0() { /* 0x337fa0 */ }
void sub_338010() { /* 0x338010 */ }
void sub_338060() { /* 0x338060 */ }
void sub_3382b0() { /* 0x3382b0 */ }
void sub_338460() { /* 0x338460 */ }
void sub_338520_subsdk0_338520() { /* 0x338520 */ }
void sub_338540() { /* 0x338540 */ }
void sub_338560_subsdk0_338560() { /* 0x338560 */ }
// sub_338580: implemented in prog/matched/subsdk0/
void sub_338590() { /* 0x338590 */ }
void sub_3387e0_subsdk0_3387e0() { /* 0x3387e0 */ }
void sub_3387f0() { /* 0x3387f0 */ }
void sub_338860() { /* 0x338860 */ }
void sub_3388e0() { /* 0x3388e0 */ }
// sub_338a80: implemented in prog/matched/subsdk0/
void sub_338a90_subsdk0_338a90() { /* 0x338a90 */ }
// sub_338ce0: implemented in prog/matched/subsdk0/
void sub_338cf0_subsdk0_338cf0() { /* 0x338cf0 */ }
void sub_338de0() { /* 0x338de0 */ }
void sub_339010() { /* 0x339010 */ }
void sub_339020() { /* 0x339020 */ }
void sub_339030() { /* 0x339030 */ }
void sub_3391f0() { /* 0x3391f0 */ }
void sub_3393e0() { /* 0x3393e0 */ }
// sub_339850: implemented in prog/matched/subsdk0/
void ERROR_not_supported() { /* 0x339860 */ }
void sub_33ad60_subsdk0_33ad60() { /* 0x33ad60 */ }
void sub_33af30() { /* 0x33af30 */ }
void sub_33b3c0() { /* 0x33b3c0 */ }
// sub_33b470: implemented in prog/matched/subsdk0/
void sub_33b480() { /* 0x33b480 */ }
void sub_33b5d0() { /* 0x33b5d0 */ }
void sub_33b860() { /* 0x33b860 */ }
void sub_33ba60() { /* 0x33ba60 */ }
void sub_33ba80() { /* 0x33ba80 */ }
void sub_33c360() { /* 0x33c360 */ }
void sub_33c450() { /* 0x33c450 */ }
void sub_33c520() { /* 0x33c520 */ }
void sub_33c650() { /* 0x33c650 */ }
void sub_33c6c0() { /* 0x33c6c0 */ }
void sub_33c7b0_subsdk0_33c7b0() { /* 0x33c7b0 */ }
// sub_33c7c0: implemented in prog/matched/subsdk0/
void sub_33c7d0() { /* 0x33c7d0 */ }
void sub_33cb10() { /* 0x33cb10 */ }
void sub_33d000_subsdk0_33d000() { /* 0x33d000 */ }
void sub_33d150_subsdk0_33d150() { /* 0x33d150 */ }
void sub_33da20() { /* 0x33da20 */ }
void sub_33dc40_subsdk0_33dc40() { /* 0x33dc40 */ }
void sub_33dcf0() { /* 0x33dcf0 */ }
void sub_33dd90() { /* 0x33dd90 */ }
void sub_33df10_subsdk0_33df10() { /* 0x33df10 */ }
// sub_33df40: implemented in prog/matched/subsdk0/
void sub_33df50() { /* 0x33df50 */ }
void sub_33e2d0_subsdk0_33e2d0() { /* 0x33e2d0 */ }
void sub_33eae0() { /* 0x33eae0 */ }
void sub_3420c0_subsdk0_3420c0() { /* 0x3420c0 */ }
void sub_342560_subsdk0_342560() { /* 0x342560 */ }
void sub_342670() { /* 0x342670 */ }
void sub_342a90() { /* 0x342a90 */ }
void sub_344730() { /* 0x344730 */ }
void sub_3448c0() { /* 0x3448c0 */ }
void sub_3449f0() { /* 0x3449f0 */ }
void sub_345300() { /* 0x345300 */ }
void sub_345460() { /* 0x345460 */ }
void sub_345810() { /* 0x345810 */ }
void sub_345e30() { /* 0x345e30 */ }
void sub_3460c0() { /* 0x3460c0 */ }
void sub_3465b0() { /* 0x3465b0 */ }
void sub_346a30() { /* 0x346a30 */ }
void sub_346d40_subsdk0_346d40() { /* 0x346d40 */ }
void sub_3470b0_subsdk0_3470b0() { /* 0x3470b0 */ }
void sub_347460() { /* 0x347460 */ }
void sub_347750() { /* 0x347750 */ }
void sub_347fe0_subsdk0_347fe0() { /* 0x347fe0 */ }
void sub_3480b0() { /* 0x3480b0 */ }
void sub_3482e0_subsdk0_3482e0() { /* 0x3482e0 */ }
void sub_348430_subsdk0_348430() { /* 0x348430 */ }
void sub_348810_subsdk0_348810() { /* 0x348810 */ }
void sub_3488e0() { /* 0x3488e0 */ }
// sub_3489a0_subsdk0_3489a0: implemented in prog/matched/subsdk0/
// sub_3489b0: implemented in prog/matched/subsdk0/
// sub_3489c0: implemented in prog/matched/subsdk0/
void sub_3489d0() { /* 0x3489d0 */ }
// sub_348a70: implemented in prog/matched/subsdk0/
// sub_348a80: implemented in prog/matched/subsdk0/
// sub_348a90_subsdk0_348a90: implemented in prog/matched/subsdk0/
// sub_348aa0: implemented in prog/matched/subsdk0/
void sub_348ab0_subsdk0_348ab0() { /* 0x348ab0 */ }
// sub_348ad0: implemented in prog/matched/subsdk0/
// sub_348ae0_subsdk0_348ae0: implemented in prog/matched/subsdk0/
// sub_348af0: implemented in prog/matched/subsdk0/
void sub_348b00() { /* 0x348b00 */ }
void sub_348c20_subsdk0_348c20() { /* 0x348c20 */ }
void sub_348c30() { /* 0x348c30 */ }
void sub_348c50() { /* 0x348c50 */ }
void sub_348e50() { /* 0x348e50 */ }
void sub_348e60_subsdk0_348e60() { /* 0x348e60 */ }
void sub_348ec0() { /* 0x348ec0 */ }
void sub_349010() { /* 0x349010 */ }
void sub_34a190() { /* 0x34a190 */ }
void sub_34a2a0() { /* 0x34a2a0 */ }
void sub_34a2f0() { /* 0x34a2f0 */ }
void sub_34a350_subsdk0_34a350() { /* 0x34a350 */ }
void sub_34a370() { /* 0x34a370 */ }
void sub_34a610() { /* 0x34a610 */ }
void sub_34a670_subsdk0_34a670() { /* 0x34a670 */ }
void sub_34a890() { /* 0x34a890 */ }
void sub_34a8a0() { /* 0x34a8a0 */ }
void sub_34a8d0() { /* 0x34a8d0 */ }
void sub_34a8f0() { /* 0x34a8f0 */ }
void sub_34a930() { /* 0x34a930 */ }
void sub_34a940() { /* 0x34a940 */ }
void sub_34aa50_subsdk0_34aa50() { /* 0x34aa50 */ }
void sub_34aa70() { /* 0x34aa70 */ }
void sub_34aba0() { /* 0x34aba0 */ }
void sub_34acb0() { /* 0x34acb0 */ }
void sub_34ade0() { /* 0x34ade0 */ }
void sub_34ae10() { /* 0x34ae10 */ }
void sub_34af00() { /* 0x34af00 */ }
void sub_34af30_subsdk0_34af30() { /* 0x34af30 */ }
void sub_34aff0() { /* 0x34aff0 */ }
void sub_34b010_subsdk0_34b010() { /* 0x34b010 */ }
void sub_34b050() { /* 0x34b050 */ }
void sub_34b090_subsdk0_34b090() { /* 0x34b090 */ }
// sub_34b0d0: implemented in prog/matched/subsdk0/
// sub_34b0e0: implemented in prog/matched/subsdk0/
void sub_34b0f0() { /* 0x34b0f0 */ }
void sub_34b270_subsdk0_34b270() { /* 0x34b270 */ }
void sub_34b2b0() { /* 0x34b2b0 */ }
// sub_34b330: implemented in prog/matched/subsdk0/
void sub_34b340() { /* 0x34b340 */ }
// sub_34b360_subsdk0_34b360: implemented in prog/matched/subsdk0/
// sub_34b370: implemented in prog/matched/subsdk0/
// sub_34b380_subsdk0_34b380: implemented in prog/matched/subsdk0/
// sub_34b390: implemented in prog/matched/subsdk0/
// sub_34b3a0: implemented in prog/matched/subsdk0/
void sub_34b3b0() { /* 0x34b3b0 */ }
void sub_34b3f0() { /* 0x34b3f0 */ }
void sub_34b490() { /* 0x34b490 */ }
void Profilestats() { /* 0x34b7d0 */ }
void d_d_d_lld_f_f() { /* 0x34b820 */ }
void d_d_d_6() { /* 0x34b860 */ }
void sub_34b8e0() { /* 0x34b8e0 */ }
void sub_34b9f0() { /* 0x34b9f0 */ }
void sub_34bac0_subsdk0_34bac0() { /* 0x34bac0 */ }
// sub_34bf60: implemented in prog/matched/subsdk0/
void sub_34bf70() { /* 0x34bf70 */ }
void sub_34e270() { /* 0x34e270 */ }
void sub_34e350_subsdk0_34e350() { /* 0x34e350 */ }
void sub_34e4e0_subsdk0_34e4e0() { /* 0x34e4e0 */ }
void sub_34e5f0() { /* 0x34e5f0 */ }
void sub_34ecd0() { /* 0x34ecd0 */ }
void sub_34f300() { /* 0x34f300 */ }
void sub_3529d0() { /* 0x3529d0 */ }
void sub_352af0() { /* 0x352af0 */ }
void sub_352d10() { /* 0x352d10 */ }
void sub_352dd0() { /* 0x352dd0 */ }
void sub_352e50() { /* 0x352e50 */ }
void sub_353170() { /* 0x353170 */ }
void sub_3539c0() { /* 0x3539c0 */ }
void sub_353aa0() { /* 0x353aa0 */ }
void sub_353b90() { /* 0x353b90 */ }
void sub_353c70_subsdk0_353c70() { /* 0x353c70 */ }
void sub_353db0() { /* 0x353db0 */ }
void sub_353ef0() { /* 0x353ef0 */ }
void sub_3554b0() { /* 0x3554b0 */ }
void sub_355580() { /* 0x355580 */ }
void sub_355620() { /* 0x355620 */ }
void sub_3557e0_subsdk0_3557e0() { /* 0x3557e0 */ }
void sub_355810() { /* 0x355810 */ }
void sub_355ab0_subsdk0_355ab0() { /* 0x355ab0 */ }
void sub_356390() { /* 0x356390 */ }
void sub_3568d0() { /* 0x3568d0 */ }
void sub_356e10() { /* 0x356e10 */ }
void sub_356ef0() { /* 0x356ef0 */ }
void sub_357160() { /* 0x357160 */ }
void sub_357a60_subsdk0_357a60() { /* 0x357a60 */ }
void sub_358620() { /* 0x358620 */ }
void sub_358830() { /* 0x358830 */ }
void sub_358910() { /* 0x358910 */ }
void sub_3589b0() { /* 0x3589b0 */ }
void sub_358a60() { /* 0x358a60 */ }
void sub_359ff0() { /* 0x359ff0 */ }
void sub_35a140() { /* 0x35a140 */ }
void sub_35a210() { /* 0x35a210 */ }
void sub_35a330() { /* 0x35a330 */ }
void sub_35a400() { /* 0x35a400 */ }
void sub_35a920() { /* 0x35a920 */ }
void sub_35b940() { /* 0x35b940 */ }
void sub_35b9a0() { /* 0x35b9a0 */ }
void sub_35ba90_subsdk0_35ba90() { /* 0x35ba90 */ }
// sub_35baa0: implemented in prog/matched/subsdk0/
// sub_35bab0: implemented in prog/matched/subsdk0/
// sub_35bac0_subsdk0_35bac0: implemented in prog/matched/subsdk0/
// sub_35bad0: implemented in prog/matched/subsdk0/
// sub_35bae0: implemented in prog/matched/subsdk0/
// sub_35baf0: implemented in prog/matched/subsdk0/
// sub_35bb00: implemented in prog/matched/subsdk0/
// sub_35bb10: implemented in prog/matched/subsdk0/
// sub_35bb20_subsdk0_35bb20: implemented in prog/matched/subsdk0/
// sub_35bb30: implemented in prog/matched/subsdk0/
// sub_35bb40: implemented in prog/matched/subsdk0/
// sub_35bb50: implemented in prog/matched/subsdk0/
// sub_35bb60: implemented in prog/matched/subsdk0/
// sub_35bb70: implemented in prog/matched/subsdk0/
// sub_35bb80: implemented in prog/matched/subsdk0/
// sub_35bb90_subsdk0_35bb90: implemented in prog/matched/subsdk0/
// sub_35bba0_subsdk0_35bba0: implemented in prog/matched/subsdk0/
// sub_35bbb0: implemented in prog/matched/subsdk0/
// sub_35bbc0: implemented in prog/matched/subsdk0/
void sub_35bbd0() { /* 0x35bbd0 */ }
void sub_35bbe0() { /* 0x35bbe0 */ }
void sub_35bbf0() { /* 0x35bbf0 */ }
void sub_35bc00() { /* 0x35bc00 */ }
void sub_35bc10() { /* 0x35bc10 */ }
void sub_35bc20_subsdk0_35bc20() { /* 0x35bc20 */ }
void sub_35bc40_subsdk0_35bc40() { /* 0x35bc40 */ }
void sub_35bc60() { /* 0x35bc60 */ }
void sub_35bc80() { /* 0x35bc80 */ }
// sub_35bc90: implemented in prog/matched/subsdk0/
void sub_35bca0() { /* 0x35bca0 */ }
void sub_35bcd0_subsdk0_35bcd0() { /* 0x35bcd0 */ }
void sub_35bd00() { /* 0x35bd00 */ }
void sub_35bd30() { /* 0x35bd30 */ }
void sub_35bd60() { /* 0x35bd60 */ }
void sub_35bd90() { /* 0x35bd90 */ }
void sub_35bdc0() { /* 0x35bdc0 */ }
void sub_35c030() { /* 0x35c030 */ }
void sub_35c9a0() { /* 0x35c9a0 */ }
void sub_35ce50() { /* 0x35ce50 */ }
void sub_35ce80() { /* 0x35ce80 */ }
void sub_35d2f0() { /* 0x35d2f0 */ }
void sub_35d390() { /* 0x35d390 */ }
void sub_35d3c0_subsdk0_35d3c0() { /* 0x35d3c0 */ }
void sub_35d3e0_subsdk0_35d3e0() { /* 0x35d3e0 */ }
void sub_35d410_subsdk0_35d410() { /* 0x35d410 */ }
void sub_35d450() { /* 0x35d450 */ }
void sub_35d4a0() { /* 0x35d4a0 */ }
void sub_35d4d0_subsdk0_35d4d0() { /* 0x35d4d0 */ }
void sub_35d990() { /* 0x35d990 */ }
void sub_35dc10() { /* 0x35dc10 */ }
// sub_35df90: implemented in prog/matched/subsdk0/
// sub_35dfa0: implemented in prog/matched/subsdk0/
void sub_35dfb0() { /* 0x35dfb0 */ }
void sub_35e040() { /* 0x35e040 */ }
void sub_35e060() { /* 0x35e060 */ }
void sub_35e090() { /* 0x35e090 */ }
void sub_35e0b0() { /* 0x35e0b0 */ }
void sub_35e0f0() { /* 0x35e0f0 */ }
void sub_35e140() { /* 0x35e140 */ }
void sub_35e170() { /* 0x35e170 */ }
void sub_35e1c0() { /* 0x35e1c0 */ }
void sub_35e260() { /* 0x35e260 */ }
void sub_35e3e0() { /* 0x35e3e0 */ }
void sub_35e860() { /* 0x35e860 */ }
void sub_35efa0() { /* 0x35efa0 */ }
void sub_35f220() { /* 0x35f220 */ }
void sub_35f790_subsdk0_35f790() { /* 0x35f790 */ }
void sub_35f810() { /* 0x35f810 */ }
void sub_35fb90() { /* 0x35fb90 */ }
void sub_35fdd0_subsdk0_35fdd0() { /* 0x35fdd0 */ }
void sub_35fe00_subsdk0_35fe00() { /* 0x35fe00 */ }
void sub_35fe60() { /* 0x35fe60 */ }
void sub_35ff60_subsdk0_35ff60() { /* 0x35ff60 */ }
void sub_35fff0() { /* 0x35fff0 */ }
void sub_360120() { /* 0x360120 */ }
void sub_3607d0_subsdk0_3607d0() { /* 0x3607d0 */ }
void sub_360c50() { /* 0x360c50 */ }
void sub_360fd0() { /* 0x360fd0 */ }
void sub_361110() { /* 0x361110 */ }
void sub_361350_subsdk0_361350() { /* 0x361350 */ }
void sub_361390() { /* 0x361390 */ }
void sub_361680() { /* 0x361680 */ }
void sub_3619d0() { /* 0x3619d0 */ }
void sub_3623c0() { /* 0x3623c0 */ }
void sub_362e40() { /* 0x362e40 */ }
void sub_364130() { /* 0x364130 */ }

}  // namespace subsdk0
