/* sdk.audio - 1 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "audio_audio_sdk.h"

namespace audio {
void AudioUsbDeviceOutput_sdk_96ac0() { /* 0x96ac0 */ }

}  // namespace audio
