/* main.audio - 4 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "audio_audio_main.h"

namespace audio {
void AudioUsbDeviceOutput() { /* 0x5650 */ }
void MovieAudioInputReadThread() { /* 0x663ee0 */ }
void MovieAudioOutputHandlerThread() { /* 0x664fd0 */ }
void SoundWait() { /* 0x13ab400 */ }

}  // namespace audio
