/* subsdk0.audio - 58 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "audio_audio_subsdk0.h"

namespace audio {
void AudioCallback() { /* 0x19e0 */ }
void MovieNnCodecAudioOutputReceiver() { /* 0x124f0 */ }
void MovieAudioRendererThread() { /* 0x12d10 */ }
void NnAudioEncoderLooper() { /* 0x21130 */ }
void AudioSampleTable() { /* 0x275e0 */ }
void audio_decoder() { /* 0x28f10 */ }
void audio_encoder() { /* 0x79720 */ }
void AudioParameter() { /* 0x108bd0 */ }
void AudioRecord() { /* 0x1095b0 */ }
void AudioRecord_2() { /* 0x10ad40 */ }
void AudioRecord_3() { /* 0x10b530 */ }
void AudioSystem() { /* 0x10b960 */ }
void AudioSystem_2() { /* 0x10d350 */ }
void AudioTrack() { /* 0x111670 */ }
void AudioTrack_2() { /* 0x1140e0 */ }
void AudioTrack_3() { /* 0x114870 */ }
void AudioTrack_dump() { /* 0x114b10 */ }
void AudioTrack_4() { /* 0x114f80 */ }
void AudioTrackShared() { /* 0x1156f0 */ }
void AudioTrackShared_2() { /* 0x115ba0 */ }
void AudioTrackShared_3() { /* 0x115e20 */ }
void AudioTrackShared_4() { /* 0x115fb0 */ }
void AudioTrackShared_5() { /* 0x1160b0 */ }
void AudioTrackShared_6() { /* 0x1162a0 */ }
void AudioTrackShared_7() { /* 0x1163e0 */ }
void AudioTrackShared_8() { /* 0x1165d0 */ }
void AudioTrackShared_9() { /* 0x1166f0 */ }
void IAudioFlinger() { /* 0x116c50 */ }
void android_media_IAudioFlinger() { /* 0x11abe0 */ }
void android_media_IAudioFlingerClient() { /* 0x11b2d0 */ }
void android_media_IAudioPolicyServiceClient() { /* 0x11b980 */ }
void ARawAudioAssembler() { /* 0x12e8c0 */ }
void ARawAudioAssembler_2() { /* 0x12e9e0 */ }
void AMPEG4AudioAssembler() { /* 0x131160 */ }
void AMPEG4AudioAssembler_2() { /* 0x1316c0 */ }
void AMPEG4AudioAssembler_3() { /* 0x132680 */ }
void AMPEG4AudioAssembler_4() { /* 0x1328d0 */ }
void AMPEG4AudioAssembler_5() { /* 0x132a80 */ }
void AudioPlayer() { /* 0x1c75b0 */ }
void AudioPlayer_2() { /* 0x1c7850 */ }
void AudioPlayer_3() { /* 0x1c78f0 */ }
void AudioPlayer_4() { /* 0x1c7e50 */ }
void AudioPlayer_5() { /* 0x1c7f00 */ }
void AudioPlayer_6() { /* 0x1c8120 */ }
void AudioPlayer_7() { /* 0x1c8830 */ }
void AudioSource() { /* 0x1c8c80 */ }
void AudioSource_2() { /* 0x1c8ea0 */ }
void AudioSource_3() { /* 0x1c97c0 */ }
void AudioSource_4() { /* 0x1c9bf0 */ }
void SoundHandle() { /* 0x203580 */ }
void audio_decoder_vorbis() { /* 0x20e190 */ }
void audio_decoder_2() { /* 0x20ef20 */ }
void audio_reader_binary() { /* 0x27c1a0 */ }
void audio_writer_binary() { /* 0x27ca40 */ }
void audio_decoder_3() { /* 0x293210 */ }
void audio_decoder_4() { /* 0x293440 */ }
void audio_decoder_x_eac3() { /* 0x293490 */ }
void audio_decoder_5() { /* 0x2936e0 */ }

}  // namespace audio
