/* subsdk0.field - 2 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "field_field_subsdk0.h"

namespace field {
void Deinterlace1stField() { /* 0x2c1860 */ }
void Deinterlace2ndField() { /* 0x2c1a90 */ }

}  // namespace field
