/* sdk.field - 1 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "field_field_sdk.h"

namespace field {
void SecondFieldOffset() { /* 0x3ccdf0 */ }

}  // namespace field
