/* main.field - 45 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "field_field_main.h"

namespace field {
void HeightField() { /* 0x111de0 */ }
void HeightFieldFlags() { /* 0x117640 */ }
void GuHeightField() { /* 0x14f3f0 */ }
void GuHeightField_2() { /* 0x14f480 */ }
// PxHeightField: implemented in prog/matched/main/
void PxHeightField_2() { /* 0x150250 */ }
void ShadowHeightFieldGeometry() { /* 0x1d3760 */ }
void PxHeightFieldGeometry() { /* 0x215dc0 */ }
void PxHeightField_3() { /* 0x218ae0 */ }
// PxHeightField_4: implemented in prog/matched/main/
void PxHeightFieldGeometry_2() { /* 0x22dc10 */ }
void PxHeightField_5() { /* 0x231500 */ }
void PxHeightFieldGeometry_3() { /* 0x2542e0 */ }
void PxHeightFieldGeometry_4() { /* 0x25b7c0 */ }
void PxHeightFieldGeometry_5() { /* 0x263230 */ }
void GPUDepthOfField() { /* 0x4a79e0 */ }
void GPUDepthOfField_2() { /* 0x4a7f60 */ }
void GPUDepthOfField_cpp_d_PPFX_ERROR() { /* 0x4aa0d0 */ }
void GPUDepthOfField_cpp_d_PPFX_ERROR_2() { /* 0x4aa860 */ }
void GPUDepthOfField_cpp_d_PPFX_ERROR_3() { /* 0x4ad3d0 */ }
void GPUDepthOfField_cpp_d_PPFX_WARNING() { /* 0x4b19a0 */ }
void GPUDepthOfField_cpp_d_PPFX_ERROR_4() { /* 0x4b6fc0 */ }
void Field_name_0_is_reserved() { /* 0x6ec450 */ }
void HasField() { /* 0x732f90 */ }
void ClearField() { /* 0x733c50 */ }
void Field_does_not_match_message_type() { /* 0x734cf0 */ }
void MapBegin() { /* 0x73bd00 */ }
void MapEnd() { /* 0x73be70 */ }
void MapSize() { /* 0x73bfe0 */ }
void isDepthOfField() { /* 0x9a8a80 */ }
void isOtherField() { /* 0x9aad20 */ }
void map_destination_data() { /* 0xc48140 */ }
void FieldObject__lu() { /* 0xc622f0 */ }
void map_door_trigger() { /* 0xc94420 */ }
void FieldMenuRotomView() { /* 0xe5e490 */ }
void FieldMenuView() { /* 0xe5ec40 */ }
void FieldMenuRotomView_2() { /* 0xe5fa80 */ }
void LiveCommViewField() { /* 0xe70e30 */ }
void Set_Volume_m96_Field_Music() { /* 0xfbb430 */ }
void PokeListFieldState() { /* 0x12c3820 */ }
void CS_FieldPlacementSelectParamSet() { /* 0x13ab150 */ }
void CS_FieldPlacementSelectParamReset() { /* 0x13ab360 */ }
void map_destination_data_2() { /* 0x1443ed0 */ }
void sysEmitterFieldUniformBlock() { /* 0x17d5ed0 */ }
void sysEmitterFieldUniformBlock_2() { /* 0x17d63b0 */ }

}  // namespace field
