/* main.net - 55 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "net_net_main.h"

namespace net {
void SubmitNetworkRequest() { /* 0x6a2d10 */ }
void net_title_01_lyt() { /* 0x8d4800 */ }
void net_nest_hole_dai_encount() { /* 0xe3b3f0 */ }
void net_nest_hole_drop_rewards() { /* 0xe3b690 */ }
void net_nest_hole_bonus_rewards() { /* 0xe3b930 */ }
void net_nest_hole_normal_encount() { /* 0xe3bce0 */ }
void net_button() { /* 0xf23d80 */ }
void net_button_2() { /* 0xf26d60 */ }
void net_bg_00_lyt() { /* 0xfcc9b0 */ }
void net_title_00_lyt() { /* 0xfd0390 */ }
void nn_ldn_CreateNetwork() { /* 0x11e5390 */ }
void nn_ldn_CreateNetwork_2() { /* 0x11efc30 */ }
void StateOnlineCheck() { /* 0x1436f60 */ }
void LocalCreateNetworkJob_WaitCreateNetwork() { /* 0x1682740 */ }
void LdnBackgroundProcessJob_WaitCreateNetworkEvent() { /* 0x1682c00 */ }
void LdnBackgroundProcessJob_ScanNetwork() { /* 0x1683210 */ }
void LdnBackgroundProcessJob_WaitConnectNetworkEvent() { /* 0x1683870 */ }
void LdnBackgroundProcessJob_CreateNetworkPrivate() { /* 0x1683e00 */ }
void LdnBackgroundProcessJob_CreateNetworkPrivate_2() { /* 0x1683fc0 */ }
void LdnBackgroundProcessJob_WaitCreateNetworkEvent_2() { /* 0x16840d0 */ }
void LdnBackgroundProcessJob_ScanNetworkPrivate() { /* 0x1684360 */ }
void LdnBackgroundProcessJob_ConnectNetworkPrivate() { /* 0x1684750 */ }
void LdnBackgroundProcessJob_WaitConnectNetworkEvent_2() { /* 0x1684850 */ }
void LdnHostMigrationJob_ConnectNetwork() { /* 0x1684f50 */ }
void LdnHostMigrationJob_ConnectNetwork_2() { /* 0x1685360 */ }
void LdnScanNetworkJob_WaitScanNetwork() { /* 0x1685ae0 */ }
void LocalBackgroundProcessJob_DestroyNetwork() { /* 0x1687630 */ }
void LocalBackgroundProcessJob_DisconnectNetwork() { /* 0x1687880 */ }
void LocalBackgroundProcessJob_CreateNetwork() { /* 0x1687950 */ }
void LocalBackgroundProcessJob_ConnectNetwork() { /* 0x1687cf0 */ }
void LocalCreateNetworkJob_WaitCreateNetwork_2() { /* 0x16883c0 */ }
void LocalCreateNetworkJob_WaitForCancel() { /* 0x16884a0 */ }
void LocalForceDisconnectNetworkJob_WaitDisconnected() { /* 0x168a560 */ }
void LocalHostMigrationJob_DisconnectNetwork() { /* 0x168a950 */ }
void LocalHostMigrationJob_ScanNetwork() { /* 0x168b650 */ }
void LocalHostMigrationJob_ScanNetwork_2() { /* 0x168b920 */ }
void LocalMatchCreateSessionJob_CreateLocalNetwork() { /* 0x168f2c0 */ }
void LocalMatchCreateSessionJob_WaitCreateLocalNetwork() { /* 0x168f380 */ }
void LocalMatchCreateSessionJob_DestroyLocalNetwork() { /* 0x168f660 */ }
void LocalMatchDestroySessionJob_DestroyLocalNetwork() { /* 0x168fad0 */ }
void LocalConnectNetworkJob_WaitConnectNetwork() { /* 0x1697da0 */ }
void LocalConnectNetworkJob_WaitForCancel() { /* 0x1697ef0 */ }
void LocalConnectNetworkJob_WaitForCancel_2() { /* 0x16980f0 */ }
void LocalDestroyNetworkJob_TryPrepareDestroyNetwork() { /* 0x16982d0 */ }
void LocalDestroyNetworkJob_WaitForCancel() { /* 0x16983a0 */ }
void LocalDestroyNetworkJob_WaitForCancel_2() { /* 0x1698590 */ }
void LocalDestroyNetworkJob_WaitForCancel_3() { /* 0x1698670 */ }
void LocalDestroyNetworkJob_WaitDestroyNetwork() { /* 0x1698740 */ }
void LocalDestroyNetworkJob_WaitForCancel_4() { /* 0x1698810 */ }
void LocalDestroyNetworkJob_WaitForCancel_5() { /* 0x1698930 */ }
void LocalDisconnectNetworkJob_TryPrepareDisconnectNetwork() { /* 0x1698b70 */ }
void LocalDisconnectNetworkJob_WaitForCancel() { /* 0x1698c20 */ }
void LocalDisconnectNetworkJob_WaitForCancel_2() { /* 0x1698e10 */ }
void LocalScanNetworkJob_WaitScanNetwork() { /* 0x169a920 */ }
void LocalScanNetworkJob_WaitForCancel() { /* 0x169a9f0 */ }

}  // namespace net
