/* sdk.render - 1 recovered functions.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#include "render_render_sdk.h"

namespace render {
void Graphics_Device() { /* 0x3f0ec0 */ }

}  // namespace render
