#!/usr/bin/env python3
"""Emit the per-directory CMakeLists.txt files under prog/.

pokesword walks prog/ with add_subdirectory() per group and per subsystem, each
with its own source/ and include/ CMakeLists.txt feeding target_sources(). This
script regenerates that whole chain from whatever files exist on disk, so the
generated C++ tree is always buildable without hand editing.

Usage:
    python tools/prog_cmake.py
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROG = os.path.join(ROOT, "prog")

TARGET = "pokesword"

# Hand-maintained files that must survive regeneration, and the target the
# prog/ tree attaches to.
KEEP_HINTS = ("CMakeLists.txt",)


def sources_list(directory, exts):
    out = []
    for nm in sorted(os.listdir(directory)):
        p = os.path.join(directory, nm)
        if not os.path.isfile(p):
            continue
        if nm.endswith(exts):
            out.append(nm)
    return out


def write_list(directory, items, banner):
    body = ["# %s" % banner]
    if items:
        body.append("")
        body.append("target_sources(%s PRIVATE" % TARGET)
        for it in items:
            body.append("  %s" % it)
        body.append(")")
    else:
        body += ["", "# no sources at this level"]
    with open(os.path.join(directory, "CMakeLists.txt"), "w",
              encoding="utf-8") as f:
        f.write("\n".join(body) + "\n")


def process(directory):
    subdirs = sorted(nm for nm in os.listdir(directory)
                     if os.path.isdir(os.path.join(directory, nm)))
    made = []
    for sub in subdirs:
        spath = os.path.join(directory, sub)
        # A directory with children is an intermediate node: recurse and record
        # it so this level can add_subdirectory() it. Only a childless
        # directory is a leaf that owns sources directly.
        if any(os.path.isdir(os.path.join(spath, c)) for c in os.listdir(spath)):
            process(spath)
            made.append(sub)
        else:
            # Leaf owning sources directly.
            write_list(spath, sources_list(spath, (".cpp",)),
                       "prog/%s -- generated by tools/prog_cmake.py"
                       % os.path.relpath(spath, ROOT).replace("\\", "/"))
        # include/ trees are headers only: list them for the project so the
        # files are tracked by the build system, but never compile them.
        inc = os.path.join(spath, "include")
        if os.path.isdir(inc):
            hdrs = sources_list(inc, (".h", ".hpp"))
            if hdrs:
                body = ["# prog/%s -- generated by tools/prog_cmake.py"
                        % os.path.relpath(spath, ROOT).replace("\\", "/"),
                        "",
                        "target_sources(%s PRIVATE" % TARGET]
                body += ["  %s" % h for h in hdrs]
                body.append(")")
                with open(os.path.join(inc, "CMakeLists.txt"), "w",
                          encoding="utf-8") as f:
                    f.write("\n".join(body) + "\n")
    own = sources_list(directory, (".cpp",))
    name = os.path.relpath(directory, ROOT).replace("\\", "/")
    if made:
        body = ["# %s -- generated by tools/prog_cmake.py" % name, ""]
        body += ["add_subdirectory(%s)" % s for s in made]
        if own:
            body += ["", "target_sources(%s PRIVATE" % TARGET]
            body += ["  %s" % o for o in own]
            body.append(")")
        with open(os.path.join(directory, "CMakeLists.txt"), "w",
                  encoding="utf-8") as f:
            f.write("\n".join(body) + "\n")
    elif not own and any(os.path.isdir(os.path.join(directory, s))
                         for s in os.listdir(directory)):
        # Intermediate node with no sources of its own, e.g. the source/ and
        # include/ halves of a subsystem. Their children are already included,
        # so this file just records that there is nothing to add here.
        with open(os.path.join(directory, "CMakeLists.txt"), "w",
                  encoding="utf-8") as f:
            f.write("# %s -- generated by tools/prog_cmake.py\n"
                    "\n# sources live in the subdirectories; nothing to add here\n"
                    % name)
    else:
        write_list(directory, own,
                   "%s -- generated by tools/prog_cmake.py" % name)
    return made


def main():
    if not os.path.isdir(PROG):
        print("no prog/ directory")
        return 1
    process(PROG)
    total = sum(1 for _r, _d, fs in os.walk(PROG) for _f in fs)
    print("prog/ CMakeLists regenerated (%d files total)" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main())
