"""Regenerate README's <!-- STATUS --> block from tools/progress_json.py.

The block is generated output. Hand-editing it is what broke CI ten runs in a row:

    | **total** | **28942** | **152062** | **19.03%** |

was corrected by hand to the right total, while the four per-module rows above it
stayed at their old values. The workflow compares the whole block against
`python tools/progress_json.py --format markdown`, so a hand edit is invisible
locally -- `tools/audit.py` only checks the total row and the prose figures -- and
fails CI as "README status table is stale".

That is the second time this session a check passed locally and failed in CI, after
the loop committing in-flight work. Both are the same shape: the local gate checks
a *subset* of what CI checks, so green locally says less than it appears to.

Usage:
    python tools/refresh_status_block.py            # rewrite the block
    python tools/refresh_status_block.py --check    # exit 1 if stale
"""

import argparse
import io
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(ROOT, "README.md")
BEGIN = "<!-- STATUS:BEGIN"
END = "<!-- STATUS:END -->"


def generated():
    r = subprocess.run([sys.executable,
                        os.path.join(ROOT, "tools", "progress_json.py"),
                        "--format", "markdown"],
                       cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit("progress_json.py failed: %s" % (r.stderr[:200]))
    return r.stdout.strip()


def current(raw):
    m = re.search(r"<!-- STATUS:BEGIN.*?<!-- STATUS:END -->", raw, re.S)
    if not m:
        return None
    body = m.group(0).split("-->", 1)[1]
    return body.rsplit(END, 1)[0].strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the block is stale, without writing")
    a = ap.parse_args()

    raw = io.open(README, encoding="utf-8").read()
    want = generated()
    have = current(raw)
    if have is None:
        print("README.md has no STATUS block")
        return 1
    if have == want:
        print("README status block is current.")
        return 0
    if a.check:
        print("README status block is STALE. Regenerate with:")
        print("  python tools/refresh_status_block.py")
        return 1

    m = re.search(r"<!-- STATUS:BEGIN.*?<!-- STATUS:END -->", raw, re.S)
    head = raw[:m.start()]
    tail = raw[m.end():]
    # The opening marker carries descriptive text:
    #
    #     <!-- STATUS:BEGIN generated by tools/progress_json.py - do not edit by hand -->
    #
    # Slicing a fixed width for it truncates the marker to `<!-- STATUS:BEGIN ge`
    # and drops the closing `-->`, which leaves the regex still matching (it does
    # not require a well-formed comment) and so reports "current" on a block that is
    # no longer the one CI reads. The marker is delimited by the *first* `-->` after
    # the block opens, so find that rather than assuming a length.
    marker = raw[m.start():raw.index("-->", m.start()) + len("-->")]
    io.open(README, "w", encoding="utf-8", newline="").write(
        head + marker + "\n" + want + "\n" + END + tail)
    print("README status block regenerated (%d rows)."
          % len(want.splitlines()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
