/* rtld.gflib3 - 1 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace gflib3 {
void nn_ro_detail_g_pRoDebugFlag();  // 0x440

}  // namespace gflib3
