/* sdk.field - 1 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace field {
void SecondFieldOffset();  // 0x3ccdf0

}  // namespace field
