/* subsdk0.field - 2 recovered functions.
 * Declarations only; bodies live in the matching .cpp.
 * Generated by tools/decomp_project.py -- do not hand-edit.
 */
#pragma once

namespace field {
void Deinterlace1stField();  // 0x2c1860
void Deinterlace2ndField();  // 0x2c1a90

}  // namespace field
